Repository RooCodeInc/Roo-Code, pull requests merged in 2025-10, with the labels that each got.

#8410 fix: Addresses overeager 'there are unsaved changes' dialog in settings
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/__tests__/SettingsView.change-detection.spec.tsx
  webview-ui/src/components/settings/__tests__/SettingsView.unsaved-changes.spec.tsx
Labels: bug, size:XL, lgtm, PR - Needs Review

#8481 Deprecate free grok 4 fast
  packages/types/src/model.ts
  packages/types/src/providers/roo.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/__tests__/ModelPicker.deprecated.spec.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: size:L, lgtm, UI/UX, Issue/PR - Triage

#8491 chore: add changeset for v3.28.15
  .changeset/v3.28.15.md
  releases/3.28.15-release.png
Labels: changelog-ready, size:S

#8519 Release: v1.81.0
  packages/types/npm/package.metadata.json
Labels: size:XS

#8535 Release: v1.82.0
  packages/types/npm/package.metadata.json
Labels: size:XS

#8559 Revert "feat: Experiment: Show a bit of stats in Cloud tab to help users discover there's more in Cloud"
  packages/cloud/src/CloudAPI.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/__tests__/ContextWindowProgress.spec.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ContextWindowProgress.tsx
  webview-ui/src/components/chat/TaskHeader.tsx
  webview-ui/src/components/chat/__tests__/TaskHeader.spec.tsx
  webview-ui/src/components/cloud/CloudView.tsx
  webview-ui/src/components/cloud/UsagePreview.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/ca/cloud.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/de/cloud.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/cloud.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/es/cloud.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/fr/cloud.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hi/cloud.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/id/cloud.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/it/cloud.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ja/cloud.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/ko/cloud.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/nl/cloud.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pl/cloud.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt-BR/cloud.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/ru/cloud.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/tr/cloud.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/vi/cloud.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-CN/cloud.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/cloud.json
  webview-ui/src/utils/format.ts
Labels: size:XL
