Repository RooCodeInc/Roo-Code, pull requests merged in 2025-08, with the labels that each got.

#6477 fix: linter not applied to locales/*/README.md
  .github/workflows/update-contributors.yml
Labels: bug, size:XS, lgtm, PR - Needs Review

#6538 Clean up the auto-approve UI
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/AutoApproveToggle.tsx
  webview-ui/src/components/settings/MaxCostInput.tsx
  webview-ui/src/components/settings/MaxLimitInputs.tsx
  webview-ui/src/components/settings/MaxRequestsInput.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: size:L, lgtm, UI/UX, Issue/PR - Triage

#6537 More tolerant search/replace match
  src/core/diff/strategies/__tests__/multi-search-replace.spec.ts
  src/core/diff/strategies/multi-file-search-replace.ts
  src/core/diff/strategies/multi-search-replace.ts
Labels: enhancement, size:M, lgtm, PR - Needs Review

#6552 fix: Fix VB.NET indexing by implementing fallback chunking system
  src/services/code-index/processors/__tests__/parser.vb.spec.ts
  src/services/code-index/processors/parser.ts
  src/services/code-index/shared/supported-extensions.ts
  src/services/tree-sitter/index.ts
Labels: bug, documentation, size:L, PR - Needs Preliminary Review

#6562 Add Qwen 3 Coder from Cerebras
  packages/types/src/providers/cerebras.ts
  src/api/providers/__tests__/cerebras.spec.ts
  src/api/providers/cerebras.ts
Labels: enhancement, size:M, lgtm, Issue/PR - Triage

#6564 Release v3.25.5
  .changeset/v3.25.5.md
Labels: changelog-ready, size:S

#6540 Cloud: support syncing provider profiles from the cloud
  packages/types/src/cloud.ts
  packages/types/src/provider-settings.ts
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.spec.ts
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:XL, lgtm, Issue/PR - Triage

#6606 Task and TaskProvider event emitter cleanup + a few new events
  apps/vscode-e2e/src/suite/markdown-lists.test.ts
  apps/vscode-e2e/src/suite/modes.test.ts
  apps/vscode-e2e/src/suite/subtasks.test.ts
  apps/vscode-e2e/src/suite/task.test.ts
  apps/vscode-e2e/src/suite/tools/apply-diff.test.ts
  apps/vscode-e2e/src/suite/tools/execute-command.test.ts
  apps/vscode-e2e/src/suite/tools/insert-content.test.ts
  apps/vscode-e2e/src/suite/tools/list-files.test.ts
  apps/vscode-e2e/src/suite/tools/read-file.test.ts
  apps/vscode-e2e/src/suite/tools/search-and-replace.test.ts
  apps/vscode-e2e/src/suite/tools/search-files.test.ts
  apps/vscode-e2e/src/suite/tools/use-mcp-tool.test.ts
  apps/vscode-e2e/src/suite/tools/write-to-file.test.ts
  apps/vscode-e2e/src/suite/utils.ts
  packages/cloud/src/CloudAPI.ts
  packages/cloud/src/CloudService.ts
  packages/cloud/src/CloudSettingsService.ts
  packages/cloud/src/CloudShareService.ts
  packages/cloud/src/ShareService.ts
  packages/cloud/src/StaticSettingsService.ts
  packages/cloud/src/TelemetryClient.ts
  packages/cloud/src/__tests__/CloudService.test.ts
  packages/cloud/src/__tests__/CloudSettingsService.test.ts
  packages/cloud/src/__tests__/CloudShareService.test.ts
  packages/cloud/src/__tests__/auth/WebAuthService.spec.ts
  packages/cloud/src/auth/AuthService.ts
  packages/cloud/src/auth/StaticTokenAuthService.ts
  packages/cloud/src/auth/WebAuthService.ts
  packages/cloud/src/config.ts
  packages/cloud/src/errors.ts
  packages/cloud/src/index.ts
  packages/types/src/api.ts
  packages/types/src/cloud.ts
  packages/types/src/events.ts
  packages/types/src/index.ts
  packages/types/src/ipc.ts
  packages/types/src/message.ts
  packages/types/src/task.ts
  src/core/task/Task.ts
  src/core/tools/attemptCompletionTool.ts
  src/core/tools/newTaskTool.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/__tests__/ClineProvider.sticky-mode.spec.ts
  src/extension/api.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
Labels: enhancement, size:XL, lgtm, Issue/PR - Triage

#6610 Bump @roo-code/types to v1.42.0
  packages/types/npm/package.json
  packages/types/package.json
  packages/types/tsup.config.ts
Labels: size:S, Issue/PR - Triage

#6623 Fix the UI for approving chained commands
  webview-ui/src/components/chat/CommandExecution.tsx
  webview-ui/src/components/chat/CommandPatternSelector.tsx
  webview-ui/src/components/chat/__tests__/CommandExecution.spec.tsx
  webview-ui/src/components/chat/__tests__/CommandPatternSelector.spec.tsx
Labels: size:L, UI/UX

#6359 Changing checkpoint timing and ensuring checkpoints work
  src/core/assistant-message/presentAssistantMessage.ts
  src/core/checkpoints/index.ts
  src/core/task/Task.ts
  src/services/checkpoints/ShadowCheckpointService.ts
  webview-ui/src/components/chat/checkpoints/CheckpointMenu.tsx
Labels: bug, size:L, lgtm, PR - Needs Review

#6640 Bump @roo-code/types to v1.43.0
  packages/types/README.md
  packages/types/npm/package.json
  packages/types/package.json
Labels: size:M, lgtm

#6611 Use @roo-code/cloud from npm
  packages/cloud/eslint.config.mjs
  packages/cloud/package.json
  packages/cloud/src/CloudAPI.ts
  packages/cloud/src/CloudService.ts
  packages/cloud/src/CloudSettingsService.ts
  packages/cloud/src/CloudShareService.ts
  packages/cloud/src/RefreshTimer.ts
  packages/cloud/src/SettingsService.ts
  packages/cloud/src/StaticSettingsService.ts
  packages/cloud/src/TelemetryClient.ts
  packages/cloud/src/__mocks__/vscode.ts
  packages/cloud/src/__tests__/CloudService.integration.test.ts
  packages/cloud/src/__tests__/CloudService.test.ts
  packages/cloud/src/__tests__/CloudSettingsService.test.ts
  packages/cloud/src/__tests__/CloudShareService.test.ts
  packages/cloud/src/__tests__/RefreshTimer.test.ts
  packages/cloud/src/__tests__/StaticSettingsService.test.ts
  packages/cloud/src/__tests__/TelemetryClient.test.ts
  packages/cloud/src/__tests__/auth/StaticTokenAuthService.spec.ts
  packages/cloud/src/__tests__/auth/WebAuthService.spec.ts
  packages/cloud/src/auth/AuthService.ts
  packages/cloud/src/auth/StaticTokenAuthService.ts
  packages/cloud/src/auth/WebAuthService.ts
  packages/cloud/src/auth/index.ts
  packages/cloud/src/config.ts
  packages/cloud/src/errors.ts
  packages/cloud/src/index.ts
  packages/cloud/src/types.ts
  packages/cloud/src/utils.ts
  packages/cloud/tsconfig.json
  packages/cloud/vitest.config.ts
  pnpm-lock.yaml
  src/extension.ts
  src/package.json
Labels: size:XXL, Issue/PR - Triage

#5341 use assistantMessageParser class instead of parseAssistantMessage
  packages/types/src/experiment.ts
  src/core/assistant-message/AssistantMessageParser.ts
  src/core/assistant-message/__tests__/AssistantMessageParser.spec.ts
  src/core/task/Task.ts
  src/shared/__tests__/experiments.spec.ts
  src/shared/experiments.ts
  webview-ui/src/context/__tests__/ExtensionStateContext.spec.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm, PR - Needs Review

#6422 feat(ui): Make mode selection dropdowns responsive
  webview-ui/src/components/modes/ModesView.tsx
Labels: size:XS, lgtm, UI/UX, PR - Needs Review

#6675 Bump @roo-code/types to v1.44.0
  packages/types/npm/package.json
  packages/types/src/cloud.ts
  packages/types/src/global-settings.ts
Labels: size:XS

#6677 Extension bridge
  pnpm-lock.yaml
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/extension.ts
  src/package.json
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/utils/remoteControl.ts
  webview-ui/src/components/account/AccountView.tsx
  webview-ui/src/components/account/__tests__/AccountView.spec.tsx
  webview-ui/src/components/modes/ModesView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/i18n/locales/ca/account.json
  webview-ui/src/i18n/locales/de/account.json
  webview-ui/src/i18n/locales/en/account.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/account.json
  webview-ui/src/i18n/locales/fr/account.json
  webview-ui/src/i18n/locales/hi/account.json
  webview-ui/src/i18n/locales/id/account.json
  webview-ui/src/i18n/locales/it/account.json
  webview-ui/src/i18n/locales/ja/account.json
  webview-ui/src/i18n/locales/ko/account.json
  webview-ui/src/i18n/locales/nl/account.json
  webview-ui/src/i18n/locales/pl/account.json
  webview-ui/src/i18n/locales/pt-BR/account.json
  webview-ui/src/i18n/locales/ru/account.json
  webview-ui/src/i18n/locales/tr/account.json
  webview-ui/src/i18n/locales/vi/account.json
  webview-ui/src/i18n/locales/zh-CN/account.json
  webview-ui/src/i18n/locales/zh-TW/account.json
Labels: size:L, lgtm, Issue/PR - Triage

#6652 Add the fireworks AI provider
  .github/ISSUE_TEMPLATE/bug_report.yml
  packages/types/src/global-settings.ts
  packages/types/src/provider-settings.ts
  packages/types/src/providers/fireworks.ts
  packages/types/src/providers/index.ts
  src/api/index.ts
  src/api/providers/__tests__/fireworks.spec.ts
  src/api/providers/fireworks.ts
  src/api/providers/index.ts
  src/shared/ProfileValidator.ts
  src/shared/__tests__/ProfileValidator.spec.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/settings/providers/Fireworks.tsx
  webview-ui/src/components/settings/providers/index.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/utils/validate.ts
Labels: enhancement, size:XL, lgtm, PR - Needs Review

#6561 Redesigned Task Header
  webview-ui/src/__tests__/ContextWindowProgress.spec.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/ContextWindowProgress.tsx
  webview-ui/src/components/chat/ShareButton.tsx
  webview-ui/src/components/chat/TaskActions.tsx
  webview-ui/src/components/chat/TaskHeader.tsx
  webview-ui/src/components/chat/__tests__/TaskActions.spec.tsx
  webview-ui/src/components/chat/__tests__/TaskHeader.spec.tsx
  webview-ui/src/components/common/Thumbnails.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, lgtm, UI/UX, PR - Draft / In Progress

#6734 feat: add OpenAI GPT OSS model to Cerebras providers
  packages/types/src/providers/cerebras.ts
Labels: enhancement, size:S, lgtm

#6735 Revert "Changesets config tweak (#6733)"
  .changeset/config.json
Labels: size:XS

#6697 Fix: Resolve Memory Leak in ChatView Virtual Scrolling Implementation
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:L, lgtm, PR - Needs Review

#6724 Add swift files to fallback list
  src/services/code-index/processors/__tests__/parser.vb.spec.ts
  src/services/code-index/shared/supported-extensions.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#6780 fix: Replace scrollToIndex with scrollTo to fix scroll jitter
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:M, lgtm, PR - Needs Review

#6779 fix: prevent unnecessary MCP server refresh on settings save (#6772)
  src/core/webview/__tests__/webviewMessageHandler.spec.ts
  src/core/webview/webviewMessageHandler.ts
Labels: bug, size:L, lgtm, PR - Needs Preliminary Review

#6795 Bring back "Use @roo-code/cloud from npm"
  .dockerignore
  packages/cloud/eslint.config.mjs
  packages/cloud/package.json
  packages/cloud/src/CloudAPI.ts
  packages/cloud/src/CloudService.ts
  packages/cloud/src/CloudSettingsService.ts
  packages/cloud/src/CloudShareService.ts
  packages/cloud/src/RefreshTimer.ts
  packages/cloud/src/SettingsService.ts
  packages/cloud/src/StaticSettingsService.ts
  packages/cloud/src/TelemetryClient.ts
  packages/cloud/src/__mocks__/vscode.ts
  packages/cloud/src/__tests__/CloudService.integration.test.ts
  packages/cloud/src/__tests__/CloudService.test.ts
  packages/cloud/src/__tests__/CloudSettingsService.test.ts
  packages/cloud/src/__tests__/CloudShareService.test.ts
  packages/cloud/src/__tests__/RefreshTimer.test.ts
  packages/cloud/src/__tests__/StaticSettingsService.test.ts
  packages/cloud/src/__tests__/TelemetryClient.test.ts
  packages/cloud/src/__tests__/auth/StaticTokenAuthService.spec.ts
  packages/cloud/src/__tests__/auth/WebAuthService.spec.ts
  packages/cloud/src/auth/AuthService.ts
  packages/cloud/src/auth/StaticTokenAuthService.ts
  packages/cloud/src/auth/WebAuthService.ts
  packages/cloud/src/auth/index.ts
  packages/cloud/src/config.ts
  packages/cloud/src/errors.ts
  packages/cloud/src/index.ts
  packages/cloud/src/types.ts
  packages/cloud/src/utils.ts
  packages/cloud/tsconfig.json
  packages/cloud/vitest.config.ts
  packages/evals/Dockerfile.runner
  pnpm-lock.yaml
  src/extension.ts
  src/package.json
Labels: size:XXL, Issue/PR - Triage

#6799 Support linking to @roo-code/cloud in Roo-Code repo
  package.json
  scripts/link-packages.js
  src/extension.ts
  src/tsconfig.json
Labels: enhancement, size:L, lgtm, Issue/PR - Triage

#6808 Fix rounding of max tokens
  src/shared/api.ts
Labels: bug, size:XS

#6809 chore: add changeset for v3.25.9
  .changeset/v3.25.9.md
Labels: changelog-ready, size:XS

#6878 fix(mcp): Revert changes causing startup issues and remove refresh notifications
  src/core/webview/__tests__/webviewMessageHandler.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/services/mcp/McpHub.ts
Labels: bug, size:L, lgtm, Issue/PR - Triage

#6778 Bedrock: workaround LiteLLM passthrough issues
  src/api/providers/bedrock.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#6864 GPT5 OpenAI Fix
  packages/types/src/message.ts
  packages/types/src/model.ts
  packages/types/src/provider-settings.ts
  packages/types/src/providers/openai.ts
  src/api/index.ts
  src/api/providers/__tests__/openai-native.spec.ts
  src/api/providers/openai-native.ts
  src/api/providers/openai.ts
  src/api/providers/requesty.ts
  src/api/transform/model-params.ts
  src/api/transform/reasoning.ts
  src/core/task/Task.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: bug, size:XXL, lgtm, PR - Needs Review

#6875 Add IO Intelligence Provider
  packages/types/src/global-settings.ts
  packages/types/src/provider-settings.ts
  packages/types/src/providers/index.ts
  packages/types/src/providers/io-intelligence.ts
  src/api/index.ts
  src/api/providers/__tests__/io-intelligence.spec.ts
  src/api/providers/fetchers/__tests__/modelCache.spec.ts
  src/api/providers/fetchers/io-intelligence.ts
  src/api/providers/fetchers/modelCache.ts
  src/api/providers/index.ts
  src/api/providers/io-intelligence.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ProfileValidator.ts
  src/shared/__tests__/ProfileValidator.spec.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/settings/providers/IOIntelligence.tsx
  webview-ui/src/components/settings/providers/index.ts
  webview-ui/src/components/ui/hooks/__tests__/useSelectedModel.spec.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/utils/__tests__/validate.test.ts
  webview-ui/src/utils/validate.ts
Labels: documentation, enhancement, size:XL, lgtm, Issue/PR - Triage

#6961 Handle bridge config fetch errors
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/extension.ts
Labels: bug, size:S

#6686 fix: add --no-sandbox flag to browser launch options
  src/services/browser/UrlContentFetcher.ts
  src/services/browser/__tests__/UrlContentFetcher.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#6946 Update and improve zh-TW Traditional Chinese locale
  webview-ui/src/i18n/locales/zh-TW/account.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/common.json
  webview-ui/src/i18n/locales/zh-TW/history.json
  webview-ui/src/i18n/locales/zh-TW/humanRelay.json
  webview-ui/src/i18n/locales/zh-TW/marketplace.json
  webview-ui/src/i18n/locales/zh-TW/mcp.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/i18n/locales/zh-TW/welcome.json
Labels: documentation, size:XS, Issue/PR - Triage

#6998 Add minimal reasoning support to OpenRouter
  src/api/transform/__tests__/reasoning.spec.ts
  src/api/transform/reasoning.ts
  webview-ui/src/components/settings/ThinkingBudget.tsx
Labels: enhancement, size:L, lgtm

#7005 feat: Update Claude Sonnet 4 context window to 1 million tokens
  packages/types/src/provider-settings.ts
  packages/types/src/providers/anthropic.ts
  src/api/providers/anthropic.ts
  webview-ui/src/components/settings/ModelInfoView.tsx
  webview-ui/src/components/settings/providers/Anthropic.tsx
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, PR - Needs Preliminary Review

#7018 chore: add changeset for v3.25.12
  .changeset/v3.25.12.md
Labels: changelog-ready, size:S

#6948 Remove deprecated GPT-4.5 Preview model
  packages/types/src/providers/openai.ts
Labels: size:XS, lgtm, Issue/PR - Triage

#7033 Release v3.25.13
  .changeset/v3.25.13.md
Labels: documentation, size:XS

#7044 Fix webview in dev mode
  knip.json
  pnpm-lock.yaml
  scripts/link-packages.js
  src/shared/cloud.ts
  webview-ui/package.json
  webview-ui/src/__mocks__/vscode.ts
  webview-ui/src/components/account/AccountView.tsx
  webview-ui/src/components/chat/ShareButton.tsx
  webview-ui/src/components/settings/ApiConfigManager.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/providers/Glama.tsx
  webview-ui/src/components/settings/providers/IOIntelligence.tsx
  webview-ui/src/components/settings/providers/LiteLLM.tsx
  webview-ui/src/components/settings/providers/OpenAICompatible.tsx
  webview-ui/src/components/settings/providers/OpenRouter.tsx
  webview-ui/src/components/settings/providers/Requesty.tsx
  webview-ui/src/components/settings/providers/Unbound.tsx
  webview-ui/src/components/settings/utils/__tests__/organizationFilters.test.ts
  webview-ui/src/components/settings/utils/organizationFilters.ts
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/utils/__tests__/validate.test.ts
  webview-ui/src/utils/validate.ts
  webview-ui/vite.config.ts
Labels: bug, size:M

#7056 Fix: AWS Bedrock 1M context - Move anthropic_beta to additionalModelRequestFields
  src/api/providers/__tests__/bedrock.spec.ts
  src/api/providers/bedrock.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#7060 Release v3.25.14
  .changeset/v3.25.14.md
Labels: documentation, size:XS

#6925 Fix allowedMaxRequests and allowedMaxCost values not showing in the settings UI
  webview-ui/src/components/settings/SettingsView.tsx
Labels: bug, size:XS, lgtm, PR - Needs Review

#6922 fix: reset condensing state when switching tasks
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:XS, lgtm, PR - Needs Preliminary Review

#6206 feat: implement sitemap generation in TypeScript and remove XML file
  apps/web-roo-code/.env.example
  apps/web-roo-code/.gitignore
  apps/web-roo-code/.npmrc
  apps/web-roo-code/next-sitemap.config.cjs
  apps/web-roo-code/package.json
  apps/web-roo-code/src/app/sitemap.xml
  knip.json
  pnpm-lock.yaml
Labels: enhancement, size:M, lgtm, PR - Needs Review

#7102 fix: add /evals page to sitemap generation
  apps/web-roo-code/next-sitemap.config.cjs
Labels: bug, size:S, PR - Needs Review

#7103 Release v3.25.15
  .changeset/v3.25.15.md
Labels: changelog-ready, size:XS, Issue/PR - Triage

#7096 feat(web): fill missing SEO-related values
  apps/web-roo-code/src/app/enterprise/page.tsx
  apps/web-roo-code/src/app/evals/page.tsx
  apps/web-roo-code/src/app/layout.tsx
  apps/web-roo-code/src/app/privacy/page.tsx
  apps/web-roo-code/src/app/robots.ts
  apps/web-roo-code/src/app/terms/page.tsx
  apps/web-roo-code/src/lib/seo.ts
Labels: enhancement, size:L, lgtm, PR - Needs Review

#7035 Refactor task execution system: improve call stack management
  src/core/task/Task.ts
  src/core/task/__tests__/Task.dispose.test.ts
Labels: bug, size:XXL, lgtm, PR - Needs Review

#7113 Fix: Enable save button for provider dropdown and checkbox changes
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/__tests__/ThinkingBudget.spec.tsx
  webview-ui/src/components/settings/providers/HuggingFace.tsx
  webview-ui/src/components/settings/providers/Unbound.tsx
Labels: bug, size:M, lgtm, UI/UX, PR - Needs Review

#7122 Add an API for resuming tasks by ID
  packages/ipc/README.md
  packages/types/npm/package.metadata.json
  packages/types/src/__tests__/ipc.test.ts
  packages/types/src/ipc.ts
  src/extension/api.ts
Labels: documentation, enhancement, size:L

#7140 Make enhance with task history default to true
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  webview-ui/src/components/settings/PromptsSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: enhancement, size:S, lgtm

#7137 fix: use native Ollama API instead of OpenAI compatibility layer
  pnpm-lock.yaml
  src/api/index.ts
  src/api/providers/__tests__/native-ollama.spec.ts
  src/api/providers/native-ollama.ts
  src/package.json
Labels: bug, size:L, lgtm

#7128 Emit event when a task ask requires interaction
  packages/types/npm/package.metadata.json
  packages/types/src/events.ts
  packages/types/src/message.ts
  packages/types/src/task.ts
  pnpm-lock.yaml
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/package.json
Labels: enhancement, size:L, Issue/PR - Triage

#7151 Release v3.25.16
  .changeset/v3.25.16.md
Labels: changelog-ready, size:S

#7157 Fix terminal reuse logic
  src/core/tools/__tests__/executeCommand.spec.ts
  src/core/tools/executeCommandTool.ts
  src/integrations/terminal/TerminalRegistry.ts
Labels: bug, size:M

#7212 Expose thinking tokens for `roo/sonic`
  .env.sample
  packages/types/src/providers/roo.ts
  src/api/providers/__tests__/roo.spec.ts
  src/api/providers/base-openai-compatible-provider.ts
  src/api/providers/roo.ts
Labels: enhancement, size:M, lgtm, Issue/PR - Triage

#7222 feat: simple read_file tool for single-file-only models
  packages/types/src/index.ts
  packages/types/src/single-file-read-models.ts
  src/core/assistant-message/presentAssistantMessage.ts
  src/core/prompts/system.ts
  src/core/prompts/tools/index.ts
  src/core/prompts/tools/simple-read-file.ts
  src/core/task/Task.ts
  src/core/tools/simpleReadFileTool.ts
Labels: enhancement, size:L, lgtm, Issue/PR - Triage

#7201 feat: add new models and update configurations for vscode-lm
  packages/types/src/providers/vscode-llm.ts
Labels: enhancement, size:M, lgtm, PR - Needs Review

#7239 Fix: Add 'roo' provider to checkExistKey function
  src/shared/checkExistApiConfig.ts
Labels: bug, size:XS, lgtm

#7242 chore: add changeset for v3.25.19
  .changeset/v3.25.19.md
Labels: changelog-ready, size:XS

#7244 Add announcement for Sonic model
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/components/chat/__tests__/Announcement.spec.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, UI/UX

#7245 chore: add changeset for v3.25.20
  .changeset/v3.25.20.md
Labels: changelog-ready, size:XS

#7258 Add MODELS_BY_PROVIDER for use in @roo-code/cloud
  packages/types/npm/package.metadata.json
  packages/types/src/model.ts
  packages/types/src/provider-settings.ts
  packages/types/src/providers/bedrock.ts
  packages/types/src/providers/index.ts
  packages/types/src/providers/vscode-llm.ts
Labels: enhancement, size:L, Issue/PR - Triage

#7164 refactor(storage): better fs check
  src/utils/__tests__/storage.spec.ts
  src/utils/storage.ts
Labels: size:L, lgtm, PR - Needs Review

#6967 feat: add OpenAI context window error handling
  src/core/context/context-management/__tests__/context-error-handling.test.ts
  src/core/context/context-management/context-error-handling.ts
  src/core/task/Task.ts
Labels: bug, enhancement, size:XL, PR - Needs Review

#7299 Evals web app fixes / tweaks
  apps/web-evals/.env
  apps/web-evals/scripts/check-services.sh
  apps/web-evals/src/app/runs/new/new-run.tsx
  apps/web-evals/src/app/runs/new/settings-diff.tsx
Labels: size:M, UI/UX

#6775 feat: add optional todos parameter to new_task tool with experimental setting (#6329)
  packages/types/src/experiment.ts
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/architect-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/ask-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-disabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-enabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/partial-reads-enabled.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/consistent-system-prompt.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-computer-use-support.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-false.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-true.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-undefined.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-different-viewport-size.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-mcp-hub-provided.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-undefined-mcp-hub.snap
  src/core/prompts/__tests__/system-prompt.spec.ts
  src/core/prompts/sections/__tests__/custom-instructions.spec.ts
  src/core/prompts/sections/tool-use.ts
  src/core/prompts/tools/__tests__/new-task.spec.ts
  src/core/prompts/tools/new-task.ts
  src/core/prompts/types.ts
  src/core/task/Task.ts
  src/core/tools/__tests__/newTaskTool.spec.ts
  src/core/tools/newTaskTool.ts
  src/core/tools/updateTodoListTool.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/generateSystemPrompt.ts
  src/package.json
  src/package.nls.json
  src/shared/ExtensionMessage.ts
  src/shared/tools.ts
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.spec.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm, PR - Needs Preliminary Review

#7302 refactor: Remove exceptions from RooHandler constructor
  src/api/index.ts
  src/api/providers/__tests__/roo.spec.ts
  src/api/providers/roo.ts
  src/core/webview/webviewMessageHandler.ts
Labels: size:M, lgtm, PR - Needs Review

#7305 fix: ensure subtask results are provided to GPT-5 in OpenAI Responses API
  src/core/task/Task.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#7326 chore: add changeset for v3.25.22
  .changeset/v3.25.22.md
Labels: changelog-ready, size:XS

#7332 Revert "feat: enable loading Roo modes from multiple files in .roo/roo_modes directory"
  src/core/config/CustomModesManager.ts
  src/core/config/__tests__/CustomModesManager.spec.ts
Labels: bug, size:XL, lgtm

#7338 chore: add changeset for v3.25.23
  .changeset/v3.25.23.md
Labels: size:XS

#7176 Show cache read and write prices for OpenRouter inference providers
  src/api/providers/fetchers/__tests__/openrouter.spec.ts
  src/api/providers/fetchers/openrouter.ts
  webview-ui/src/components/ui/hooks/useOpenRouterModelProviders.ts
Labels: bug, size:M, lgtm, PR - Needs Preliminary Review

#7363 fix: resolve newTaskRequireTodos setting not working correctly
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/architect-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/ask-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-disabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-enabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/partial-reads-enabled.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/consistent-system-prompt.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-computer-use-support.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-false.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-true.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-undefined.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-different-viewport-size.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-mcp-hub-provided.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-undefined-mcp-hub.snap
  src/core/prompts/sections/tool-use.ts
  src/core/prompts/tools/__tests__/new-task.spec.ts
  src/core/prompts/tools/new-task.ts
  src/core/tools/__tests__/newTaskTool.spec.ts
  src/core/tools/newTaskTool.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#7378 Fix requesty model listing
  src/api/providers/fetchers/requesty.ts
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#7391 fix: add todos parameter to new_task tool usage in issue-fixer mode
  .roo/rules-issue-fixer/1_Workflow.xml
  .roo/rules-issue-fixer/2_best_practices.xml
Labels: documentation, size:XS, PR - Needs Review

#7390 Handle substitution patterns in command validation
  webview-ui/src/utils/__tests__/command-validation.spec.ts
  webview-ui/src/utils/command-validation.ts
Labels: size:L, lgtm, Issue/PR - Triage

#7255 update privacy policy to account for stealth model
  PRIVACY.md
  apps/web-roo-code/src/app/privacy/page.tsx
Labels: documentation, size:S, lgtm, PR - Needs Review

#7392 feat: Hide static providers with no models from provider list
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.provider-filtering.spec.tsx
Labels: enhancement, size:L, lgtm, PR - Needs Review

#7394 fix: preserve user input when selecting follow-up choices
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:S, lgtm, PR - Needs Review

#7400 feat: update /init command to focus only on non-obvious discoveries
  src/services/command/__tests__/built-in-commands.spec.ts
  src/services/command/built-in-commands.ts
Labels: enhancement, size:L, lgtm, Issue/PR - Triage

#7403 Mark code-workspace files as protected
  src/core/protect/RooProtectedController.ts
  src/core/protect/__tests__/RooProtectedController.spec.ts
Labels: enhancement, size:S, lgtm

#7404 Update list of default allowed commands
  src/package.json
  src/utils/__tests__/migrateSettings.spec.ts
  src/utils/migrateSettings.ts
Labels: size:L, lgtm, Issue/PR - Triage

#7405 Follow symlinks in rooignore checks
  src/core/ignore/RooIgnoreController.ts
  src/core/ignore/__tests__/RooIgnoreController.spec.ts
Labels: size:M, lgtm, PR - Needs Review

#7396 feat: Add Vercel AI Gateway provider integration
  packages/types/npm/package.metadata.json
  packages/types/src/global-settings.ts
  packages/types/src/provider-settings.ts
  packages/types/src/providers/index.ts
  packages/types/src/providers/vercel-ai-gateway.ts
  pnpm-lock.yaml
  src/api/index.ts
  src/api/providers/__tests__/vercel-ai-gateway.spec.ts
  src/api/providers/fetchers/__tests__/vercel-ai-gateway.spec.ts
  src/api/providers/fetchers/modelCache.ts
  src/api/providers/fetchers/vercel-ai-gateway.ts
  src/api/providers/index.ts
  src/api/providers/vercel-ai-gateway.ts
  src/api/transform/caching/__tests__/vercel-ai-gateway.spec.ts
  src/api/transform/caching/vercel-ai-gateway.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/__tests__/webviewMessageHandler.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/package.json
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/settings/providers/VercelAiGateway.tsx
  webview-ui/src/components/settings/providers/index.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/utils/__tests__/validate.test.ts
  webview-ui/src/utils/validate.ts
Labels: enhancement, size:XXL, lgtm, PR - Needs Preliminary Review

#7182 feat: Enable on-disk storage for Qdrant vectors and HNSW index
  src/services/code-index/vector-store/__tests__/qdrant-client.spec.ts
  src/services/code-index/vector-store/qdrant-client.ts
Labels: enhancement, size:M, PR - Needs Preliminary Review

#7443 fix: remove duplicate cache display in task header
  webview-ui/src/components/chat/TaskHeader.tsx
Labels: size:S, lgtm, UI/UX, Issue/PR - Triage

#7436 Random chat text area cleanup
  apps/web-evals/package.json
  pnpm-lock.yaml
  src/core/webview/webviewMessageHandler.ts
  src/shared/TelemetrySetting.ts
  src/shared/combineCommandSequences.ts
  webview-ui/src/components/chat/ApiConfigSelector.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/CodeIndexPopover.tsx
  webview-ui/src/components/chat/EditModeControls.tsx
  webview-ui/src/components/chat/IconButton.tsx
  webview-ui/src/components/chat/IndexingStatusBadge.tsx
  webview-ui/src/components/chat/ModeSelector.tsx
  webview-ui/src/components/chat/SlashCommandsPopover.tsx
  webview-ui/src/components/chat/__tests__/ApiConfigSelector.spec.tsx
  webview-ui/src/components/chat/__tests__/ChatTextArea.spec.tsx
  webview-ui/src/components/chat/__tests__/ChatView.keyboard-fix.spec.tsx
  webview-ui/src/components/chat/__tests__/ChatView.spec.tsx
  webview-ui/src/components/chat/__tests__/EditModeControls.spec.tsx
  webview-ui/src/components/chat/__tests__/IndexingStatusBadge.spec.tsx
  webview-ui/src/components/chat/__tests__/ModeSelector.spec.tsx
  webview-ui/src/components/common/TelemetryBanner.tsx
  webview-ui/src/components/settings/About.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/ui/standard-tooltip.tsx
  webview-ui/src/components/ui/tooltip.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/hooks/useTooltip.ts
  webview-ui/src/index.css
  webview-ui/src/utils/TelemetryClient.ts
  webview-ui/src/utils/test-utils.tsx
Labels: size:XXL, lgtm, UI/UX, PR - Needs Review

#7448 Always set remoteControlEnabled to true for cloud agents
  src/extension.ts
Labels: size:S

#7445 Add support for Vercel embeddings
  packages/types/src/codebase-index.ts
  packages/types/src/global-settings.ts
  src/api/providers/fetchers/vercel-ai-gateway.ts
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/embeddings.json
  src/i18n/locales/de/embeddings.json
  src/i18n/locales/en/embeddings.json
  src/i18n/locales/es/embeddings.json
  src/i18n/locales/fr/embeddings.json
  src/i18n/locales/hi/embeddings.json
  src/i18n/locales/id/embeddings.json
  src/i18n/locales/it/embeddings.json
  src/i18n/locales/ja/embeddings.json
  src/i18n/locales/ko/embeddings.json
  src/i18n/locales/nl/embeddings.json
  src/i18n/locales/pl/embeddings.json
  src/i18n/locales/pt-BR/embeddings.json
  src/i18n/locales/ru/embeddings.json
  src/i18n/locales/tr/embeddings.json
  src/i18n/locales/vi/embeddings.json
  src/i18n/locales/zh-CN/embeddings.json
  src/i18n/locales/zh-TW/embeddings.json
  src/services/code-index/config-manager.ts
  src/services/code-index/embedders/__tests__/vercel-ai-gateway.spec.ts
  src/services/code-index/embedders/vercel-ai-gateway.ts
  src/services/code-index/interfaces/config.ts
  src/services/code-index/interfaces/embedder.ts
  src/services/code-index/interfaces/manager.ts
  src/services/code-index/service-factory.ts
  src/shared/WebviewMessage.ts
  src/shared/embeddingModels.ts
  webview-ui/src/components/chat/CodeIndexPopover.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm, PR - Needs Preliminary Review

#7461 Remove dot before model display
  webview-ui/src/components/chat/ApiConfigSelector.tsx
Labels: size:XS, UI/UX, Issue/PR - Triage

#7463 Update 3.26.1 changeset
  .changeset/v3.26.1.md
Labels: size:XS

#7067 Fix GPT-5 Responses API issues with condensing and image support
  packages/types/src/model.ts
  packages/types/src/providers/openai.ts
  pnpm-lock.yaml
  src/api/index.ts
  src/api/providers/__tests__/openai-native.spec.ts
  src/api/providers/openai-native.ts
  src/core/task/Task.ts
  src/core/task/__tests__/Task.spec.ts
  src/core/task/types.ts
  src/package.json
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: bug, size:XXL, lgtm, PR - Needs Review

#7475 Bump cloud to 0.25.0
  pnpm-lock.yaml
  src/package.json
Labels: size:XS

#7479 Make the default image filename more generic
  src/integrations/misc/image-handler.ts
Labels: size:XS

#7467 Show console logging in vitests when the --no-silent flag is set
  src/utils/vitest-verbosity.ts
  src/vitest.config.ts
  src/vitest.setup.ts
  webview-ui/vitest.config.ts
  webview-ui/vitest.setup.ts
Labels: enhancement, size:M, lgtm, PR - Needs Review

#7515 Refactor the extension bridge
  packages/cloud/src/WebAuthService.ts
  packages/cloud/src/bridge/BaseChannel.ts
  packages/cloud/src/bridge/BridgeOrchestrator.ts
  packages/cloud/src/bridge/ExtensionBridgeService.ts
  packages/cloud/src/bridge/ExtensionChannel.ts
  packages/cloud/src/bridge/ExtensionManager.ts
  packages/cloud/src/bridge/SocketTransport.ts
  packages/cloud/src/bridge/TaskChannel.ts
  packages/cloud/src/bridge/TaskManager.ts
  packages/cloud/src/bridge/__tests__/ExtensionChannel.test.ts
  packages/cloud/src/bridge/__tests__/TaskChannel.test.ts
  packages/cloud/src/bridge/index.ts
  packages/cloud/src/importVscode.ts
  packages/cloud/src/index.ts
  packages/types/src/cloud.ts
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/__tests__/ClineProvider.sticky-mode.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/extension.ts
  src/services/mcp/McpHub.ts
  src/services/mdm/MdmService.ts
  src/utils/remoteControl.ts
Labels: size:XXL, Issue/PR - Triage

#7536 refactor: flatten image generation settings structure
  packages/types/src/global-settings.ts
  packages/types/src/provider-settings.ts
  src/core/config/ContextProxy.ts
  src/core/config/__tests__/ContextProxy.spec.ts
  src/core/tools/__tests__/generateImageTool.test.ts
  src/core/tools/generateImageTool.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/checkExistApiConfig.ts
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/components/settings/ImageGenerationSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/__tests__/ImageGenerationSettings.spec.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: size:L, lgtm, PR - Needs Review

#7541 chore: add changeset for v3.26.3
  .changeset/v3.26.3.md
Labels: changelog-ready, size:XS

#7546 Putting the Roo in Roo-leases
  .roo/commands/release.md
  CHANGELOG.md
  releases/3.26.0-release.png
  releases/3.26.1-release.png
  releases/3.26.2-release.png
  releases/3.26.3-release.png
  releases/template.png
Labels: changelog-ready, size:S

#7540 fix: special tokens should not break task processing
  src/utils/__tests__/tiktoken.spec.ts
  src/utils/tiktoken.ts
Labels: bug, size:S, lgtm, PR - Needs Preliminary Review
