Repository RooCodeInc/Roo-Code, pull requests merged in 2025-07, with the labels that each got.

#5242 feat: adding default headers and testing for litellm fetcher
  src/api/providers/fetchers/__tests__/litellm.spec.ts
  src/api/providers/fetchers/litellm.ts
  src/api/providers/router-provider.ts
Labels: enhancement, size:S, lgtm, PR - Needs Review

#5295 Fix #5294: Prevent Architect mode from providing time estimates
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/architect-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-disabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-enabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/partial-reads-enabled.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/consistent-system-prompt.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-computer-use-support.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-false.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-true.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-undefined.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-different-viewport-size.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-mcp-hub-provided.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-undefined-mcp-hub.snap
  src/shared/modes.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#5280 feat: add translation orchestration to PR Fixer mode
  .roo/rules-pr-fixer/1_workflow.xml
  .roo/rules-pr-fixer/2_best_practices.xml
  .roo/rules-pr-fixer/3_common_patterns.xml
  .roo/rules-pr-fixer/4_tool_usage.xml
  .roo/rules-pr-fixer/5_examples.xml
Labels: enhancement, size:L, lgtm, PR - Needs Review

#4284 feat(dx): streamline extension installation and documentation
  README.md
  package.json
  scripts/install-vsix.js
Labels: documentation, enhancement, size:L, lgtm, PR - Needs Preliminary Review

#5308 Suppress mermaid error rendering
  webview-ui/src/components/common/MermaidBlock.tsx
Labels: size:XS, lgtm, PR - Needs Review

#5323 Cloud: support alternate auth token from environment
  packages/cloud/src/CloudService.ts
  packages/cloud/src/SettingsService.ts
  packages/cloud/src/ShareService.ts
  packages/cloud/src/TelemetryClient.ts
  packages/cloud/src/__tests__/CloudService.test.ts
  packages/cloud/src/__tests__/ShareService.test.ts
  packages/cloud/src/__tests__/auth/StaticTokenAuthService.spec.ts
  packages/cloud/src/__tests__/auth/WebAuthService.spec.ts
  packages/cloud/src/auth/AuthService.ts
  packages/cloud/src/auth/StaticTokenAuthService.ts
  packages/cloud/src/auth/WebAuthService.ts
  packages/cloud/src/auth/index.ts
Labels: size:L, lgtm, PR - Needs Review

#5342 Give Mermaid buttons a light background in light mode
  webview-ui/src/components/common/MermaidButton.tsx
Labels: size:XS, lgtm, UI/UX, Issue/PR - Triage

#5347 Add .vscode/ to the list of write-protected files/directories
  src/core/protect/RooProtectedController.ts
  src/core/protect/__tests__/RooProtectedController.spec.ts
Labels: size:XS, lgtm, PR - Needs Review

#5234 feat: integrate security one-pager into website
  apps/web-roo-code/src/app/enterprise/page.tsx
  apps/web-roo-code/src/components/chromes/footer.tsx
  apps/web-roo-code/src/components/chromes/nav-bar.tsx
  apps/web-roo-code/src/lib/constants.ts
Labels: enhancement, size:M, lgtm, UI/UX, PR - Needs Review

#5254 fix access_mcp_resource fails to handle images correctly
  src/core/tools/accessMcpResourceTool.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#5228 feat: add Gemini embedding provider for codebase indexing
  packages/types/src/codebase-index.ts
  packages/types/src/global-settings.ts
  src/services/code-index/__tests__/config-manager.spec.ts
  src/services/code-index/__tests__/service-factory.spec.ts
  src/services/code-index/config-manager.ts
  src/services/code-index/constants/index.ts
  src/services/code-index/embedders/__tests__/gemini.spec.ts
  src/services/code-index/embedders/gemini.ts
  src/services/code-index/embedders/openai-compatible.ts
  src/services/code-index/interfaces/config.ts
  src/services/code-index/interfaces/embedder.ts
  src/services/code-index/interfaces/manager.ts
  src/services/code-index/service-factory.ts
  src/shared/embeddingModels.ts
  webview-ui/src/components/settings/CodeIndexSettings.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm, PR - Needs Review

#5214 fix: support full endpoint URLs in OpenAI Compatible provider (#5212)
  src/services/code-index/embedders/__tests__/openai-compatible.spec.ts
  src/services/code-index/embedders/openai-compatible.ts
Labels: bug, enhancement, size:L, lgtm, PR - Needs Review

#5249 fix: prevent completion sound from replaying when reopening completed tasks (#4885)
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/__tests__/ChatView.spec.tsx
Labels: bug, size:M, lgtm, PR - Needs Review

#5237 Fix: Chat UI consistency and layout shifts
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/history/TaskItem.tsx
Labels: size:L, lgtm, UI/UX, PR - Needs Review

#5317 feat: Delete .roo/rules-{mode} folder when custom mode is deleted (#5210)
  src/core/webview/__tests__/webviewMessageHandler.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/id/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/modes/DeleteModeDialog.tsx
  webview-ui/src/components/modes/ModesView.tsx
  webview-ui/src/i18n/locales/ca/prompts.json
  webview-ui/src/i18n/locales/de/prompts.json
  webview-ui/src/i18n/locales/en/prompts.json
  webview-ui/src/i18n/locales/es/prompts.json
  webview-ui/src/i18n/locales/fr/prompts.json
  webview-ui/src/i18n/locales/hi/prompts.json
  webview-ui/src/i18n/locales/id/prompts.json
  webview-ui/src/i18n/locales/it/prompts.json
  webview-ui/src/i18n/locales/ja/prompts.json
  webview-ui/src/i18n/locales/ko/prompts.json
  webview-ui/src/i18n/locales/nl/prompts.json
  webview-ui/src/i18n/locales/pl/prompts.json
  webview-ui/src/i18n/locales/pt-BR/prompts.json
  webview-ui/src/i18n/locales/ru/prompts.json
  webview-ui/src/i18n/locales/tr/prompts.json
  webview-ui/src/i18n/locales/vi/prompts.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
Labels: enhancement, size:XL, lgtm, PR - Changes Requested

#5379 feat: add Issue Fixer Orchestrator mode
  .roo/rules-issue-fixer-orchestrator/1_Workflow.xml
  .roo/rules-issue-fixer-orchestrator/2_best_practices.xml
  .roomodes
Labels: enhancement, size:L, lgtm, PR - Needs Review

#5382 fix: enhance PR reviewer mode to prevent duplicate comments
  .roo/rules-pr-reviewer/1_workflow.xml
  .roo/rules-pr-reviewer/2_best_practices.xml
  .roo/rules-pr-reviewer/3_common_mistakes_to_avoid.xml
Labels: Issue/PR - Triage

#5158 Fix code index secret persistence and improve settings UX
  src/core/config/ContextProxy.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/services/code-index/__tests__/config-manager.spec.ts
  src/services/code-index/__tests__/manager.spec.ts
  src/services/code-index/config-manager.ts
  src/services/code-index/manager.ts
  src/services/code-index/service-factory.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/CodeIndexPopover.tsx
  webview-ui/src/components/chat/IndexingStatusBadge.tsx
  webview-ui/src/components/chat/__tests__/IndexingStatusBadge.spec.tsx
  webview-ui/src/components/settings/CodeIndexSettings.tsx
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/__tests__/CodeIndexSettings.spec.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: bug, size:XXL, lgtm, UI/UX, PR - Needs Review

#5349 fix: prevent chatbox focus loss during automated file editing (#4574)
  src/core/tools/applyDiffTool.ts
  src/core/tools/multiApplyDiffTool.ts
  src/integrations/editor/DiffViewProvider.ts
  src/integrations/editor/__tests__/DiffViewProvider.spec.ts
Labels: bug, size:S, lgtm, UI/UX, PR - Needs Preliminary Review

#5388 Fix inconsistent descriptions in slash commands
  webview-ui/src/utils/__tests__/context-mentions.spec.ts
  webview-ui/src/utils/context-mentions.ts
Labels: size:S, lgtm, Issue/PR - Triage

#5378 feat: add markdown support to codebase indexing (#4660)
  src/services/code-index/processors/__tests__/parser.spec.ts
  src/services/code-index/processors/__tests__/scanner.spec.ts
  src/services/code-index/processors/parser.ts
  src/services/code-index/processors/scanner.ts
  src/services/code-index/shared/supported-extensions.ts
  src/services/tree-sitter/__tests__/markdownIntegration.spec.ts
Labels: enhancement, size:XXL, lgtm, PR - Needs Preliminary Review

#5377 fix: resolve Go duplicate references in tree-sitter queries (#5367)
  src/services/code-index/constants/index.ts
  src/services/code-index/processors/__tests__/parser.spec.ts
  src/services/code-index/processors/parser.ts
  src/services/tree-sitter/__tests__/inspectGo.spec.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.go.spec.ts
  src/services/tree-sitter/queries/go.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5406 PR-Reviewer improvements
  .roo/rules-pr-reviewer/1_orchestrator_workflow.xml
  .roo/rules-pr-reviewer/1_workflow.xml
  .roo/rules-pr-reviewer/2_best_practices.xml
  .roo/rules-pr-reviewer/2_critical_review_guidelines.xml
  .roo/rules-pr-reviewer/3_common_mistakes_to_avoid.xml
  .roo/rules-pr-reviewer/3_delegation_patterns.xml
  .roo/rules-pr-reviewer/4_github_operations.xml
  .roo/rules-pr-reviewer/5_context_management.xml
  .roomodes
Labels: enhancement, size:XXL, lgtm, Issue/PR - Triage

#5407 Pr fixer improvements
  .roo/rules-pr-fixer-orchestrator/1_Workflow.xml
  .roo/rules-pr-fixer-orchestrator/2_best_practices.xml
  .roo/rules-pr-fixer-orchestrator/3_github_cli_usage.xml
  .roo/rules-pr-fixer-orchestrator/4_requirements_analysis.xml
  .roo/rules-pr-fixer-orchestrator/5_self_contained_workflow.xml
  .roo/rules-pr-fixer-orchestrator/6_pr_template_format.xml
  .roomodes
Labels: enhancement, size:XXL, lgtm, Issue/PR - Triage

#5410 fix: restore search score threshold slider
  packages/types/src/codebase-index.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/CodeIndexPopover.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: bug, size:M, lgtm, UI/UX, Issue/PR - Triage

#5432 Fix new_task tool streaming issue
  src/core/tools/newTaskTool.ts
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#5433 Add description field to create_mode instructions
  src/core/prompts/instructions/create-mode.ts
Labels: documentation, size:XS, lgtm, Issue/PR - Triage

#5435 Cloud: support static cloud settings
  packages/cloud/src/CloudService.ts
  packages/cloud/src/CloudSettingsService.ts
  packages/cloud/src/SettingsService.ts
  packages/cloud/src/StaticSettingsService.ts
  packages/cloud/src/TelemetryClient.ts
  packages/cloud/src/__tests__/CloudService.integration.test.ts
  packages/cloud/src/__tests__/CloudService.test.ts
  packages/cloud/src/__tests__/StaticSettingsService.test.ts
Labels: enhancement, size:XL, lgtm, Issue/PR - Triage

#5404 fix: add embedder validation to prevent misleading status indicators (#4398)
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/embeddings.json
  src/i18n/locales/de/embeddings.json
  src/i18n/locales/en/embeddings.json
  src/i18n/locales/es/embeddings.json
  src/i18n/locales/fr/embeddings.json
  src/i18n/locales/hi/embeddings.json
  src/i18n/locales/id/embeddings.json
  src/i18n/locales/it/embeddings.json
  src/i18n/locales/ja/embeddings.json
  src/i18n/locales/ko/embeddings.json
  src/i18n/locales/nl/embeddings.json
  src/i18n/locales/pl/embeddings.json
  src/i18n/locales/pt-BR/embeddings.json
  src/i18n/locales/ru/embeddings.json
  src/i18n/locales/tr/embeddings.json
  src/i18n/locales/vi/embeddings.json
  src/i18n/locales/zh-CN/embeddings.json
  src/i18n/locales/zh-TW/embeddings.json
  src/services/code-index/__tests__/manager.spec.ts
  src/services/code-index/__tests__/service-factory.spec.ts
  src/services/code-index/embedders/__tests__/gemini.spec.ts
  src/services/code-index/embedders/__tests__/ollama.spec.ts
  src/services/code-index/embedders/__tests__/openai-compatible.spec.ts
  src/services/code-index/embedders/__tests__/openai.spec.ts
  src/services/code-index/embedders/gemini.ts
  src/services/code-index/embedders/ollama.ts
  src/services/code-index/embedders/openai-compatible.ts
  src/services/code-index/embedders/openai.ts
  src/services/code-index/interfaces/embedder.ts
  src/services/code-index/manager.ts
  src/services/code-index/orchestrator.ts
  src/services/code-index/service-factory.ts
  src/services/code-index/shared/validation-helpers.ts
Labels: bug, documentation, size:XXL, lgtm, PR - Needs Review

#5461 Remove warning about writing not being allowed
  src/core/environment/__tests__/getEnvironmentDetails.spec.ts
  src/core/environment/getEnvironmentDetails.ts
Labels: size:S, lgtm, Issue/PR - Triage

#5155 fix typescript compiler watch path inconsistency
  src/package.json
  src/tsconfig.json
Labels: size:XS, lgtm, PR - Needs Preliminary Review

#5473 Add a hint about using todos for complicated tasks
  src/core/environment/reminder.ts
Labels: size:XS

#5472 Make the default architect prompt create a todo list
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/architect-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-disabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-enabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/partial-reads-enabled.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/consistent-system-prompt.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-computer-use-support.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-false.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-true.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-undefined.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-different-viewport-size.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-mcp-hub-provided.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-undefined-mcp-hub.snap
  src/core/prompts/__tests__/get-prompt-component.spec.ts
  src/core/prompts/system.ts
  src/shared/__tests__/modes-empty-prompt-component.spec.ts
  src/shared/__tests__/modes.spec.ts
  src/shared/modes.ts
  src/utils/__tests__/object.spec.ts
  src/utils/object.ts
Labels: size:L, lgtm, PR - Needs Review

#5475 Only show share modal from sharebutton
  webview-ui/src/components/chat/ShareButton.tsx
  webview-ui/src/components/chat/__tests__/TaskActions.spec.tsx
Labels: bug, size:M, lgtm, Issue/PR - Triage

#5476 Remove unnecessary useEffect from sharebutton
  webview-ui/src/components/chat/ShareButton.tsx
Labels: size:XS, lgtm, Issue/PR - Triage

#5477 fix: improve chat UI - add camera icon margin and make placeholder no…
  webview-ui/src/components/chat/ChatTextArea.tsx
Labels: size:XS, lgtm, UI/UX

#5482 Fix auto-approve todo settings
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
Labels: size:XS, lgtm

#5484 Bump types to 1.31.0
  packages/types/npm/package.json
Labels: size:XS, Issue/PR - Triage

#5487 update internal orchestrator modes definitions to remove tool access
  .roomodes
Labels: size:S, lgtm, PR - Draft / In Progress

#5489 fix: remove flaky SearchableSelect clear button test
  webview-ui/src/__tests__/SearchableSelect.spec.tsx
Labels: size:M, lgtm

#5481 Move codebase indexing out of experimental
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/services/code-index/__tests__/config-manager.spec.ts
  src/services/code-index/__tests__/manager.spec.ts
  src/services/code-index/config-manager.ts
  src/services/code-index/interfaces/config.ts
  webview-ui/src/components/chat/CodeIndexPopover.tsx
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: size:L, lgtm, Issue/PR - Triage

#5486 fix: strengthen codebase_search enforcement throughout conversations
  src/core/prompts/sections/__tests__/objective.spec.ts
  src/core/prompts/sections/__tests__/tool-use-guidelines.spec.ts
  src/core/prompts/sections/objective.ts
  src/core/prompts/sections/rules.ts
  src/core/prompts/sections/tool-use-guidelines.ts
Labels: size:S, lgtm, PR - Needs Review

#5497 feat: prepare v3.23.0 release
  .changeset/v3.23.0.md
  README.md
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/id/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/nl/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/ru/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/README.md
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: documentation, size:XXL

#5499 Remove changeset that is preventing release
  .changeset/stale-rivers-travel.md
Labels: size:XS

#5510 Remove feature3 from announcement
  .changeset/young-dancers-sell.md
  webview-ui/src/components/chat/Announcement.tsx
Labels: size:XS

#5523 Tweak alignment of indexing dot
  webview-ui/src/components/chat/IndexingStatusBadge.tsx
Labels: size:XS, UI/UX

#5526 fix: handle null/empty custom modes files to prevent 'Cannot read properties of null' error
  src/core/config/CustomModesManager.ts
  src/services/marketplace/SimpleInstaller.ts
  src/services/marketplace/__tests__/SimpleInstaller.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5527 Fix nightly build again
  src/package.json
Labels: bug, size:M

#5528 feat: Replace title attributes with StandardTooltip in ChatTextArea
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, lgtm, UI/UX, PR - Needs Review

#5529 v3.23.4
  .changeset/neat-ends-stick.md
Labels: size:XS

#5504 fix: use decodeURIComponent in openFile
  src/integrations/misc/__tests__/open-file.spec.ts
  src/integrations/misc/open-file.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5534 Make account tab visible
  src/package.json
Labels: size:S, Issue/PR - Triage

#5536 chore: add changeset for v3.23.5 patch release
  .changeset/v3.23.5.md
Labels: size:XS

#5540 fix
  src/activate/registerCommands.ts
Labels: bug, size:S, lgtm

#5559 Grok 4
  .changeset/red-symbols-grab.md
  packages/types/src/providers/xai.ts
Labels: size:M

#5557 Expand Vertex AI region config to include all available regions in GCP Vertex AI
  packages/types/src/providers/vertex.ts
  webview-ui/src/components/settings/providers/__tests__/Vertex.spec.tsx
Labels: enhancement, size:M, lgtm, PR - Needs Preliminary Review

#5563 Run nightly build on push
  .github/workflows/nightly-publish.yml
Labels: size:XS, lgtm

#5569 chore: fix typos in comment & document
  CHANGELOG.md
  apps/vscode-e2e/src/suite/tools/apply-diff.test.ts
  apps/web-roo-code/src/app/evals/evals.tsx
  packages/evals/README.md
  src/core/tools/readFileTool.ts
  webview-ui/src/utils/vscode.ts
Labels: documentation, size:S, lgtm, Issue/PR - Triage

#5574 fix(i18n): Correct translation fallback logic for embedding errors
  src/i18n/locales/ca/embeddings.json
  src/i18n/locales/de/embeddings.json
  src/i18n/locales/en/embeddings.json
  src/i18n/locales/es/embeddings.json
  src/i18n/locales/fr/embeddings.json
  src/i18n/locales/hi/embeddings.json
  src/i18n/locales/id/embeddings.json
  src/i18n/locales/it/embeddings.json
  src/i18n/locales/ja/embeddings.json
  src/i18n/locales/ko/embeddings.json
  src/i18n/locales/nl/embeddings.json
  src/i18n/locales/pl/embeddings.json
  src/i18n/locales/pt-BR/embeddings.json
  src/i18n/locales/ru/embeddings.json
  src/i18n/locales/tr/embeddings.json
  src/i18n/locales/vi/embeddings.json
  src/i18n/locales/zh-CN/embeddings.json
  src/i18n/locales/zh-TW/embeddings.json
  src/services/code-index/embedders/__tests__/gemini.spec.ts
  src/services/code-index/embedders/__tests__/openai-compatible.spec.ts
  src/services/code-index/embedders/gemini.ts
  src/services/code-index/embedders/openai-compatible.ts
  src/services/code-index/manager.ts
  src/services/code-index/shared/validation-helpers.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5586 Update ChatTextArea.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
Labels: bug, size:M, lgtm, PR - Needs Preliminary Review

#5590 Add Devstral Medium
  packages/types/src/providers/mistral.ts
Labels: size:XS, Issue/PR - Triage

#5610 feat(claude-code): add configurable max output tokens setting
  packages/types/src/provider-settings.ts
  packages/types/src/providers/claude-code.ts
  src/api/providers/__tests__/claude-code.spec.ts
  src/api/providers/claude-code.ts
  src/integrations/claude-code/run.ts
  src/shared/__tests__/api.spec.ts
  src/shared/api.ts
  webview-ui/src/components/settings/providers/ClaudeCode.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm, UI/UX, PR - Needs Review

#5595 feat: add comprehensive error telemetry to code-index service
  packages/types/src/telemetry.ts
  src/services/code-index/__tests__/cache-manager.spec.ts
  src/services/code-index/__tests__/manager.spec.ts
  src/services/code-index/__tests__/service-factory.spec.ts
  src/services/code-index/cache-manager.ts
  src/services/code-index/embedders/__tests__/gemini.spec.ts
  src/services/code-index/embedders/__tests__/ollama.spec.ts
  src/services/code-index/embedders/__tests__/openai-compatible.spec.ts
  src/services/code-index/embedders/__tests__/openai.spec.ts
  src/services/code-index/embedders/gemini.ts
  src/services/code-index/embedders/ollama.ts
  src/services/code-index/embedders/openai-compatible.ts
  src/services/code-index/embedders/openai.ts
  src/services/code-index/manager.ts
  src/services/code-index/orchestrator.ts
  src/services/code-index/processors/__tests__/file-watcher.spec.ts
  src/services/code-index/processors/__tests__/parser.spec.ts
  src/services/code-index/processors/__tests__/scanner.spec.ts
  src/services/code-index/processors/file-watcher.ts
  src/services/code-index/processors/parser.ts
  src/services/code-index/processors/scanner.ts
  src/services/code-index/search-service.ts
  src/services/code-index/service-factory.ts
  src/services/code-index/shared/__tests__/validation-helpers.spec.ts
  src/services/code-index/shared/validation-helpers.ts
Labels: enhancement, size:XL, lgtm, PR - Needs Review

#5627 test: disable flaky MCP directory_tree test
  apps/vscode-e2e/src/suite/tools/use-mcp-tool.test.ts
Labels: size:XS, lgtm, PR - Needs Review

#5614 Add a command denylist
  packages/types/src/global-settings.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/package.json
  src/package.nls.ca.json
  src/package.nls.de.json
  src/package.nls.es.json
  src/package.nls.fr.json
  src/package.nls.hi.json
  src/package.nls.id.json
  src/package.nls.it.json
  src/package.nls.ja.json
  src/package.nls.json
  src/package.nls.ko.json
  src/package.nls.nl.json
  src/package.nls.pl.json
  src/package.nls.pt-BR.json
  src/package.nls.ru.json
  src/package.nls.tr.json
  src/package.nls.vi.json
  src/package.nls.zh-CN.json
  src/package.nls.zh-TW.json
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/utils/__tests__/command-validation.spec.ts
  webview-ui/src/utils/command-validation.ts
Labels: size:L, lgtm, PR - Needs Review

#5599 feat: add enable/disable toggle for code indexing
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/services/code-index/__tests__/config-manager.spec.ts
  src/services/code-index/config-manager.ts
  src/services/code-index/manager.ts
  webview-ui/src/components/chat/CodeIndexPopover.tsx
  webview-ui/src/components/chat/__tests__/CodeIndexPopover.validation.spec.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm, UI/UX, PR - Needs Review

#5638 Remove duplicate PR link in issue fixer workflow
  .roo/rules-issue-fixer-orchestrator/5_pull_request_workflow.xml
  .roo/rules-issue-fixer/1_Workflow.xml
  .roo/rules-issue-fixer/5_pull_request_workflow.xml
Labels: size:XS, lgtm, Issue/PR - Triage

#5643 More tweaks to chatview layout
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/__tests__/HistoryPreview.spec.tsx
Labels: size:M, UI/UX, Issue/PR - Triage

#5669 chore: add changeset for v3.23.8 patch release
  .changeset/v3.23.8.md
Labels: size:XS

#5667 fix: [5424] return the cwd in the exec tool's response so that the model is not lost after subsequent calls
  src/core/tools/__tests__/executeCommand.spec.ts
  src/core/tools/executeCommandTool.ts
Labels: bug, size:L, lgtm, Issue/PR - Triage

#5698 feat: add gemini-embedding-001 model to code-index service
  src/services/code-index/__tests__/service-factory.spec.ts
  src/services/code-index/embedders/__tests__/gemini.spec.ts
  src/services/code-index/embedders/gemini.ts
  src/services/code-index/service-factory.ts
  src/shared/embeddingModels.ts
Labels: enhancement, size:L, PR - Needs Review

#5700 Tweaks to command timeout error
  src/core/tools/executeCommandTool.ts
Labels: size:XS

#5705 fix: prioritize built-in model dimensions over custom dimensions
  src/services/code-index/__tests__/config-manager.spec.ts
  src/services/code-index/__tests__/service-factory.spec.ts
  src/services/code-index/config-manager.ts
  src/services/code-index/service-factory.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5707 chore: add changeset for v3.23.10 patch release
  .changeset/v3.23.10.md
Labels: size:XS

#5676 Fix: Remove invalid skip-checkout parameter from GitHub Actions workflows
  .github/workflows/changeset-release.yml
  .github/workflows/marketplace-publish.yml
  .github/workflows/nightly-publish.yml
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#5717 Add Kimi K2 model and better support
  packages/types/src/providers/groq.ts
  src/core/task/Task.ts
  src/shared/api.ts
Labels: enhancement, size:M, lgtm, Issue/PR - Triage

#5734 Add changeset for v3.23.12 patch release
  .changeset/v3.23.12.md
Labels: size:XS

#5303 list-files must include at least the first-level directory contents
  src/services/glob/__tests__/list-files.spec.ts
  src/services/glob/list-files.ts
Labels: enhancement, size:L, lgtm, PR - Needs Review

#5750 fix: Exclude Terraform and Terragrunt cache directories from checkpoints (#4601)
  src/services/checkpoints/excludes.ts
Labels: bug, size:XS, lgtm, PR - Needs Preliminary Review

#5785 fix: resolve DirectoryScanner memory leak and improve file limit handling
  src/services/code-index/constants/index.ts
  src/services/code-index/interfaces/file-processor.ts
  src/services/code-index/processors/__tests__/scanner.spec.ts
  src/services/code-index/processors/scanner.ts
Labels: bug, size:M, PR - Needs Review

#5602 fix: Resolve confusing auto-approve checkbox states
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/__tests__/AutoApproveMenu.spec.tsx
  webview-ui/src/components/chat/__tests__/ChatView.auto-approve-new.spec.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/hooks/__tests__/useAutoApprovalState.spec.ts
  webview-ui/src/hooks/useAutoApprovalState.ts
  webview-ui/src/hooks/useAutoApprovalToggles.ts
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: bug, size:XXL, lgtm, UI/UX, PR - Needs Review

#5818 feat: Update Ollama UI to use text inputs
  webview-ui/src/components/chat/CodeIndexPopover.tsx
Labels: size:M, UI/UX, PR - Needs Review

#5833 Log API-initiated tasks to a tmp directory
  .changeset/late-rockets-talk.md
  src/extension/api.ts
Labels: size:XS, lgtm, Issue/PR - Triage

#5862 feat: Add description and whenToUse fields to custom modes in .roomodes
  .roomodes
Labels: documentation, size:S

#5716 Prevent completion with open todos
  packages/types/npm/package.json
  packages/types/src/global-settings.ts
  src/core/tools/__tests__/attemptCompletionTool.spec.ts
  src/core/tools/attemptCompletionTool.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/id/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
  src/package.json
  src/package.nls.json
Labels: enhancement, size:XL, lgtm, PR - Needs Review

#5913 feat: Add Issue Investigator mode and enhance Issue Writer mode
  .roo/rules-issue-investigator/1_workflow.xml
  .roo/rules-issue-investigator/2_best_practices.xml
  .roo/rules-issue-investigator/3_common_patterns.xml
  .roo/rules-issue-investigator/4_tool_usage.xml
  .roo/rules-issue-investigator/5_examples.xml
  .roo/rules-issue-investigator/6_communication.xml
  .roo/rules-issue-writer/1_workflow.xml
  .roo/rules-issue-writer/6_technical_analysis_workflow.xml
  .roomodes
Labels: documentation, enhancement, size:XXL

#5929 Added YouTube to website footer
  apps/web-roo-code/src/components/chromes/footer.tsx
  apps/web-roo-code/src/lib/constants.ts
Labels: size:S, lgtm, UI/UX, PR - Needs Preliminary Review

#5854 feat: add global rate limiting for OpenAI-compatible embeddings
  src/services/code-index/embedders/__tests__/openai-compatible-rate-limit.spec.ts
  src/services/code-index/embedders/__tests__/openai-compatible.spec.ts
  src/services/code-index/embedders/openai-compatible.ts
Labels: enhancement, size:L, PR - Needs Review

#5891 feat: add batch limiting to code indexer
  src/services/code-index/constants/index.ts
  src/services/code-index/processors/scanner.ts
Labels: enhancement, size:S, PR - Needs Review

#5952 Release v3.23.16
  .changeset/v3.23.16.md
  .roomodes
Labels: changelog-ready, size:M

#5991 fix: add run parameter to vitest command in rules
  .roo/rules/rules.md
Labels: documentation, size:XS, lgtm, Issue/PR - Triage

#5837 fix: resolve global mode export not including rules files (#5834)
  src/core/config/CustomModesManager.ts
  src/core/config/__tests__/CustomModesManager.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5993 Update the max_tokens fallback logic in the sliding window
  src/core/sliding-window/__tests__/sliding-window.spec.ts
  src/core/sliding-window/index.ts
Labels: size:S, lgtm, PR - Needs Review

#6019 fix: add bedrock to ANTHROPIC_STYLE_PROVIDERS and restore vertex Claude model checking
  packages/types/src/__tests__/provider-settings.test.ts
  packages/types/src/provider-settings.ts
Labels: size:M, PR - Needs Review

#6051 Bugfix: Cloud: be more specific about session error codes
  packages/cloud/src/auth/WebAuthService.ts
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#5926 docs: clarify when to use update_todo_list tool
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/architect-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/ask-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-disabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-enabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/partial-reads-enabled.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/consistent-system-prompt.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-computer-use-support.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-false.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-true.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-undefined.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-different-viewport-size.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-mcp-hub-provided.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-undefined-mcp-hub.snap
  src/core/prompts/tools/update-todo-list.ts
Labels: documentation, size:XS, lgtm, PR - Needs Review

#6023 feat: add llama-4-maverick model to Vertex AI provider (#5808)
  packages/types/src/providers/vertex.ts
Labels: enhancement, size:XS, lgtm, Issue/PR - Triage

#6090 feat: add merge-resolver mode for intelligent conflict resolution
  .roo/rules-merge-resolver/1_workflow.xml
  .roo/rules-merge-resolver/2_best_practices.xml
  .roo/rules-merge-resolver/3_tool_usage.xml
  .roo/rules-merge-resolver/4_complete_example.xml
  .roo/rules-merge-resolver/5_communication.xml
  .roo/rules-pr-fixer/1_workflow.xml
  .roo/rules-pr-fixer/2_best_practices.xml
  .roo/rules-pr-fixer/3_common_patterns.xml
  .roo/rules-pr-fixer/4_tool_usage.xml
  .roo/rules-pr-fixer/5_examples.xml
  .roomodes
Labels: enhancement, size:XXL, lgtm, PR - Needs Review

#6071 Use SIGKILL for command execution timeouts in the "execa" variant
  apps/web-evals/src/actions/runs.ts
  packages/evals/src/cli/runTask.ts
  packages/types/src/global-settings.ts
  src/core/tools/executeCommandTool.ts
  src/integrations/terminal/ExecaTerminalProcess.ts
Labels: size:L, Issue/PR - Triage

#6123 Smarter auto-deny
  webview-ui/src/utils/__tests__/command-validation.spec.ts
  webview-ui/src/utils/command-validation.ts
Labels: size:L, lgtm, PR - Needs Review

#6130 chore: add changeset for v3.23.19
  .changeset/v3.23.19.md
Labels: size:XS

#5582 feat: Add settings to control diagnostic messages (#5524)
  packages/types/src/global-settings.ts
  src/core/mentions/index.ts
  src/core/mentions/processUserContentMentions.ts
  src/core/task/Task.ts
  src/core/tools/__tests__/insertContentTool.spec.ts
  src/core/tools/__tests__/writeToFileTool.spec.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/integrations/diagnostics/__tests__/diagnostics.spec.ts
  src/integrations/diagnostics/index.ts
  src/integrations/editor/DiffViewProvider.ts
  src/integrations/editor/__tests__/DiffViewProvider.spec.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/ContextManagementSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/__tests__/ContextManagementSettings.spec.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: documentation, enhancement, size:XXL, lgtm, UI/UX, PR - Changes Requested

#6134 basic hugging face provider
  packages/types/src/provider-settings.ts
  src/api/huggingface-models.ts
  src/api/index.ts
  src/api/providers/huggingface.ts
  src/api/providers/index.ts
  src/core/webview/webviewMessageHandler.ts
  src/services/huggingface-models.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/settings/providers/HuggingFace.tsx
  webview-ui/src/components/settings/providers/__tests__/HuggingFace.spec.tsx
  webview-ui/src/components/settings/providers/index.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, Issue/PR - Triage

#6040 Fix/website logo theme persistence
  apps/web-roo-code/src/lib/hooks/use-logo-src.ts
Labels: bug, size:S, lgtm, PR - Needs Review

#6184 Expose default modes in @roo-code/types
  packages/types/npm/package.json
  packages/types/src/mode.ts
  src/shared/modes.ts
Labels: size:L, Issue/PR - Triage

#6193 Add type for allowing org members to view all tasks
  packages/types/npm/package.json
  packages/types/src/cloud.ts
Labels: size:XS, lgtm, Issue/PR - Triage

#6055 feat: add efficiency warning for single SEARCH/REPLACE blocks in apply_diff
  src/core/tools/applyDiffTool.ts
  src/core/tools/multiApplyDiffTool.ts
Labels: enhancement, size:S, lgtm, PR - Needs Review

#6224 fix: prevent duplicate command patterns by trimming full command
  webview-ui/src/components/chat/CommandPatternSelector.tsx
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#6227 fix: add error message when no workspace folder is open for code indexing
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/embeddings.json
  src/i18n/locales/de/embeddings.json
  src/i18n/locales/en/embeddings.json
  src/i18n/locales/es/embeddings.json
  src/i18n/locales/fr/embeddings.json
  src/i18n/locales/hi/embeddings.json
  src/i18n/locales/id/embeddings.json
  src/i18n/locales/it/embeddings.json
  src/i18n/locales/ja/embeddings.json
  src/i18n/locales/ko/embeddings.json
  src/i18n/locales/nl/embeddings.json
  src/i18n/locales/pl/embeddings.json
  src/i18n/locales/pt-BR/embeddings.json
  src/i18n/locales/ru/embeddings.json
  src/i18n/locales/tr/embeddings.json
  src/i18n/locales/vi/embeddings.json
  src/i18n/locales/zh-CN/embeddings.json
  src/i18n/locales/zh-TW/embeddings.json
  src/services/code-index/orchestrator.ts
Labels: enhancement, size:M, lgtm, Issue/PR - Triage

#6228 refactor: consolidate HuggingFace models API into providers/fetchers
  src/api/huggingface-models.ts
  src/api/providers/fetchers/huggingface.ts
  src/core/webview/webviewMessageHandler.ts
Labels: size:L, lgtm, Issue/PR - Triage

#6236 Clean up some of the hugging face provider settings
  webview-ui/src/components/settings/providers/HuggingFace.tsx
Labels: size:M, UI/UX

#6237 chore: add changeset for v3.24.0
  .changeset/v3.24.0.md
  README.md
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/id/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/nl/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/ru/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/README.md
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: documentation, changelog-ready, size:S, Issue/PR - Triage

#6238 Kick off release
  .changeset/brown-insects-start.md
Labels: changelog-ready, size:XS

#6253 fix: restore working settings link in command permissions tooltip
  webview-ui/src/components/chat/CommandPatternSelector.tsx
Labels: bug, size:S, lgtm, Issue/PR - Triage

#5176 # fix: list_files recursive mode now works for dot directories
  src/services/glob/__tests__/list-files.spec.ts
  src/services/glob/constants.ts
  src/services/glob/list-files.ts
Labels: bug, size:XL, lgtm, PR - Needs Review

#6266 fix: prevent scrollbar flickering in chat view during content streaming
  webview-ui/src/components/chat/Markdown.tsx
  webview-ui/src/components/common/MarkdownBlock.tsx
Labels: bug, size:L, lgtm, Issue/PR - Triage

#6263 Support for custom slash commands
  src/__tests__/command-integration.spec.ts
  src/__tests__/command-mentions.spec.ts
  src/__tests__/commands.spec.ts
  src/core/mentions/index.ts
  src/core/webview/webviewMessageHandler.ts
  src/services/command/commands.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/context-mentions.ts
  webview-ui/src/__tests__/command-autocomplete.spec.ts
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ContextMenu.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/utils/__tests__/context-mentions.spec.ts
  webview-ui/src/utils/context-mentions.ts
Labels: enhancement, size:XXL, PR - Needs Preliminary Review

#6140 feat: Add search functionality to mode selector popup and reorganize layout
  webview-ui/src/components/chat/ModeSelector.tsx
  webview-ui/src/components/chat/__tests__/ModeSelector.spec.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, lgtm, UI/UX, PR - Needs Review

#6148 feat: sync API config selector style with mode selector from PR #6140
  webview-ui/src/components/chat/ApiConfigSelector.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/__tests__/ApiConfigSelector.spec.tsx
  webview-ui/src/i18n/locales/ca/common.json
  webview-ui/src/i18n/locales/de/common.json
  webview-ui/src/i18n/locales/en/common.json
  webview-ui/src/i18n/locales/es/common.json
  webview-ui/src/i18n/locales/fr/common.json
  webview-ui/src/i18n/locales/hi/common.json
  webview-ui/src/i18n/locales/id/common.json
  webview-ui/src/i18n/locales/it/common.json
  webview-ui/src/i18n/locales/ja/common.json
  webview-ui/src/i18n/locales/ko/common.json
  webview-ui/src/i18n/locales/nl/common.json
  webview-ui/src/i18n/locales/pl/common.json
  webview-ui/src/i18n/locales/pt-BR/common.json
  webview-ui/src/i18n/locales/ru/common.json
  webview-ui/src/i18n/locales/tr/common.json
  webview-ui/src/i18n/locales/vi/common.json
  webview-ui/src/i18n/locales/zh-CN/common.json
  webview-ui/src/i18n/locales/zh-TW/common.json
Labels: size:XL, lgtm, UI/UX, PR - Needs Review

#6230 Update issue writer rules and workflow configurations
  .roo/rules-issue-writer/1_workflow.xml
  .roo/rules-issue-writer/2_github_issue_templates.xml
  .roo/rules-issue-writer/3_best_practices.xml
  .roo/rules-issue-writer/4_common_mistakes_to_avoid.xml
  .roo/rules-issue-writer/5_github_cli_usage.xml
  .roo/rules-issue-writer/6_technical_analysis_workflow.xml
  .roomodes
Labels: documentation, enhancement, size:XXL, lgtm, Issue/PR - Triage

#6303 Revert "fix: optimize README for VS Code marketplace to prevent UI freezing"
  README.vscode.md
  apps/vscode-nightly/esbuild.mjs
  src/esbuild.mjs
Labels: size:L

#6074 feat: add prompt caching support for LiteLLM (#5791)
  packages/types/src/provider-settings.ts
  src/api/providers/__tests__/lite-llm.spec.ts
  src/api/providers/lite-llm.ts
  webview-ui/src/components/settings/providers/LiteLLM.tsx
Labels: enhancement, size:L, lgtm, PR - Needs Review

#6286 Add a UI for managing slash commands
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/id/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/__tests__/command-autocomplete.spec.ts
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ContextMenu.tsx
  webview-ui/src/components/chat/SlashCommandItem.tsx
  webview-ui/src/components/chat/SlashCommandsList.tsx
  webview-ui/src/components/chat/SlashCommandsPopover.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/utils/__tests__/context-mentions.spec.ts
  webview-ui/src/utils/context-mentions.ts
Labels: size:XL, UI/UX, PR - Needs Preliminary Review

#6313 feat(mode-writer): add validation and cohesion checking for mode creation
  .roo/rules-mode-writer/1_mode_creation_workflow.xml
  .roo/rules-mode-writer/5_complete_mode_examples.xml
  .roo/rules-mode-writer/7_validation_cohesion_checking.xml
  .roomodes
Labels: enhancement, size:XL, lgtm

#6314 Add support for slash command frontmatter descriptions
  pnpm-lock.yaml
  src/core/mentions/index.ts
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/id/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
  src/package.json
  src/services/command/__tests__/frontmatter-commands.spec.ts
  src/services/command/commands.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/utils/context-mentions.ts
Labels: enhancement, size:L, Issue/PR - Triage

#6327 Support inserting mentions after a slash command
  webview-ui/src/__tests__/command-autocomplete.spec.ts
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ContextMenu.tsx
  webview-ui/src/utils/__tests__/context-mentions.spec.ts
  webview-ui/src/utils/context-mentions.ts
Labels: enhancement, size:L, Issue/PR - Triage

#6331 Parse mentions from all user inputs
  src/core/mentions/processUserContentMentions.ts
Labels: enhancement, size:XS, Issue/PR - Triage

#6336 Better command highlighting
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/__tests__/ChatTextArea.spec.tsx
Labels: size:L, UI/UX

#6350 fix(environment): Filter out non-text tab inputs
  src/core/environment/getEnvironmentDetails.ts
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#6355 Remove duplicated assignment
  webview-ui/src/components/ErrorBoundary.tsx
Labels: size:XS, lgtm

#6357 feat: make PR reviewer rules generic
  .roo/rules-pr-reviewer/1_workflow.xml
Labels: enhancement, size:XS

#6379 Improvements to subshell validation
  webview-ui/src/components/chat/CommandExecution.tsx
  webview-ui/src/utils/__tests__/command-validation.spec.ts
  webview-ui/src/utils/command-validation.ts
Labels: size:L, lgtm, Issue/PR - Triage

#6378 Cloud: add organization MCP controls
  packages/cloud/src/CloudService.ts
  packages/types/src/cloud.ts
  src/core/webview/ClineProvider.ts
  src/services/marketplace/MarketplaceManager.ts
  src/services/marketplace/RemoteConfigLoader.ts
  src/services/marketplace/__tests__/MarketplaceManager.spec.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/components/marketplace/MarketplaceListView.tsx
  webview-ui/src/components/marketplace/MarketplaceViewStateManager.ts
  webview-ui/src/components/marketplace/__tests__/MarketplaceListView.spec.tsx
  webview-ui/src/i18n/locales/ca/marketplace.json
  webview-ui/src/i18n/locales/de/marketplace.json
  webview-ui/src/i18n/locales/en/marketplace.json
  webview-ui/src/i18n/locales/es/marketplace.json
  webview-ui/src/i18n/locales/fr/marketplace.json
  webview-ui/src/i18n/locales/hi/marketplace.json
  webview-ui/src/i18n/locales/id/marketplace.json
  webview-ui/src/i18n/locales/it/marketplace.json
  webview-ui/src/i18n/locales/ja/marketplace.json
  webview-ui/src/i18n/locales/ko/marketplace.json
  webview-ui/src/i18n/locales/nl/marketplace.json
  webview-ui/src/i18n/locales/pl/marketplace.json
  webview-ui/src/i18n/locales/pt-BR/marketplace.json
  webview-ui/src/i18n/locales/ru/marketplace.json
  webview-ui/src/i18n/locales/tr/marketplace.json
  webview-ui/src/i18n/locales/vi/marketplace.json
  webview-ui/src/i18n/locales/zh-CN/marketplace.json
  webview-ui/src/i18n/locales/zh-TW/marketplace.json
Labels: enhancement, size:L, lgtm, PR - Needs Preliminary Review

#6387 Bump types to 1.40.0
  packages/types/npm/package.json
Labels: size:XS, lgtm, Issue/PR - Triage

#6386 fix: show diff view before approval when PREVENT_FOCUS_DISRUPTION is disabled
  src/core/tools/insertContentTool.ts
  src/core/tools/multiApplyDiffTool.ts
  src/core/tools/searchAndReplaceTool.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#6389 Release v3.25.2
  .changeset/v3.25.2.md
Labels: changelog-ready, size:XS

#6409 Add docs link for slash commands
  webview-ui/src/components/chat/SlashCommandsPopover.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: documentation, size:S

#6414 Allow queueing images
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
Labels: size:XS, UI/UX

#6415 Hide Gemini checkboxes on the welcome view
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/providers/Gemini.tsx
  webview-ui/src/components/settings/providers/__tests__/Gemini.spec.tsx
Labels: size:M, lgtm, UI/UX, Issue/PR - Triage

#6428 Remove event types mention from PR reviewer rules
  .roo/rules-pr-reviewer/1_workflow.xml
  .roo/rules-pr-reviewer/2_best_practices.xml
  .roo/rules-pr-reviewer/3_common_mistakes_to_avoid.xml
Labels: documentation, size:S, lgtm, PR - Needs Review

#6435 chore: add changeset for v3.25.3
  .changeset/v3.25.3.md
Labels: changelog-ready, size:S, Issue/PR - Triage

#6188 feat: add SambaNova provider integration
  .github/ISSUE_TEMPLATE/bug_report.yml
  packages/types/src/global-settings.ts
  packages/types/src/provider-settings.ts
  packages/types/src/providers/index.ts
  packages/types/src/providers/sambanova.ts
  src/api/index.ts
  src/api/providers/__tests__/sambanova.spec.ts
  src/api/providers/index.ts
  src/api/providers/sambanova.ts
  src/shared/ProfileValidator.ts
  src/shared/__tests__/ProfileValidator.spec.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/settings/providers/SambaNova.tsx
  webview-ui/src/components/settings/providers/index.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm, PR - Needs Review

#6449 fix: Use separate changelog for nightly builds to prevent marketplace freezing
  CHANGELOG-NIGHTLY.md
  apps/vscode-nightly/esbuild.mjs
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#6345 Support new LLM provider: Doubao
  packages/types/src/provider-settings.ts
  packages/types/src/providers/doubao.ts
  packages/types/src/providers/index.ts
  src/api/index.ts
  src/api/providers/doubao.ts
  src/api/providers/index.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/settings/providers/Doubao.tsx
  webview-ui/src/components/settings/providers/index.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm, PR - Needs Review

#6424 feat: enhance token counting by extracting text from messages using VSCode LM API
  src/api/providers/vscode-lm.ts
  src/api/transform/__tests__/vscode-lm-format.spec.ts
  src/api/transform/vscode-lm-format.ts
Labels: enhancement, size:L, lgtm, PR - Needs Preliminary Review

#6317 Add pattern to support Databricks /invocations endpoints
  src/services/code-index/embedders/openai-compatible.ts
Labels: enhancement, size:XS, lgtm, PR - Needs Preliminary Review

#6453 Miscellaneous cleanup
  .roo/rules/rules.md
  README.vscode.md
  apps/web-evals/package.json
  apps/web-roo-code/package.json
  packages/cloud/src/CloudService.ts
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/extension/api.ts
  src/package.json
  src/services/marketplace/MarketplaceManager.ts
  src/shared/ProfileValidator.ts
Labels: size:L, Issue/PR - Triage

#6146 Migrate evals database when deploying roo-code-website
  .github/workflows/website-deploy.yml
  packages/evals/package.json
  packages/evals/src/db/migrations/0001_add_timeout_to_runs.sql
Labels: size:S, lgtm, PR - Needs Review

#6457 Fix: Kill button for execute_command tool
  src/integrations/terminal/ExecaTerminalProcess.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#6473 Release v3.25.4
  .changeset/v3.25.4.md
Labels: changelog-ready, size:S, Issue/PR - Triage
