Repository RooCodeInc/Roo-Code, pull requests merged in 2025-09, with the labels that each got.

#7571 Fix claudeCode.notFound translation key
  src/integrations/claude-code/run.ts
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#7579 v3.26.4
  .changeset/v3.26.4.md
  .roo/commands/release.md
  CHANGELOG.md
  releases/3.26.4-release.png
Labels: changelog-ready, size:S

#7602 fix: add cache reporting support for OpenAI-Native provider
  src/api/providers/__tests__/openai-native-usage.spec.ts
  src/api/providers/openai-native.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#7606 feat: add auto-approve support for MCP access_resource tool
  packages/types/src/mcp.ts
  webview-ui/src/components/chat/ChatView.tsx
Labels: enhancement, size:M, lgtm, PR - Needs Review

#7616 Never give up in socket transport
  packages/cloud/src/bridge/SocketTransport.ts
Labels: size:S, lgtm

#7618 Fix socket-io client event handling
  packages/cloud/src/bridge/SocketTransport.ts
Labels: bug, size:L

#7619 More socket-io client fixes from PR feedback
  packages/cloud/src/bridge/SocketTransport.ts
Labels: size:XS

#7620 More socket-io client logging improvements
  packages/cloud/src/bridge/SocketTransport.ts
Labels: enhancement, size:M

#7578 Update chutes.ts to add Qwen3 235B A22B Thinking 2507 model
  packages/types/src/providers/chutes.ts
Labels: documentation, enhancement, size:S, lgtm, PR - Needs Review

#7628 chore: add changeset for v3.26.5
  .changeset/v3.26.5.md
  releases/3.26.5-release.png
Labels: changelog-ready, size:S

#7636 Release: v1.73.0
  packages/types/npm/package.metadata.json
Labels: size:XS

#7638 Cloud: remove extension_bridge_enabled for personal users
  packages/cloud/src/WebAuthService.ts
  packages/cloud/src/__tests__/WebAuthService.spec.ts
Labels: size:S, lgtm, Issue/PR - Triage

#7587 fix: preserve scroll position when switching tabs in settings
  webview-ui/src/components/common/Tab.tsx
  webview-ui/src/components/settings/SettingsView.tsx
Labels: bug, size:S, lgtm, PR - Needs Preliminary Review

#7593 feat: add Kimi K2 Turbo model configuration to moonshotModels
  packages/types/src/providers/moonshot.ts
Labels: enhancement, size:S, lgtm, PR - Needs Preliminary Review

#7650 Release v3.26.6
  .changeset/v3.26.6.md
  releases/3.26.6-release.png
Labels: documentation, size:S, Issue/PR - Triage

#7686 fix: prevent countdown timer from showing in history for answered follow-up questions
  packages/types/src/message.ts
  src/core/task/Task.ts
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:S, lgtm, PR - Needs Review

#7673 fix: Fix the issue of Moonshot's maximum return token count being limited to 1024
  src/api/providers/__tests__/moonshot.spec.ts
  src/api/providers/moonshot.ts
  src/api/providers/openai.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#7681 Use an allowlist to keep the prompt default shell sane
  src/utils/__tests__/shell.spec.ts
  src/utils/shell.ts
Labels: enhancement, size:L, lgtm, PR - Draft / In Progress

#7682 Fix: Improve WelcomeView styling and readability
  webview-ui/src/components/welcome/WelcomeView.tsx
Labels: size:S, lgtm, UI/UX, PR - Needs Review

#7447 Edit/Delete User Message
  src/core/checkpoints/__tests__/checkpoint.test.ts
  src/core/checkpoints/index.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/__tests__/checkpointRestoreHandler.spec.ts
  src/core/webview/__tests__/webviewMessageHandler.checkpoint.spec.ts
  src/core/webview/__tests__/webviewMessageHandler.spec.ts
  src/core/webview/checkpointRestoreHandler.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/App.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/CheckpointRestoreDialog.tsx
  webview-ui/src/components/chat/__tests__/CheckpointRestoreDialog.spec.tsx
  webview-ui/src/i18n/locales/ca/common.json
  webview-ui/src/i18n/locales/de/common.json
  webview-ui/src/i18n/locales/en/common.json
  webview-ui/src/i18n/locales/es/common.json
  webview-ui/src/i18n/locales/fr/common.json
  webview-ui/src/i18n/locales/hi/common.json
  webview-ui/src/i18n/locales/id/common.json
  webview-ui/src/i18n/locales/it/common.json
  webview-ui/src/i18n/locales/ja/common.json
  webview-ui/src/i18n/locales/ko/common.json
  webview-ui/src/i18n/locales/nl/common.json
  webview-ui/src/i18n/locales/pl/common.json
  webview-ui/src/i18n/locales/pt-BR/common.json
  webview-ui/src/i18n/locales/ru/common.json
  webview-ui/src/i18n/locales/tr/common.json
  webview-ui/src/i18n/locales/vi/common.json
  webview-ui/src/i18n/locales/zh-CN/common.json
  webview-ui/src/i18n/locales/zh-TW/common.json
Labels: documentation, size:XXL, lgtm, PR - Needs Review

#6904 fix: identify mcp and slash command config path in multiple folder workspace
  src/activate/registerCommands.ts
  src/core/mentions/index.ts
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/integrations/workspace/WorkspaceTracker.ts
  src/services/code-index/manager.ts
  src/services/code-index/vector-store/qdrant-client.ts
  src/services/mcp/McpHub.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#7583 fix: resolve CI e2e test ETIMEDOUT errors when downloading VS Code
  .github/workflows/code-qa.yml
  apps/vscode-e2e/src/runTest.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#7434 fix: Tackling Race/State condition issue by Changing the Code Design for Gemini Grounding Sources
  src/api/providers/__tests__/gemini-handler.spec.ts
  src/api/providers/gemini.ts
  src/api/transform/stream.ts
  src/core/task/Task.ts
  src/core/task/__tests__/grounding-sources.test.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#7714 fix: preserve context by retrying with full conversation on invalid previous_response_id
  src/api/providers/__tests__/openai-native.spec.ts
  src/api/providers/openai-native.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#7715 chore: add changeset for v3.26.8
  .changeset/v3.26.8.md
  releases/3.26.8-release.png
Labels: changelog-ready, size:S

#7719 Bump to 3.27.0
  .changeset/v3.27.0.md
  releases/3.27.0-release.png
Labels: size:XS

#7749 Add model info to eval runs table
  apps/web-roo-code/src/app/evals/evals.tsx
  apps/web-roo-code/src/app/evals/plot.tsx
  apps/web-roo-code/src/app/evals/types.ts
  apps/web-roo-code/src/lib/format-currency.ts
  apps/web-roo-code/src/lib/hooks/use-open-router-models.ts
  packages/evals/package.json
  packages/evals/src/db/migrations/0002_bouncy_blazing_skull.sql
  packages/evals/src/db/migrations/meta/0002_snapshot.json
  packages/evals/src/db/migrations/meta/_journal.json
  packages/evals/src/db/schema.ts
Labels: enhancement, size:XL, lgtm, Issue/PR - Triage

#7594 Revert PR #7188 - Restore temperature parameter to fix TabbyApi/ExLlamaV2 crashes
  src/api/providers/__tests__/chutes.spec.ts
  src/api/providers/__tests__/fireworks.spec.ts
  src/api/providers/__tests__/groq.spec.ts
  src/api/providers/__tests__/openai.spec.ts
  src/api/providers/__tests__/roo.spec.ts
  src/api/providers/__tests__/sambanova.spec.ts
  src/api/providers/__tests__/zai.spec.ts
  src/api/providers/base-openai-compatible-provider.ts
  src/api/providers/openai.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#7679 Make ollama models info transport work like lmstudio
  src/core/webview/__tests__/webviewMessageHandler.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/components/settings/providers/Ollama.tsx
  webview-ui/src/components/ui/hooks/useOllamaModels.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
Labels: size:L, lgtm, UI/UX, PR - Needs Review

#7793 fix: resolve chat message edit/delete duplication issues
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/__tests__/webviewMessageHandler.delete.spec.ts
  src/core/webview/__tests__/webviewMessageHandler.edit.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/id/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
Labels: bug, size:XL, lgtm, PR - Needs Review

#7819 fix: add GIT_EDITOR env var to merge-resolver mode for non-interactive rebase
  .roo/rules-merge-resolver/1_workflow.xml
  .roo/rules-merge-resolver/3_tool_usage.xml
  .roo/rules-merge-resolver/4_complete_example.xml
Labels: bug, documentation, size:M, lgtm, PR - Needs Review

#7839 Fix Groq context window display
  src/api/providers/__tests__/groq.spec.ts
  src/api/providers/groq.ts
Labels: bug, size:S, lgtm, PR - Needs Review

#7850 feat: In-extension dismissible upsells for Roo Code Cloud
  packages/types/src/global-settings.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/ShareButton.tsx
  webview-ui/src/components/chat/TaskHeader.tsx
  webview-ui/src/components/chat/__tests__/ChatView.spec.tsx
  webview-ui/src/components/chat/__tests__/TaskActions.spec.tsx
  webview-ui/src/components/chat/__tests__/TaskHeader.spec.tsx
  webview-ui/src/components/cloud/CloudUpsellDialog.tsx
  webview-ui/src/components/cloud/CloudView.tsx
  webview-ui/src/components/cloud/__tests__/CloudUpsellDialog.spec.tsx
  webview-ui/src/components/common/DismissibleUpsell.tsx
  webview-ui/src/components/common/__tests__/DismissibleUpsell.spec.tsx
  webview-ui/src/components/welcome/RooCloudCTA.tsx
  webview-ui/src/hooks/useCloudUpsell.ts
  webview-ui/src/i18n/locales/ca/cloud.json
  webview-ui/src/i18n/locales/de/cloud.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/cloud.json
  webview-ui/src/i18n/locales/es/cloud.json
  webview-ui/src/i18n/locales/fr/cloud.json
  webview-ui/src/i18n/locales/hi/cloud.json
  webview-ui/src/i18n/locales/id/cloud.json
  webview-ui/src/i18n/locales/it/cloud.json
  webview-ui/src/i18n/locales/ja/cloud.json
  webview-ui/src/i18n/locales/ko/cloud.json
  webview-ui/src/i18n/locales/nl/cloud.json
  webview-ui/src/i18n/locales/pl/cloud.json
  webview-ui/src/i18n/locales/pt-BR/cloud.json
  webview-ui/src/i18n/locales/ru/cloud.json
  webview-ui/src/i18n/locales/tr/cloud.json
  webview-ui/src/i18n/locales/vi/cloud.json
  webview-ui/src/i18n/locales/zh-CN/cloud.json
  webview-ui/src/i18n/locales/zh-TW/cloud.json
Labels: enhancement, size:XXL, lgtm, PR - Needs Review

#7858 v3.28.0
  .changeset/v3.28.0.md
  releases/3.28.0-release.png
Labels: changelog-ready, size:S, lgtm

#7860 Bust cache in generated image preview
  src/core/tools/__tests__/generateImageTool.test.ts
  src/core/tools/generateImageTool.ts
Labels: bug, size:M, lgtm, Issue/PR - Triage

#7948 feat: add Qwen3 Next 80B A3B models to chutes provider
  packages/types/src/providers/chutes.ts
Labels: enhancement, size:S, lgtm, PR - Needs Review

#7987 ux: Makes text area buttons appear only when there's text
  webview-ui/src/components/chat/ChatTextArea.tsx
Labels: size:M, lgtm, UI/UX, Issue/PR - Triage

#7813 fix: corrected C# tree-sitter query
  src/services/tree-sitter/queries/c-sharp.ts
Labels: bug, size:M, lgtm, PR - Needs Preliminary Review

#8003 Add Z.ai coding plan support
  packages/types/src/provider-settings.ts
  packages/types/src/providers/zai.ts
  src/api/providers/__tests__/zai.spec.ts
  src/api/providers/zai.ts
  webview-ui/src/components/settings/providers/ZAi.tsx
Labels: enhancement, size:M, lgtm, Issue/PR - Triage

#8008 fix: handle ByteString conversion errors in OpenAI embedders
  src/services/code-index/embedders/__tests__/openai-compatible.spec.ts
  src/services/code-index/embedders/openai-compatible.ts
  src/services/code-index/embedders/openai.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#8024 feat: Bring back a way to temporarily and globally pause auto-approve without losing your toggle state
  webview-ui/src/components/chat/AutoApproveDropdown.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/hooks/__tests__/useAutoApprovalState.spec.ts
  webview-ui/src/hooks/useAutoApprovalState.ts
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:L, lgtm, Issue/PR - Triage

#8030 Release: v1.76.0
  packages/types/npm/package.metadata.json
Labels: size:XS

#8031 Types 1.77.0
  packages/types/npm/package.metadata.json
Labels: size:XS

#7911 feat(web): update homepage headline and tagline for remote control capabilities
  apps/web-roo-code/src/app/page.tsx
Labels: enhancement, size:S, lgtm, PR - Needs Review

#8032 ux: Responsive Auto-Approve
  webview-ui/src/components/chat/AutoApproveDropdown.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:S, lgtm, UI/UX, Issue/PR - Triage

#8163 Add a list of sub-processors
  apps/web-roo-code/src/app/legal/subprocessors/page.tsx
  apps/web-roo-code/src/components/chromes/footer.tsx
Labels: enhancement, size:L, lgtm

#8175 Supernova
  packages/types/src/providers/roo.ts
  packages/types/src/single-file-read-models.ts
Labels: size:S, lgtm, Issue/PR - Triage

#8182 chore: add changeset for v3.28.4
  .changeset/v3.28.4.md
  releases/3.28.4-release.png
Labels: changelog-ready, size:S, lgtm

#8180 Updating the privacy policy to allow us to send occasional emails
  apps/web-roo-code/src/app/privacy/page.tsx
Labels: size:S, lgtm, PR - Needs Review

#8186 update sambanova models
  packages/types/src/providers/sambanova.ts
Labels: enhancement, size:S, lgtm, PR - Needs Review

#8171 Fix duplicate rehydrate during reasoning; centralize rehydrate and preserve cancel metadata
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/id/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
Labels: bug, size:L, lgtm, PR - Needs Review

#8197 Add an announcement for Supernova
  packages/cloud/src/CloudService.ts
  packages/cloud/src/WebAuthService.ts
  packages/types/src/cloud.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, lgtm, UI/UX, Issue/PR - Triage

#8198 Release v3.28.5
  .changeset/v3.28.5.md
Labels: changelog-ready, size:S

#8224 Bare metal evals fixes
  apps/web-evals/package.json
  packages/evals/README.md
  packages/evals/docker-compose.yml
  packages/evals/scripts/setup.sh
  src/api/providers/__tests__/roo.spec.ts
  src/api/providers/roo.ts
  src/extension.ts
Labels: bug, documentation, size:L, lgtm, Issue/PR - Triage

#8298 fix: include initial ask in condense summarization (#8293)
  src/core/condense/__tests__/index.spec.ts
  src/core/condense/index.ts
Labels: bug, size:M, lgtm, Issue/PR - Triage

#8305 Release v3.28.8
  .changeset/v3.28.8.md
  releases/3.28.8-release.png
Labels: documentation, changelog-ready, size:S

#8315 Correct tool use suggestion to improve model adherence to suggestion
  src/core/tools/multiApplyDiffTool.ts
Labels: size:XS, lgtm, PR - Needs Review

#8317 Show the Roo provider on the welcome screen
  packages/types/src/telemetry.ts
  src/assets/images/roo.png
  webview-ui/src/components/welcome/WelcomeView.tsx
  webview-ui/src/i18n/locales/ca/welcome.json
  webview-ui/src/i18n/locales/de/welcome.json
  webview-ui/src/i18n/locales/en/welcome.json
  webview-ui/src/i18n/locales/es/welcome.json
  webview-ui/src/i18n/locales/fr/welcome.json
  webview-ui/src/i18n/locales/hi/welcome.json
  webview-ui/src/i18n/locales/id/welcome.json
  webview-ui/src/i18n/locales/it/welcome.json
  webview-ui/src/i18n/locales/ja/welcome.json
  webview-ui/src/i18n/locales/ko/welcome.json
  webview-ui/src/i18n/locales/nl/welcome.json
  webview-ui/src/i18n/locales/pl/welcome.json
  webview-ui/src/i18n/locales/pt-BR/welcome.json
  webview-ui/src/i18n/locales/ru/welcome.json
  webview-ui/src/i18n/locales/tr/welcome.json
  webview-ui/src/i18n/locales/vi/welcome.json
  webview-ui/src/i18n/locales/zh-CN/welcome.json
  webview-ui/src/i18n/locales/zh-TW/welcome.json
Labels: size:M, UI/UX, Issue/PR - Triage

#8303 wip: Website Improvements
  apps/web-roo-code/public/Roo-Code-Logo-Horiz-blk.svg
  apps/web-roo-code/public/Roo-Code-Logo-Horiz-white.svg
  apps/web-roo-code/src/app/page.tsx
  apps/web-roo-code/src/app/pricing/page.tsx
  apps/web-roo-code/src/components/chromes/footer.tsx
  apps/web-roo-code/src/components/chromes/nav-bar.tsx
  apps/web-roo-code/src/components/homepage/features-mobile.tsx
  apps/web-roo-code/src/components/homepage/features.tsx
  apps/web-roo-code/src/components/homepage/index.ts
  apps/web-roo-code/src/components/homepage/install-section.tsx
  apps/web-roo-code/src/components/homepage/testimonials-mobile.tsx
  apps/web-roo-code/src/components/homepage/testimonials.tsx
  apps/web-roo-code/src/lib/constants.ts
Labels: size:XXL, lgtm, UI/UX, PR - Draft / In Progress

#8326 web: More website copy tweaks
  apps/web-roo-code/public/logos/amazon.svg
  apps/web-roo-code/public/logos/anthropic.svg
  apps/web-roo-code/public/logos/apple.svg
  apps/web-roo-code/public/logos/bytedance.svg
  apps/web-roo-code/public/logos/carvana.svg
  apps/web-roo-code/public/logos/deepseek.svg
  apps/web-roo-code/public/logos/gemini.svg
  apps/web-roo-code/public/logos/grok.svg
  apps/web-roo-code/public/logos/kimi.svg
  apps/web-roo-code/public/logos/microsoft.svg
  apps/web-roo-code/public/logos/mistral.svg
  apps/web-roo-code/public/logos/netflix.svg
  apps/web-roo-code/public/logos/ollama.svg
  apps/web-roo-code/public/logos/openai.svg
  apps/web-roo-code/public/logos/qwen.svg
  apps/web-roo-code/public/logos/rakuten.svg
  apps/web-roo-code/public/logos/red-hat.svg
  apps/web-roo-code/src/app/page.tsx
  apps/web-roo-code/src/components/homepage/company-logos.tsx
  apps/web-roo-code/src/components/homepage/features.tsx
  apps/web-roo-code/src/components/homepage/install-section.tsx
Labels: size:L, lgtm, Issue/PR - Triage

#8330 Upgrade Supernova
  packages/types/src/providers/roo.ts
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.spec.ts
  src/core/webview/ClineProvider.ts
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, PR - Draft / In Progress

#8339 Track when telemetry settings change
  packages/telemetry/src/TelemetryService.ts
  packages/types/src/telemetry.ts
  src/core/webview/__tests__/telemetrySettingsTracking.spec.ts
  src/core/webview/webviewMessageHandler.ts
Labels: enhancement, size:L, Issue/PR - Triage

#8343 Make chat icons shrink-0
  webview-ui/src/components/chat/ChatRow.tsx
Labels: size:S, lgtm, UI/UX, Issue/PR - Triage

#8083 ci: refresh contrib.rocks cache workflow
  .github/workflows/update-contributors.yml
Labels: size:M, lgtm, PR - Needs Review

#8373 fix: correct Claude Sonnet 4.5 model ID format
  packages/types/src/providers/openrouter.ts
  src/api/providers/fetchers/__tests__/openrouter.spec.ts
Labels: PR - Needs Review

#8388 fix: remove topP parameter from Bedrock inference config
  src/api/providers/__tests__/bedrock-reasoning.spec.ts
  src/api/providers/bedrock.ts
Labels: bug, size:S, lgtm, PR - Needs Review

#8413 chore: add changeset for v3.28.14
  .changeset/v3.28.14.md
  releases/3.28.14-release.png
Labels: size:XS
