Repository RooCodeInc/Roo-Code, pull requests merged in 2025-02, with the labels that each got.

#701 Changeset version bump
  .changeset/poor-vans-prove.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#705 Changeset version bump
  .changeset/kind-balloons-grin.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#715 Changeset version bump
  .changeset/blue-masks-camp.md
  .changeset/breezy-badgers-refuse.md
  .changeset/nine-tables-cheat.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#783 Changeset version bump
  .changeset/gorgeous-insects-punch.md
  .changeset/heavy-feet-judge.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#797 Changeset version bump
  .changeset/pretty-buckets-double.md
  .changeset/violet-paws-own.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#818 Changeset version bump
  .changeset/late-bees-juggle.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#820 Changeset version bump
  .changeset/yellow-garlics-tap.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#861 Changeset version bump
  .changeset/cyan-insects-marry.md
  .changeset/dirty-coins-exist.md
  .changeset/red-badgers-matter.md
  .changeset/violet-rockets-fetch.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#890 Changeset version bump
  .changeset/spicy-pugs-guess.md
  .changeset/stupid-masks-pay.md
  .changeset/unlucky-rivers-leave.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#911 Changeset version bump
  .changeset/cool-keys-prove.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#913 Changeset version bump
  .changeset/calm-berries-poke.md
  .changeset/fair-boxes-smile.md
  .changeset/funny-bananas-sneeze.md
  .changeset/moody-fans-build.md
  .changeset/polite-lizards-rhyme.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#953 Changeset version bump
  .changeset/clean-bears-hammer.md
  .changeset/orange-geese-provide.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#981 Changeset version bump
  .changeset/clever-news-arrive.md
  .changeset/fast-weeks-sip.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#1048 Changeset version bump
  .changeset/itchy-tomatoes-tie.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#1060 Changeset version bump
  .changeset/healthy-rabbits-poke.md
  .changeset/slimy-timers-float.md
  .changeset/twelve-ways-peel.md
  .changeset/wet-games-pay.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready

#1095 Changeset version bump
  .changeset/witty-dryers-explode.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S, lgtm

#1104 fix: Update AWS Bedrock region options
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: bug, size:XS, lgtm

#1110 v3.3.24
  .changeset/large-geese-sparkle.md
Labels: size:XS

#1111 Changeset version bump
  .changeset/large-geese-sparkle.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1112 Skip flaky tests and suppress logging to get back to clean output
  jest.config.js
  src/__mocks__/jest.setup.ts
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
Labels: size:M, lgtm

#1113 Debugger mode
  .changeset/flat-snails-unite.md
  src/core/Cline.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/__tests__/modes.test.ts
  src/shared/experiments.ts
  src/shared/modes.ts
Labels: size:L

#1114 Changeset version bump
  .changeset/flat-snails-unite.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1116 Tweak the debug prompt
  .changeset/cuddly-crabs-shake.md
  src/shared/__tests__/modes.test.ts
  src/shared/modes.ts
Labels: changelog-ready, size:S

#1117 Changeset version bump
  .changeset/cuddly-crabs-shake.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1125 Improved diff editing use consistency
  CHANGELOG.md
  src/api/transform/o1-format.ts
  src/core/Cline.ts
  src/core/__tests__/mode-validator.test.ts
  src/core/assistant-message/index.ts
  src/core/assistant-message/parse-assistant-message.ts
  src/core/diff/strategies/__tests__/new-unified.test.ts
  src/core/diff/strategies/__tests__/search-replace.test.ts
  src/core/diff/strategies/__tests__/unified.test.ts
  src/core/diff/strategies/new-unified/index.ts
  src/core/diff/strategies/search-replace.ts
  src/core/diff/strategies/unified.ts
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/__tests__/sections.test.ts
  src/core/prompts/__tests__/system.test.ts
  src/core/prompts/sections/capabilities.ts
  src/core/prompts/sections/mcp-servers.ts
  src/core/prompts/sections/modes.ts
  src/core/prompts/sections/rules.ts
  src/core/prompts/tools/index.ts
  src/core/prompts/tools/write-to-file.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/shared/ExtensionMessage.ts
  src/shared/__tests__/modes.test.ts
  src/shared/tool-groups.ts
Labels: documentation, size:L, lgtm

#1126 Add Knip check for unused files
  .github/workflows/code-qa.yml
  knip.json
  package-lock.json
  package.json
  src/api/transform/o1-format.ts
  src/integrations/diagnostics/DiagnosticsMonitor.ts
  src/integrations/terminal/TerminalActions.ts
  src/integrations/workspace/get-python-env.ts
  webview-ui/src/components/common/Demo.tsx
  webview-ui/src/components/settings/TabNavbar.tsx
  webview-ui/src/services/GitService.ts
Labels: enhancement, size:XL, lgtm

#1130 Updating CODEOWNERS to better reflect the current state
  .github/CODEOWNERS
Labels: documentation, size:XS, lgtm

#1128 Try to stabilize tests in CI
  .github/workflows/code-qa.yml
  package-lock.json
  package.json
  src/core/diff/strategies/new-unified/__tests__/edit-strategies.test.ts
  src/services/checkpoints/__tests__/LocalCheckpointService.test.ts
  src/services/checkpoints/__tests__/ShadowCheckpointService.test.ts
  webview-ui/.eslintrc.json
  webview-ui/package-lock.json
  webview-ui/package.json
Labels: size:M, lgtm

#1135 Include the original task in the power steering content
  .changeset/weak-swans-study.md
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/experiments.ts
Labels: size:L, lgtm

#1137 Revert "Include the original task in the power steering content"
  .changeset/weak-swans-study.md
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/experiments.ts
Labels: size:L

#1131 Debug test flakes
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
  src/core/diff/strategies/new-unified/__tests__/edit-strategies.test.ts
Labels: size:L, lgtm

#1100 Improvement/task delete confirmation 854
  webview-ui/src/components/history/DeleteTaskDialog.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/history/__tests__/HistoryView.test.tsx
Labels: bug, enhancement, size:M, lgtm

#1148 Added support for Claude Sonnet 3.7 via VertexAI
  src/shared/api.ts
Labels: enhancement, size:XS, lgtm

#1149 Add Claude 3.7
  src/api/providers/anthropic.ts
  src/api/providers/openrouter.ts
  src/shared/api.ts
Labels: enhancement, size:S, lgtm

#1152 3.7
  .changeset/warm-kangaroos-give.md
Labels: size:XS

#1136 Changeset version bump
  .changeset/warm-kangaroos-give.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1154 Default to Claude 3.7 where appropriate
  .github/ISSUE_TEMPLATE/bug_report.yml
  src/api/providers/__tests__/glama.test.ts
  src/api/providers/__tests__/openrouter.test.ts
  src/api/providers/__tests__/vertex.test.ts
  src/api/providers/openrouter.ts
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/shared/api.ts
  src/test/suite/index.ts
  src/test/suite/modes.test.ts
  src/test/suite/task.test.ts
  webview-ui/src/components/settings/GlamaModelPicker.tsx
  webview-ui/src/components/settings/OpenRouterModelPicker.tsx
  webview-ui/src/components/settings/RequestyModelPicker.tsx
  webview-ui/src/components/settings/SettingsView.tsx
Labels: size:L, lgtm

#1156 Add Claude 3.7 to Bedrock
  src/shared/api.ts
Labels: enhancement, size:S, lgtm

#1157 README updates
  README.md
Labels: documentation, size:L, lgtm

#1158 v3.7.1
  .changeset/large-ladybugs-behave.md
Labels: size:XS

#1160 Changeset version bump
  .changeset/large-ladybugs-behave.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1153 Changes to increase adherence to diff edits
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/__tests__/sections.test.ts
  src/core/prompts/sections/capabilities.ts
  src/core/prompts/sections/modes.ts
  src/core/prompts/sections/rules.ts
  src/shared/tool-groups.ts
Labels: size:M, lgtm

#1162 Sliding window fix
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
  src/core/webview/ClineProvider.ts
Labels: bug, size:L, lgtm

#1164 v3.7.2
  .changeset/fifty-files-jog.md
Labels: size:XS

#1166 Changeset version bump
  .changeset/fifty-files-jog.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1167 Claude 3.7 thinking
  package-lock.json
  package.json
  src/api/providers/__tests__/anthropic.test.ts
  src/api/providers/anthropic.ts
  src/api/providers/bedrock.ts
  src/api/transform/__tests__/bedrock-converse-format.test.ts
  src/api/transform/__tests__/gemini-format.test.ts
  src/api/transform/__tests__/mistral-format.test.ts
  src/api/transform/__tests__/openai-format.test.ts
  src/api/transform/__tests__/vscode-lm-format.test.ts
  src/api/transform/bedrock-converse-format.ts
  src/api/transform/gemini-format.ts
  src/api/transform/mistral-format.ts
  src/api/transform/openai-format.ts
  src/api/transform/simple-format.ts
  src/api/transform/vscode-lm-format.ts
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/integrations/misc/export-markdown.ts
  src/shared/__tests__/checkExistApiConfig.test.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/ui/index.ts
Labels: size:XXL, lgtm

#1175 v3.7.3
  .changeset/real-zebras-remain.md
Labels: size:XS, lgtm

#1176 Changeset version bump
  .changeset/real-zebras-remain.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S, lgtm

#1180 Properly reset thinking setting when changing profiles
  .changeset/little-deers-occur.md
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: bug, size:S, lgtm

#1194 Fix context window truncation math
  src/api/providers/glama.ts
  src/api/providers/openrouter.ts
  src/api/providers/unbound.ts
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
  src/core/webview/ClineProvider.ts
  src/shared/api.ts
Labels: size:L, lgtm

#1190 File drag and drop
  .changeset/shaggy-spies-kneel.md
  src/core/webview/ClineProvider.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/utils/__tests__/path-mentions.test.ts
  webview-ui/src/utils/path-mentions.ts
Labels: enhancement, size:L, lgtm

#1192 Move & clean up model fetchers
  src/api/providers/glama.ts
  src/api/providers/lmstudio.ts
  src/api/providers/ollama.ts
  src/api/providers/openai.ts
  src/api/providers/openrouter.ts
  src/api/providers/requesty.ts
  src/api/providers/unbound.ts
  src/api/providers/vscode-lm.ts
  src/core/Cline.ts
  src/core/config/__tests__/CustomModesManager.test.ts
  src/core/webview/ClineProvider.ts
  src/services/mcp/McpHub.ts
  src/shared/globalFileNames.ts
  src/shared/globalState.ts
  src/utils/__tests__/path.test.ts
  src/utils/cost.ts
  webview-ui/src/components/chat/TaskHeader.tsx
Labels: size:XXL, lgtm

#1199 Update package.json
  package.json
Labels: size:XS

#1200 Thinking settings tweaks
  .changeset/swift-kings-attack.md
  src/api/providers/anthropic.ts
  src/api/providers/openrouter.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:L, lgtm

#1201 Fix: Input/output prices should be parsed using parseFloat
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: bug, size:XS, lgtm

#1122 fix: ModelID cannot be saved and refactor ModelPicker
  webview-ui/src/__mocks__/lucide-react.ts
  webview-ui/src/__mocks__/vscrui.ts
  webview-ui/src/components/settings/ApiErrorMessage.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/GlamaModelPicker.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/OpenAiModelPicker.tsx
  webview-ui/src/components/settings/OpenRouterModelPicker.tsx
  webview-ui/src/components/settings/RequestyModelPicker.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/UnboundModelPicker.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/components/settings/__tests__/ModelPicker.test.tsx
  webview-ui/src/components/ui/combobox-primitive.tsx
  webview-ui/src/components/ui/combobox.tsx
  webview-ui/src/components/ui/input-base.tsx
  webview-ui/src/components/welcome/WelcomeView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/utils/validate.ts
Labels: bug, size:XXL, lgtm

#1198 V3.7.5
  .changeset/cold-poems-change.md
  src/core/sliding-window/index.ts
Labels: size:XS, lgtm

#1202 Fix model picker
  .changeset/real-ties-destroy.md
  src/api/providers/requesty.ts
  src/core/webview/ClineProvider.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/package-lock.json
  webview-ui/src/components/settings/ApiErrorMessage.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/ui/alert-dialog.tsx
  webview-ui/src/components/ui/dialog.tsx
  webview-ui/src/components/welcome/WelcomeView.tsx
  webview-ui/src/utils/validate.ts
Labels: bug, size:XXL, lgtm

#1196 Changeset version bump (v3.7.5)
  .changeset/cold-poems-change.md
  .changeset/real-ties-destroy.md
  .changeset/shaggy-spies-kneel.md
  .changeset/swift-kings-attack.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:M, lgtm

#1216 Fix long strings correctly in ChatRow
  .changeset/fluffy-apples-attack.md
  webview-ui/src/components/chat/ChatRow.tsx
Labels: bug, size:S, lgtm

#1219 Better OpenRouter error handling
  .changeset/tender-cycles-help.md
  src/core/Cline.ts
Labels: enhancement, size:XS, lgtm

#1221 Support multiple files in drag-and-drop
  .changeset/orange-zoos-train.md
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/__tests__/ChatTextArea.test.tsx
Labels: enhancement, size:L, lgtm

#1217 Allow control over maxTokens for thinking models
  .changeset/wild-emus-dream.md
  src/api/providers/anthropic.ts
  src/api/providers/openrouter.ts
  src/core/Cline.ts
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
  src/core/webview/ClineProvider.ts
  src/shared/api.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/ThinkingBudget.tsx
Labels: enhancement, size:L, lgtm

#1224 Truncate results from search_files to 500 chars max
  .changeset/stale-cooks-help.md
  src/services/ripgrep/__tests__/index.test.ts
  src/services/ripgrep/index.ts
Labels: bug, size:M, lgtm

#1218 Changeset version bump
  .changeset/fluffy-apples-attack.md
  .changeset/orange-zoos-train.md
  .changeset/stale-cooks-help.md
  .changeset/tender-cycles-help.md
  .changeset/wild-emus-dream.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M

#1228 Stop removing commas from terminal output
  .changeset/sour-parents-hug.md
  src/integrations/terminal/TerminalProcess.ts
Labels: bug, size:XS, lgtm

#1231 Fix missing tooltips in several components.
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/TaskHeader.tsx
Labels: bug, size:M

#1237 Fix AnthropicHandler#completePrompt
  src/api/providers/__tests__/anthropic.test.ts
  src/api/providers/anthropic.ts
Labels: bug, size:M, lgtm

#1240 Revert "Stop removing commas from terminal output"
  .changeset/sour-parents-hug.md
  src/integrations/terminal/TerminalProcess.ts
Labels: size:XS

#1242 v3.7.7
  .changeset/gorgeous-feet-dress.md
Labels: size:XS

#1230 Changeset version bump
  .changeset/eighty-cheetahs-fetch.md
  .changeset/gorgeous-feet-dress.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#961 Add Vertex AI prompt caching support for Claude models
  src/api/providers/__tests__/vertex.test.ts
  src/api/providers/vertex.ts
  src/shared/api.ts
Labels: size:L, lgtm

#1244 Added cache costs for Claude Sonnet 3.7 via Vertex AI
  src/shared/api.ts
Labels: size:XS, lgtm

#1250 Add gpt-4.5-preview
  .changeset/flat-avocados-carry.md
  src/api/providers/__tests__/openai-native.test.ts
  src/shared/api.ts
Labels: enhancement, size:S, lgtm

#1249 Allow users to set custom system prompts
  src/__mocks__/fs/promises.ts
  src/__mocks__/jest.setup.ts
  src/core/prompts/__tests__/custom-system-prompt.test.ts
  src/core/prompts/sections/custom-system-prompt.ts
  src/core/prompts/system.ts
  webview-ui/src/components/prompts/PromptsView.tsx
Labels: enhancement, size:L, lgtm

#1253 Changeset version bump
  .changeset/flat-avocados-carry.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:S

#1254 Added support for Claude Sonnet 3.7 thinking via Vertex AI
  package-lock.json
  package.json
  src/api/providers/__tests__/vertex.test.ts
  src/api/providers/vertex.ts
  src/core/webview/ClineProvider.ts
  src/shared/api.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/components/settings/__tests__/ThinkingBudget.test.tsx
Labels: enhancement, size:XL, lgtm

#1257 Add provider-agnostic modelMaxThinkingTokens setting
  src/api/providers/__tests__/vertex.test.ts
  src/api/providers/anthropic.ts
  src/api/providers/openrouter.ts
  src/api/providers/vertex.ts
  src/core/webview/ClineProvider.ts
  src/shared/__tests__/checkExistApiConfig.test.ts
  src/shared/api.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/components/settings/__tests__/ThinkingBudget.test.tsx
Labels: size:M, lgtm

#1245 Delete task confirmation enhancements
  .changeset/chilly-bugs-pay.md
  webview-ui/src/components/chat/TaskHeader.tsx
  webview-ui/src/components/history/DeleteTaskDialog.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/history/__tests__/HistoryView.test.tsx
Labels: size:L, lgtm

#1256 Prettier thinking blocks
  .changeset/young-hornets-taste.md
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ReasoningBlock.tsx
  webview-ui/src/index.css
Labels: size:L, lgtm

#1248 Make the copy action on history and history preview consistent
  webview-ui/src/components/history/CopyButton.tsx
  webview-ui/src/components/history/ExportButton.tsx
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/index.css
  webview-ui/src/utils/__tests__/format.test.ts
  webview-ui/src/utils/format.ts
Labels: size:L, lgtm

#1271 Fix: Resolve issue #1146 - UI color in 'light' mode causes dark background on dark text (context menu)
  webview-ui/src/components/chat/ContextMenu.tsx
Labels: bug, size:S, lgtm

#1272 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, size:M, lgtm

#1262 Fix maxTokens defaults for Claude 3.7 Sonnet models
  .changeset/tasty-grapes-suffer.md
  src/api/providers/openrouter.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/components/settings/__tests__/ThinkingBudget.test.tsx
Labels: bug, size:M, lgtm

#1236 Fix TerminalProcess output parsing
  src/core/Cline.ts
  src/integrations/terminal/TerminalManager.ts
  src/integrations/terminal/TerminalProcess.ts
  src/integrations/terminal/TerminalRegistry.ts
  src/integrations/terminal/__tests__/TerminalProcess.test.ts
  src/integrations/terminal/__tests__/TerminalRegistry.test.ts
  src/shared/combineCommandSequences.ts
Labels: bug, size:XL

#1268 Optimize Task ID Initialization Order
  src/core/Cline.ts
Labels: size:XS, lgtm

#1276 Re-enable tests
  src/integrations/terminal/__tests__/TerminalProcess.test.ts
Labels: size:XS, lgtm
