Repository RooCodeInc/Roo-Code, pull requests merged in 2025-06, with the labels that each got.

#4191 Fix the label of the OpenAI-compatible API keys
  webview-ui/src/components/settings/providers/OpenAICompatible.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: size:S

#3654 fix: prevent dump of an entire file into the context on user edit
  src/core/tools/applyDiffTool.ts
  src/core/tools/insertContentTool.ts
  src/core/tools/searchAndReplaceTool.ts
  src/core/tools/writeToFileTool.ts
  src/integrations/editor/DiffViewProvider.ts
Labels: size:L, lgtm, PR - Changes Requested

#4196 Better handling of cloud login/out with multiple workspaces
  packages/cloud/package.json
  packages/cloud/src/AuthService.ts
  pnpm-lock.yaml
Labels: size:L, lgtm

#4212 Upgrade Node.js to v20.19.2 for security enhancements
  .github/workflows/changeset-release.yml
  .github/workflows/code-qa.yml
  .github/workflows/marketplace-publish.yml
  .github/workflows/nightly-publish.yml
  .github/workflows/update-contributors.yml
  .nvmrc
  evals/scripts/setup.sh
Labels: size:S

#4210 feat: Add support for Streamable HTTP Transport MCP servers
  src/__mocks__/@modelcontextprotocol/sdk/client/streamableHttp.js
  src/core/tools/__tests__/writeToFileTool.test.ts
  src/services/mcp/McpHub.ts
Labels: enhancement, size:L, lgtm

#4219 Revert "Revert "fix: prevent dump of an entire file into the context on user edit ""
  src/core/tools/applyDiffTool.ts
  src/core/tools/insertContentTool.ts
  src/core/tools/searchAndReplaceTool.ts
  src/core/tools/writeToFileTool.ts
  src/integrations/editor/DiffViewProvider.ts
Labels: size:L

#4095 chore: fix typos in comment-out
  src/api/providers/__tests__/bedrock-custom-arn.test.ts
  src/api/providers/bedrock.ts
  src/core/assistant-message/parseAssistantMessage.ts
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/utils/shell.ts
Labels: size:S, lgtm, PR - Draft / In Progress

#2220 test: add command line test for multi-search-replace
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
Labels: lgtm, PR - Needs Review

#4220 Fix typo in tool use prompt
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/sections/tool-use.ts
Labels: bug, size:XS

#4221 Run prettier on src/
  src/api/providers/fetchers/litellm.ts
  src/api/providers/lite-llm.ts
  src/core/tools/__tests__/readFileTool.test.ts
  src/integrations/misc/__tests__/read-file-tool.test.ts
  src/shared/__tests__/experiments.test.ts
Labels: size:L

#3690 Fix directory link handling in markdown
  src/integrations/misc/open-file.ts
Labels: bug, enhancement, size:L, lgtm, PR - Needs Review

#4193 releasing memory in apply diff
  src/core/tools/applyDiffTool.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#4151 Unify history item UI with TaskItem and TaskItemHeader
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/history/TaskItem.tsx
  webview-ui/src/components/history/TaskItemFooter.tsx
  webview-ui/src/components/history/TaskItemHeader.tsx
  webview-ui/src/components/history/__tests__/HistoryView.test.tsx
  webview-ui/src/components/history/__tests__/TaskItem.test.tsx
Labels: size:XL, lgtm, UI/UX, PR - Needs Review

#4251 fix: SSE MCP Invocation
  src/services/mcp/McpHub.ts
Labels: bug, size:S, lgtm

#4268 Cloud: bugfixes: log refresh errors and allow logout from inactive-session
  packages/cloud/src/AuthService.ts
  packages/cloud/src/CloudService.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/App.tsx
  webview-ui/src/components/account/AccountView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
Labels: bug, size:M, lgtm

#3799 Improves model info detection for custom Bedrock ARNs
  packages/types/src/provider-settings.ts
  packages/types/src/providers/bedrock.ts
  src/api/providers/bedrock.ts
Labels: size:M, lgtm, PR - Needs Review

#4270 Cloud: add auth logs to the output channel
  packages/cloud/src/AuthService.ts
  packages/cloud/src/CloudService.ts
  packages/cloud/src/__tests__/CloudService.test.ts
  packages/cloud/src/types.ts
  src/extension.ts
  src/utils/__tests__/outputChannelLogger.test.ts
  src/utils/outputChannelLogger.ts
Labels: enhancement, size:L, lgtm

#4288 feat(tools): add support for reading PDF, DOCX, and IPYNB files in read_file tool
  src/core/tools/__tests__/readFileTool.test.ts
  src/core/tools/readFileTool.ts
  src/integrations/misc/extract-text.ts
Labels: enhancement, size:L, lgtm, PR - Needs Review

#4291 Update RCC types
  packages/types/npm/package.json
  packages/types/src/cloud.ts
Labels: size:M, lgtm

#4302 Add vercel deploy workflows
  .github/workflows/website-deploy.yml
  .github/workflows/website-preview.yml
  .gitignore
Labels: enhancement, size:M

#4307 Automatically deploy to Vercel
  .github/workflows/website-deploy.yml
  .github/workflows/website-preview.yml
Labels: size:S

#4323 Improve turbo task dependency declarations
  .github/workflows/marketplace-publish.yml
  .github/workflows/nightly-publish.yml
  MONOREPO.md
  README.md
  apps/vscode-nightly/esbuild.mjs
  apps/vscode-nightly/turbo.json
  apps/web-evals/next.config.ts
  apps/web-evals/package.json
  apps/web-evals/turbo.json
  apps/web-roo-code/turbo.json
  package.json
  src/package.json
  src/turbo.json
  turbo.json
  webview-ui/package.json
  webview-ui/turbo.json
Labels: documentation, size:L

#4228 fix(clipboard): Clear setTimeout in useCopyToClipboard to resolve memory leak
  webview-ui/src/utils/clipboard.ts
Labels: bug, size:S, lgtm, PR - Needs Review

#4235 fix(RooTips): Clear setTimeout in useEffect cleanup to prevent state updates on unmounted components
  webview-ui/src/components/welcome/RooTips.tsx
Labels: bug, size:S, lgtm, PR - Needs Review

#4259 refactor(mcp): use getDefaultEnvironment for stdio client transport
  src/services/mcp/McpHub.ts
  src/services/mcp/__tests__/McpHub.test.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#4266 ClineProvider Instance cleanup
  src/core/webview/ClineProvider.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#4332 Get rid of "partial" component in names referencing not necessarily partial messages
  src/core/task/Task.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: size:S, lgtm, Issue/PR - Triage

#3681 fix: resolve Mermaid CSP errors with enhanced bundling strategy
  webview-ui/src/components/common/MermaidBlock.tsx
  webview-ui/vite.config.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#4248 fix: Address memory leaks in ChatView component (ChatView_1113, ChatView_1236)
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:S, lgtm, PR - Needs Review

#4389 v3.19.4
  .changeset/v3.19.4.md
Labels: changelog-ready, size:S

#4401 Fix "The thinking budget (52428) is invalid" Gemini 2.5 Pro Preview e…
  .changeset/slick-knives-invent.md
  src/api/transform/__tests__/model-params.spec.ts
  src/api/transform/model-params.ts
Labels: bug, size:M

#4363 Add MCP configuration file
  .roo/mcp.json
Labels: size:S, lgtm, PR - Needs Review

#4418 Fix git clone in evals setup script
  package.json
  packages/evals/scripts/setup.sh
Labels: bug, size:XS

#4420 Update evals README.md
  packages/evals/README.md
Labels: documentation, size:S

#4422 Remove mcp.json configuration and add it to .gitignore
  .gitignore
  .roo/mcp.json
Labels: size:S, lgtm

#4428 Prevent hanging processes from preventing container cleanup
  packages/evals/src/cli/runTask.ts
Labels: size:M, lgtm

#4003 Remove usage of npx
  src/package.json
Labels: size:XS, lgtm, PR - Needs Review

#4448 Add a share button when logged into cloud
  packages/cloud/src/AuthService.ts
  packages/cloud/src/CloudService.ts
  packages/cloud/src/ShareService.ts
  packages/cloud/src/__tests__/ShareService.test.ts
  packages/cloud/src/utils.ts
  packages/types/src/cloud.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/TaskActions.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:XL, lgtm

#4352 feat: add experimental flag to disable command execution in attempt_c…
  packages/types/src/experiment.ts
  src/core/prompts/sections/objective.ts
  src/core/prompts/system.ts
  src/core/prompts/tools/__tests__/attempt-completion.test.ts
  src/core/prompts/tools/attempt-completion.ts
  src/core/prompts/tools/index.ts
  src/core/prompts/tools/types.ts
  src/core/tools/__tests__/attemptCompletionTool.experiment.test.ts
  src/core/tools/attemptCompletionTool.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/experiments.ts
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm, PR - Needs Review

#3772 fix: use safeWriteJson for all JSON file writes
  .roo/rules-code/use-safeWriteJson.md
  pnpm-lock.yaml
  src/api/providers/fetchers/modelCache.ts
  src/api/providers/fetchers/modelEndpointCache.ts
  src/core/config/__tests__/importExport.test.ts
  src/core/config/importExport.ts
  src/core/context-tracking/FileContextTracker.ts
  src/core/task-persistence/apiMessages.ts
  src/core/task-persistence/taskMessages.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/package.json
  src/services/code-index/__tests__/cache-manager.test.ts
  src/services/code-index/cache-manager.ts
  src/services/mcp/McpHub.ts
  src/services/mcp/__tests__/McpHub.test.ts
  src/utils/__tests__/safeWriteJson.test.ts
  src/utils/safeWriteJson.ts
Labels: bug, enhancement, size:XL, lgtm, PR - Needs Review

#4458 Fix Copy button logic
  webview-ui/src/components/history/CopyButton.tsx
Labels: size:S, lgtm, PR - Needs Review

#4478 Run prettier on src
  src/core/prompts/sections/__tests__/objective.test.ts
  src/core/prompts/sections/__tests__/tool-use-guidelines.test.ts
  src/core/prompts/sections/objective.ts
  src/core/prompts/sections/rules.ts
  src/core/prompts/sections/tool-use-guidelines.ts
  src/core/prompts/tools/attempt-completion.ts
  src/core/tools/__tests__/attemptCompletionTool.experiment.test.ts
Labels: size:L

#4477 Publish CI failures to Slack
  .github/actions/slack-notify/action.yml
  .github/workflows/code-qa.yml
Labels: enhancement, size:L, Issue/PR - Triage

#4470 Document how to add evals
  packages/evals/ADDING-EVALS.md
Labels: documentation, size:L, Issue/PR - Triage

#4461 Retry tasks that disconnect before completion or timeout
  packages/evals/src/cli/runTask.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#4479 Try to fix win32 esbuild
  packages/build/src/esbuild.ts
  src/esbuild.mjs
Labels: bug, size:M

#4489 Improve eval docker ports
  packages/evals/docker-compose.yml
Labels: size:S, lgtm

#4488 fix: remove explicit cache_control for Google models in OpenRouter (#4487)
  packages/types/src/providers/openrouter.ts
  src/api/providers/fetchers/__tests__/openrouter.spec.ts
Labels: bug, size:S, lgtm

#4490 v3.19.6
  .changeset/free-squids-poke.md
Labels: size:XS

#4486 Control Gemini thinking budget via Requesty
  src/api/providers/fetchers/requesty.ts
Labels: enhancement, size:S, lgtm

#4507 Switch back to GH runners for CI
  .github/workflows/code-qa.yml
Labels: size:S

#4472 GHA evals
  .github/workflows/evals.yml
  apps/web-evals/src/actions/exercises.ts
  apps/web-evals/src/actions/runs.ts
  apps/web-evals/src/app/api/health/route.ts
  packages/evals/Dockerfile.runner
  packages/evals/Dockerfile.web
  packages/evals/docker-compose.yml
  packages/evals/package.json
  packages/evals/src/cli/FileLogger.ts
  packages/evals/src/cli/index.ts
  packages/evals/src/cli/processTask.ts
  packages/evals/src/cli/runCi.ts
  packages/evals/src/cli/runEvals.ts
  packages/evals/src/cli/runTask.ts
  packages/evals/src/cli/runUnitTest.ts
  packages/evals/src/cli/utils.ts
  packages/evals/src/exercises/index.ts
Labels: size:XL, Issue/PR - Triage, evals

#4509 Disable checkpoint if nested git repos are detected
  src/core/assistant-message/presentAssistantMessage.ts
  src/core/checkpoints/index.ts
  src/core/environment/getEnvironmentDetails.ts
  src/services/checkpoints/ShadowCheckpointService.ts
  src/services/checkpoints/__tests__/ShadowCheckpointService.test.ts
  src/services/checkpoints/__tests__/excludes.test.ts
  src/services/checkpoints/constants.ts
  src/services/checkpoints/excludes.ts
Labels: size:L, lgtm

#4517 Remove Storybook + unused components
  knip.json
  pnpm-lock.yaml
  webview-ui/.storybook/main.ts
  webview-ui/.storybook/preview.ts
  webview-ui/.storybook/vscode.css
  webview-ui/package.json
  webview-ui/src/components/ui/chat/Chat.tsx
  webview-ui/src/components/ui/chat/ChatInput.tsx
  webview-ui/src/components/ui/chat/ChatInputProvider.ts
  webview-ui/src/components/ui/chat/ChatMessage.tsx
  webview-ui/src/components/ui/chat/ChatMessageProvider.ts
  webview-ui/src/components/ui/chat/ChatMessages.tsx
  webview-ui/src/components/ui/chat/ChatProvider.ts
  webview-ui/src/components/ui/chat/index.ts
  webview-ui/src/components/ui/chat/types.ts
  webview-ui/src/components/ui/chat/useChatInput.ts
  webview-ui/src/components/ui/chat/useChatMessage.ts
  webview-ui/src/components/ui/chat/useChatUI.ts
  webview-ui/src/components/ui/markdown/Blockquote.tsx
  webview-ui/src/components/ui/markdown/CodeBlock.tsx
  webview-ui/src/components/ui/markdown/Markdown.tsx
  webview-ui/src/components/ui/markdown/index.ts
  webview-ui/src/stories/AutosizeTextarea.stories.tsx
  webview-ui/src/stories/Badge.stories.tsx
  webview-ui/src/stories/Button.stories.ts
  webview-ui/src/stories/Chat.stories.tsx
  webview-ui/src/stories/Collapsible.stories.tsx
  webview-ui/src/stories/Combobox.stories.tsx
  webview-ui/src/stories/DropdownMenu.stories.tsx
  webview-ui/src/stories/Progress.stories.tsx
  webview-ui/src/stories/Slider.stories.tsx
  webview-ui/src/stories/Welcome.mdx
  webview-ui/src/stories/assets/.gitkeep
Labels: size:XXL

#4505 chore: add data-testid rule
  .roomodes
Labels: size:XS, lgtm

#4557 Revert "chore(deps): update postgres docker tag to v17"
  packages/evals/docker-compose.yml
Labels: size:XS

#4558 v3.19.7
  .changeset/v3.19.7.md
Labels: size:S

#4437 feat: Add Issue Writer and Issue Fixer modes with comprehensive workflows
  .roo/rules-issue-fixer/1_Workflow.xml
  .roo/rules-issue-fixer/2_best_practices.xml
  .roo/rules-issue-fixer/3_common_patterns.xml
  .roo/rules-issue-fixer/4_github_mcp_tool_usage.xml
  .roo/rules-issue-fixer/5_pull_request_workflow.xml
  .roo/rules-issue-fixer/6_testing_guidelines.xml
  .roo/rules-issue-fixer/7_communication_style.xml
  .roo/rules-issue-fixer/8_github_communication_guidelines.xml
  .roo/rules-issue-fixer/9_pr_review_workflow.xml
  .roo/rules-issue-writer/1_workflow.xml
  .roo/rules-issue-writer/2_github_issue_templates.xml
  .roo/rules-issue-writer/3_best_practices.xml
  .roo/rules-issue-writer/4_common_mistakes_to_avoid.xml
  .roo/rules-issue-writer/5_github_mcp_tool_usage.xml
  .roomodes
Labels: documentation, enhancement, size:XXL, lgtm, PR - Needs Review

#4531 Add PR Reviewer mode
  .roo/rules-pr-reviewer/1_workflow.xml
  .roo/rules-pr-reviewer/2_best_practices.xml
  .roo/rules-pr-reviewer/3_common_mistakes_to_avoid.xml
  .roomodes
Labels: enhancement, size:L, lgtm, PR - Needs Review

#4543 Fix OpenRouter cost calculation with BYOK
  src/api/providers/openrouter.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#4580 Update o3 prices
  packages/types/src/providers/openai.ts
Labels: size:S, lgtm

#4444 fix: TaskItem display and copy issues with HTML tags in task messages.
  webview-ui/src/components/history/CopyButton.tsx
  webview-ui/src/components/history/TaskItem.tsx
  webview-ui/src/components/history/useTaskSearch.ts
  webview-ui/src/utils/highlight.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#4511 Always focus the panel when clicked to ensure menu buttons are visible
  .changeset/khaki-clocks-float.md
  packages/telemetry/src/TelemetryService.ts
  packages/types/src/vscode.ts
  src/activate/registerCommands.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/WebviewMessage.ts
  src/utils/focusPanel.ts
  webview-ui/src/App.tsx
  webview-ui/src/components/ui/hooks/index.ts
  webview-ui/src/components/ui/hooks/useNonInteractiveClick.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#3485 feat(mcp): improve mcp with McpExecution, make UX like terminal execute
  packages/types/src/index.ts
  packages/types/src/mcp.ts
  src/core/tools/__tests__/useMcpToolTool.test.ts
  src/core/tools/useMcpToolTool.ts
  src/i18n/locales/ca/mcp.json
  src/i18n/locales/de/mcp.json
  src/i18n/locales/en/mcp.json
  src/i18n/locales/es/mcp.json
  src/i18n/locales/fr/mcp.json
  src/i18n/locales/hi/mcp.json
  src/i18n/locales/it/mcp.json
  src/i18n/locales/ja/mcp.json
  src/i18n/locales/ko/mcp.json
  src/i18n/locales/nl/mcp.json
  src/i18n/locales/pl/mcp.json
  src/i18n/locales/pt-BR/mcp.json
  src/i18n/locales/ru/mcp.json
  src/i18n/locales/tr/mcp.json
  src/i18n/locales/vi/mcp.json
  src/i18n/locales/zh-CN/mcp.json
  src/i18n/locales/zh-TW/mcp.json
  src/shared/ExtensionMessage.ts
  src/shared/__tests__/combineCommandSequences.test.ts
  src/shared/combineCommandSequences.ts
  webview-ui/jest.config.cjs
  webview-ui/src/__mocks__/react-markdown.tsx
  webview-ui/src/__mocks__/remark-gfm.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/McpExecution.tsx
  webview-ui/src/components/common/CodeAccordian.tsx
  webview-ui/src/i18n/locales/ca/mcp.json
  webview-ui/src/i18n/locales/de/mcp.json
  webview-ui/src/i18n/locales/en/mcp.json
  webview-ui/src/i18n/locales/es/mcp.json
  webview-ui/src/i18n/locales/fr/mcp.json
  webview-ui/src/i18n/locales/hi/mcp.json
  webview-ui/src/i18n/locales/it/mcp.json
  webview-ui/src/i18n/locales/ja/mcp.json
  webview-ui/src/i18n/locales/ko/mcp.json
  webview-ui/src/i18n/locales/nl/mcp.json
  webview-ui/src/i18n/locales/pl/mcp.json
  webview-ui/src/i18n/locales/pt-BR/mcp.json
  webview-ui/src/i18n/locales/ru/mcp.json
  webview-ui/src/i18n/locales/tr/mcp.json
  webview-ui/src/i18n/locales/vi/mcp.json
  webview-ui/src/i18n/locales/zh-CN/mcp.json
  webview-ui/src/i18n/locales/zh-TW/mcp.json
Labels: enhancement, size:XXL, lgtm, PR - Needs Review

#4584 Bump @roo-code/types to v1.26.0
  packages/types/README.md
  packages/types/npm/package.json
  webview-ui/package.json
Labels: documentation, size:S, lgtm, Issue/PR - Triage

#4525 feat: Add DeepSeek R1 support to Chutes provider (#4523)
  src/api/providers/__tests__/chutes.spec.ts
  src/api/providers/base-openai-compatible-provider.ts
  src/api/providers/chutes.ts
Labels: enhancement, size:L, lgtm, PR - Needs Review

#4450 feat: Navigate prompt history in prompt field via arrow up/down (#4139)
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/__tests__/ChatTextArea.test.tsx
  webview-ui/src/components/chat/hooks/usePromptHistory.ts
Labels: size:XL, lgtm, UI/UX, PR - Needs Review

#4427 docs: add JSDoc documentation for ClineAsk and ClineSay types
  packages/types/src/message.ts
Labels: documentation, size:M, lgtm, PR - Needs Review

#4362 feat: Allow escaping of context mentions
  src/core/tools/__tests__/newTaskTool.test.ts
  src/core/tools/newTaskTool.ts
  src/shared/__tests__/context-mentions.test.ts
  src/shared/context-mentions.ts
Labels: documentation, enhancement, size:L, lgtm, PR - Needs Review

#4315 update xai models and pricing
  .changeset/cruel-roses-stick.md
  packages/types/src/providers/xai.ts
  src/api/providers/__tests__/xai.test.ts
  src/api/providers/xai.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#3342 feat: Enhance apply_diff with XML for multi-file/multi-diff operations & batch UI
  packages/types/src/experiment.ts
  src/core/assistant-message/presentAssistantMessage.ts
  src/core/diff/strategies/multi-file-search-replace.ts
  src/core/prompts/__tests__/sections.test.ts
  src/core/task/Task.ts
  src/core/task/__tests__/Task.test.ts
  src/core/tools/__tests__/applyDiffTool.experiment.spec.ts
  src/core/tools/applyDiffTool.ts
  src/core/tools/multiApplyDiffTool.ts
  src/core/webview/generateSystemPrompt.ts
  src/shared/ExtensionMessage.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/experiments.ts
  src/shared/tools.ts
  webview-ui/src/components/chat/BatchDiffApproval.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: bug, enhancement, size:XXL, lgtm, UI/UX, PR - Needs Review

#4481 feat: Add reasoning budget support to Bedrock models for extended thinking (#4201)
  packages/types/src/providers/bedrock.ts
  src/api/providers/__tests__/bedrock-reasoning.test.ts
  src/api/providers/bedrock.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/providers/Bedrock.tsx
Labels: enhancement, size:XL, lgtm, UI/UX, PR - Needs Review

#4599 Evals fixes
  packages/evals/src/cli/runTask.ts
  packages/types/src/experiment.ts
  src/shared/ExtensionMessage.ts
  src/shared/experiments.ts
  webview-ui/src/components/settings/ExperimentalSettings.tsx
Labels: size:M, lgtm, Issue/PR - Triage

#4608 Fix undefined on multi-file apply_diff output
  src/core/assistant-message/presentAssistantMessage.ts
Labels: bug, size:S, lgtm, Issue/PR - Triage

#4609 v3.20
  .changeset/v3.20.0.md
  .roomodes
  README.md
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/nl/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/ru/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/README.md
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: documentation, size:XXL, Issue/PR - Triage

#4615 Improve performance of MCP execution block
  webview-ui/src/components/chat/McpExecution.tsx
Labels: enhancement, size:L, PR - Needs Review

#4626 Revert "feat: Add reasoning budget support to Bedrock models for extended thinking (#4201)"
  packages/types/src/providers/bedrock.ts
  src/api/providers/__tests__/bedrock-reasoning.test.ts
  src/api/providers/bedrock.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/providers/Bedrock.tsx
Labels: size:XL

#4634 Update ContextManagementSettings.tsx
  webview-ui/src/components/settings/ContextManagementSettings.tsx
Labels: size:XS, lgtm, Issue/PR - Triage

#4585 Add cache breakpoints for custom vertex models on Unbound
  src/api/providers/unbound.ts
Labels: enhancement, size:XS, lgtm, PR - Needs Preliminary Review

#4645 Reapply reasoning for bedrock with fix
  packages/types/src/providers/bedrock.ts
  src/api/providers/__tests__/bedrock-reasoning.test.ts
  src/api/providers/bedrock.ts
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/providers/Bedrock.tsx
Labels: size:XL, lgtm, PR - Needs Review

#4652 Feat: Improve Issue Fixer Rules for Targeted Fixes
  .roo/rules-issue-fixer/1_Workflow.xml
  .roo/rules-issue-fixer/2_best_practices.xml
Labels: size:S, lgtm, PR - Needs Review

#4649 Prevent MCP 'installed' label from being squeezed #4630
  webview-ui/src/components/marketplace/components/MarketplaceItemCard.tsx
Labels: size:XS, lgtm, UI/UX, PR - Needs Review

#4644 feat(ui): add max height constraint to MCP execution response
  webview-ui/src/components/chat/McpExecution.tsx
Labels: size:XS, lgtm, UI/UX, PR - Needs Review

#4596 ♻️ Refactor: Avoid type system duplication
  packages/types/src/global-settings.ts
  packages/types/src/provider-settings.ts
  packages/types/src/type-fu.ts
Labels: size:L, lgtm, PR - Needs Preliminary Review

#4662 v3.20.2
  .changeset/v3.20.2.md
Labels: changelog-ready, size:S

#4670 Adjust searching outside of the workspace to respect the auto-approve…
  src/core/tools/__tests__/searchFilesTool.spec.ts
  src/core/tools/searchFilesTool.ts
  src/i18n/locales/ca/tools.json
  src/i18n/locales/de/tools.json
  src/i18n/locales/en/tools.json
  src/i18n/locales/es/tools.json
  src/i18n/locales/fr/tools.json
  src/i18n/locales/hi/tools.json
  src/i18n/locales/it/tools.json
  src/i18n/locales/ja/tools.json
  src/i18n/locales/ko/tools.json
  src/i18n/locales/nl/tools.json
  src/i18n/locales/pl/tools.json
  src/i18n/locales/pt-BR/tools.json
  src/i18n/locales/ru/tools.json
  src/i18n/locales/tr/tools.json
  src/i18n/locales/vi/tools.json
  src/i18n/locales/zh-CN/tools.json
  src/i18n/locales/zh-TW/tools.json
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:L, lgtm, Issue/PR - Triage

#4667 Add logic to prevent auto-approving edits of configuration files
  packages/types/src/global-settings.ts
  packages/types/src/message.ts
  src/core/assistant-message/presentAssistantMessage.ts
  src/core/prompts/responses.ts
  src/core/protect/RooProtectedController.ts
  src/core/protect/__tests__/RooProtectedController.spec.ts
  src/core/task/Task.ts
  src/core/tools/insertContentTool.ts
  src/core/tools/listFilesTool.ts
  src/core/tools/multiApplyDiffTool.ts
  src/core/tools/searchAndReplaceTool.ts
  src/core/tools/writeToFileTool.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/tools.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm, PR - Draft / In Progress

#4674 Fix multi-file diff error handling and UI feedback
  src/core/diff/strategies/multi-file-search-replace.ts
  src/core/tools/multiApplyDiffTool.ts
Labels: bug, size:S, lgtm, UI/UX, Issue/PR - Triage

#4672 ✨feat: Indonesian translation
  .roo/rules-translate/001-general-rules.md
  packages/types/src/vscode.ts
  src/i18n/locales/id/common.json
  src/i18n/locales/id/marketplace.json
  src/i18n/locales/id/mcp.json
  src/i18n/locales/id/tools.json
  src/package.nls.id.json
  src/shared/language.ts
  webview-ui/src/i18n/locales/id/account.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/id/common.json
  webview-ui/src/i18n/locales/id/history.json
  webview-ui/src/i18n/locales/id/humanRelay.json
  webview-ui/src/i18n/locales/id/marketplace.json
  webview-ui/src/i18n/locales/id/mcp.json
  webview-ui/src/i18n/locales/id/prompts.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/id/welcome.json
Labels: enhancement, size:XXL, lgtm, Issue/PR - Triage

#4675 Update Indonesian locale files for chat and settings
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/id/settings.json
Labels: documentation, size:XS, lgtm, PR - Needs Review

#4681 Fix inconsistencies in markdown file i18n
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  locales/ca/CODE_OF_CONDUCT.md
  locales/ca/CONTRIBUTING.md
  locales/de/CODE_OF_CONDUCT.md
  locales/de/CONTRIBUTING.md
  locales/es/CODE_OF_CONDUCT.md
  locales/es/CONTRIBUTING.md
  locales/fr/CODE_OF_CONDUCT.md
  locales/fr/CONTRIBUTING.md
  locales/hi/CODE_OF_CONDUCT.md
  locales/hi/CONTRIBUTING.md
  locales/id/CODE_OF_CONDUCT.md
  locales/id/CONTRIBUTING.md
  locales/it/CODE_OF_CONDUCT.md
  locales/it/CONTRIBUTING.md
  locales/ja/CODE_OF_CONDUCT.md
  locales/ja/CONTRIBUTING.md
  locales/ko/CODE_OF_CONDUCT.md
  locales/ko/CONTRIBUTING.md
  locales/nl/CODE_OF_CONDUCT.md
  locales/nl/CONTRIBUTING.md
  locales/pl/CODE_OF_CONDUCT.md
  locales/pl/CONTRIBUTING.md
  locales/pt-BR/CODE_OF_CONDUCT.md
  locales/pt-BR/CONTRIBUTING.md
  locales/ru/CODE_OF_CONDUCT.md
  locales/ru/CONTRIBUTING.md
  locales/tr/CODE_OF_CONDUCT.md
  locales/tr/CONTRIBUTING.md
  locales/vi/CODE_OF_CONDUCT.md
  locales/vi/CONTRIBUTING.md
  locales/zh-CN/CODE_OF_CONDUCT.md
  locales/zh-CN/CONTRIBUTING.md
  locales/zh-TW/CODE_OF_CONDUCT.md
  locales/zh-TW/CONTRIBUTING.md
Labels: documentation, size:L, Issue/PR - Triage

#4682 Make listing tools respect auto-approve settings for outside of the workspace
  src/core/tools/listCodeDefinitionNamesTool.ts
  src/core/tools/listFilesTool.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, lgtm

#4683 Fix errant maxReadFileLine default
  src/core/tools/readFileTool.ts
Labels: bug, size:XS

#4685 v3.20.3
  .changeset/v3.20.3.md
Labels: changelog-ready, size:S

#4684 refactor: more consistent history UI
  webview-ui/src/components/history/CopyButton.tsx
  webview-ui/src/components/history/DeleteButton.tsx
  webview-ui/src/components/history/ExportButton.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/history/TaskItem.tsx
  webview-ui/src/components/history/TaskItemFooter.tsx
  webview-ui/src/components/history/TaskItemHeader.tsx
  webview-ui/src/components/history/__tests__/BatchDeleteTaskDialog.test.tsx
  webview-ui/src/components/history/__tests__/CopyButton.test.tsx
  webview-ui/src/components/history/__tests__/DeleteButton.test.tsx
  webview-ui/src/components/history/__tests__/DeleteTaskDialog.test.tsx
  webview-ui/src/components/history/__tests__/ExportButton.test.tsx
  webview-ui/src/components/history/__tests__/HistoryPreview.test.tsx
  webview-ui/src/components/history/__tests__/HistoryView.test.tsx
  webview-ui/src/components/history/__tests__/TaskItem.test.tsx
  webview-ui/src/components/history/__tests__/TaskItemFooter.test.tsx
  webview-ui/src/components/history/__tests__/TaskItemHeader.test.tsx
  webview-ui/src/components/history/__tests__/useTaskSearch.test.tsx
  webview-ui/src/i18n/locales/ca/history.json
  webview-ui/src/i18n/locales/de/history.json
  webview-ui/src/i18n/locales/en/history.json
  webview-ui/src/i18n/locales/es/history.json
  webview-ui/src/i18n/locales/fr/history.json
  webview-ui/src/i18n/locales/hi/history.json
  webview-ui/src/i18n/locales/id/history.json
  webview-ui/src/i18n/locales/it/history.json
  webview-ui/src/i18n/locales/ja/history.json
  webview-ui/src/i18n/locales/ko/history.json
  webview-ui/src/i18n/locales/nl/history.json
  webview-ui/src/i18n/locales/pl/history.json
  webview-ui/src/i18n/locales/pt-BR/history.json
  webview-ui/src/i18n/locales/ru/history.json
  webview-ui/src/i18n/locales/tr/history.json
  webview-ui/src/i18n/locales/vi/history.json
  webview-ui/src/i18n/locales/zh-CN/history.json
  webview-ui/src/i18n/locales/zh-TW/history.json
Labels: size:XXL, lgtm, UI/UX, Issue/PR - Triage

#4600 Add Mode Writer mode to repo
  .roo/rules-mode-writer/1_mode_creation_workflow.xml
  .roo/rules-mode-writer/2_xml_structuring_best_practices.xml
  .roo/rules-mode-writer/3_mode_configuration_patterns.xml
  .roo/rules-mode-writer/4_instruction_file_templates.xml
  .roo/rules-mode-writer/5_complete_mode_examples.xml
  .roo/rules-mode-writer/6_mode_testing_validation.xml
  .roomodes
Labels: enhancement, size:XXL, lgtm, PR - Needs Review

#4623 Fix the save/discard/revert flow for Prompt Settings
  src/core/webview/webviewMessageHandler.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/settings/PromptsSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: bug, size:M, lgtm, PR - Needs Preliminary Review

#4710 refactor: reorganize implementation plan step in workflow
  .roo/rules-issue-fixer/1_Workflow.xml
Labels: size:M, lgtm

#4717 fix: update marketplace branding to 'Roo Marketplace' (#4706)
  webview-ui/src/i18n/locales/ca/marketplace.json
  webview-ui/src/i18n/locales/de/marketplace.json
  webview-ui/src/i18n/locales/en/marketplace.json
  webview-ui/src/i18n/locales/es/marketplace.json
  webview-ui/src/i18n/locales/fr/marketplace.json
  webview-ui/src/i18n/locales/hi/marketplace.json
  webview-ui/src/i18n/locales/id/marketplace.json
  webview-ui/src/i18n/locales/it/marketplace.json
  webview-ui/src/i18n/locales/ja/marketplace.json
  webview-ui/src/i18n/locales/ko/marketplace.json
  webview-ui/src/i18n/locales/nl/marketplace.json
  webview-ui/src/i18n/locales/pl/marketplace.json
  webview-ui/src/i18n/locales/pt-BR/marketplace.json
  webview-ui/src/i18n/locales/ru/marketplace.json
  webview-ui/src/i18n/locales/tr/marketplace.json
  webview-ui/src/i18n/locales/vi/marketplace.json
  webview-ui/src/i18n/locales/zh-CN/marketplace.json
  webview-ui/src/i18n/locales/zh-TW/marketplace.json
Labels: size:M, lgtm, UI/UX

#4709 fix: align codebase indexing with list-files hidden directory filtering
  src/services/code-index/processors/__tests__/file-watcher.spec.ts
  src/services/code-index/processors/__tests__/scanner.spec.ts
  src/services/code-index/processors/file-watcher.ts
  src/services/code-index/processors/scanner.ts
  src/services/glob/constants.ts
  src/services/glob/ignore-utils.ts
  src/services/glob/list-files.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#4762 Support config policies that require use of cloud
  src/core/tools/newTaskTool.ts
  src/core/webview/ClineProvider.ts
  src/extension.ts
  src/extension/api.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/ca/tools.json
  src/i18n/locales/de/common.json
  src/i18n/locales/de/tools.json
  src/i18n/locales/en/common.json
  src/i18n/locales/en/tools.json
  src/i18n/locales/es/common.json
  src/i18n/locales/es/tools.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/fr/tools.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/hi/tools.json
  src/i18n/locales/id/common.json
  src/i18n/locales/id/tools.json
  src/i18n/locales/it/common.json
  src/i18n/locales/it/tools.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ja/tools.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/ko/tools.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/nl/tools.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pl/tools.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/pt-BR/tools.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/ru/tools.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/tr/tools.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/vi/tools.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-CN/tools.json
  src/i18n/locales/zh-TW/common.json
  src/i18n/locales/zh-TW/tools.json
  src/services/mdm/MdmService.ts
  src/services/mdm/__tests__/MdmService.spec.ts
Labels: size:L, lgtm, Issue/PR - Triage

#4770 MDM check improvements
  packages/cloud/src/Config.ts
  src/core/webview/ClineProvider.ts
  src/services/mdm/MdmService.ts
  src/services/mdm/__tests__/MdmService.spec.ts
  webview-ui/src/App.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: size:M, lgtm, Issue/PR - Triage

#4781 Add telemetry for marketplace tab views and install clicks
  packages/types/npm/package.json
  packages/types/src/telemetry.ts
  webview-ui/src/App.tsx
  webview-ui/src/components/marketplace/components/MarketplaceItemCard.tsx
Labels: size:S, Issue/PR - Triage

#4783 Include the cwd in the terminal details
  src/core/environment/__tests__/getEnvironmentDetails.spec.ts
  src/core/environment/getEnvironmentDetails.ts
Labels: enhancement, size:M, lgtm

#4778 Update test mode for Vitest
  .roomodes
Labels: size:S, lgtm, PR - Needs Review

#4588 update provider models and prices for Groq & Mistral
  packages/types/src/providers/groq.ts
  packages/types/src/providers/mistral.ts
Labels: documentation, enhancement, size:M, lgtm, PR - Needs Review

#4312 Add proper error handling for API conversation history issues
  src/core/task-persistence/apiMessages.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#4306 fix: ambiguous model id error
  webview-ui/src/components/settings/ApiErrorMessage.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/__tests__/ModelPicker.test.tsx
  webview-ui/src/components/settings/providers/Glama.tsx
  webview-ui/src/components/settings/providers/LiteLLM.tsx
  webview-ui/src/components/settings/providers/OpenAICompatible.tsx
  webview-ui/src/components/settings/providers/OpenRouter.tsx
  webview-ui/src/components/settings/providers/Requesty.tsx
  webview-ui/src/components/settings/providers/Unbound.tsx
  webview-ui/src/components/ui/hooks/__tests__/useSelectedModel.test.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/utils/__tests__/validate.test.ts
  webview-ui/src/utils/validate.ts
Labels: bug, size:XL, lgtm, PR - Needs Review

#4795 Remove warning about commands switching working directory
  src/core/tools/executeCommandTool.ts
Labels: size:XS, lgtm

#4797 Ignore logs in git
  .gitignore
  MONOREPO.md
  apps/web-evals/package.json
Labels: size:M, lgtm

#4789 fix: update wording in GitHub MCP tool usage guide
  .roo/rules-issue-writer/1_workflow.xml
  .roo/rules-issue-writer/5_github_mcp_tool_usage.xml
Labels: documentation, size:S, lgtm, PR - Needs Review

#4598 Reapply "Always focus the panel when clicked to ensure menu buttons are visible"
  .changeset/khaki-clocks-float.md
  packages/telemetry/src/TelemetryService.ts
  packages/types/src/vscode.ts
  src/activate/registerCommands.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/WebviewMessage.ts
  src/utils/focusPanel.ts
  webview-ui/src/App.tsx
  webview-ui/src/components/ui/hooks/index.ts
  webview-ui/src/components/ui/hooks/useNonInteractiveClick.ts
Labels: size:L, lgtm, UI/UX, PR - Needs Review

#4800 v3.21.0
  .changeset/v3.21.0.md
  README.md
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/id/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/nl/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/ru/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/README.md
  src/core/webview/ClineProvider.ts
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: documentation, size:XXL

#4711 fix: resolve MCP server execution on Windows with node version managers (#1246)
  src/services/mcp/McpHub.ts
  src/services/mcp/__tests__/McpHub.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#4432 fix: improve error handling for codebase search embeddings
  src/i18n/locales/ca/embeddings.json
  src/i18n/locales/de/embeddings.json
  src/i18n/locales/en/embeddings.json
  src/i18n/locales/es/embeddings.json
  src/i18n/locales/fr/embeddings.json
  src/i18n/locales/hi/embeddings.json
  src/i18n/locales/id/embeddings.json
  src/i18n/locales/it/embeddings.json
  src/i18n/locales/ja/embeddings.json
  src/i18n/locales/ko/embeddings.json
  src/i18n/locales/nl/embeddings.json
  src/i18n/locales/pl/embeddings.json
  src/i18n/locales/pt-BR/embeddings.json
  src/i18n/locales/ru/embeddings.json
  src/i18n/locales/tr/embeddings.json
  src/i18n/locales/vi/embeddings.json
  src/i18n/locales/zh-CN/embeddings.json
  src/i18n/locales/zh-TW/embeddings.json
  src/services/code-index/embedders/__tests__/openai-compatible.spec.ts
  src/services/code-index/embedders/__tests__/openai.spec.ts
  src/services/code-index/embedders/ollama.ts
  src/services/code-index/embedders/openai-compatible.ts
  src/services/code-index/embedders/openai.ts
  src/services/code-index/orchestrator.ts
  src/services/code-index/processors/scanner.ts
  src/services/code-index/vector-store/__tests__/qdrant-client.spec.ts
  src/services/code-index/vector-store/qdrant-client.ts
Labels: bug, size:XXL, lgtm, PR - Needs Review

#4838 Fix #4837: Default 'Enable MCP Server Creation' to false
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: bug, size:XS, lgtm, Issue/PR - Triage

#4453 Rate limit when starting a subtask
  .vscode/settings.json
  src/core/task/Task.ts
  src/core/task/__tests__/Task.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#4844 Fix a couple security vulnerabilities for dependabot
  package.json
  pnpm-lock.yaml
Labels: size:XS, lgtm

#4847 feat: streamline feature request template to focus on problem reporting
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size:L, lgtm, UI/UX

#4857 Fix tree-sitter
  src/services/tree-sitter/__tests__/languageParser.spec.ts
  src/services/tree-sitter/languageParser.ts
Labels: bug, size:L, Issue/PR - Triage

#4539 cloud service cleanup (auth mostly)
  packages/cloud/src/AuthService.ts
  packages/cloud/src/CloudService.ts
  packages/cloud/src/SettingsService.ts
  packages/cloud/src/__mocks__/vscode.ts
  packages/cloud/src/__tests__/AuthService.spec.ts
  packages/cloud/src/__tests__/CloudService.test.ts
Labels: enhancement, size:XXL, lgtm, PR - Draft / In Progress

#4893 fix: resolve phantom subtask display on cancel during API retry (#4602)
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/webviewMessageHandler.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#4898 fix: correct Gemini 2.5 Flash pricing (#4836)
  packages/types/src/providers/gemini.ts
  packages/types/src/providers/vertex.ts
Labels: bug, size:S, lgtm

#4910 Update privacy policy to comprehensive Roo Code Cloud policy
  apps/web-roo-code/src/app/privacy/page.tsx
  apps/web-roo-code/src/components/chromes/footer.tsx
Labels: documentation, size:L, lgtm

#4914 Update enterprise page with control-plane messaging
  apps/web-roo-code/src/app/enterprise/page.tsx
Labels: size:L, lgtm

#4899 Add choice to share with organization or publicly
  packages/cloud/src/CloudService.ts
  packages/cloud/src/ShareService.ts
  packages/cloud/src/__tests__/ShareService.test.ts
  packages/types/src/cloud.ts
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/id/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/TaskActions.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/id/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, lgtm, Issue/PR - Triage

#4916 Fix roocode.com Vercel preview on PR open
  .github/workflows/website-preview.yml
  apps/web-evals/package.json
  apps/web-roo-code/package.json
  apps/web-roo-code/src/app/privacy/page.tsx
Labels: size:M, lgtm

#4920 feat: add Terms of Service page at /terms
  apps/web-roo-code/src/app/terms/page.tsx
  apps/web-roo-code/src/components/chromes/footer.tsx
Labels: enhancement, size:L, lgtm

#4922 Scope dev RCC credentials by dev url
  packages/cloud/src/AuthService.ts
  packages/cloud/src/__tests__/AuthService.spec.ts
Labels: enhancement, size:L, lgtm, Issue/PR - Triage

#4941 fix: resolve marketplace timeout issues and display installed MCPs (#4817)
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/marketplace/MarketplaceView.tsx
  webview-ui/src/components/marketplace/MarketplaceViewStateManager.ts
  webview-ui/src/components/marketplace/components/MarketplaceInstallModal.tsx
  webview-ui/src/components/marketplace/components/MarketplaceItemCard.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: bug, size:L, lgtm, PR - Needs Review

#4863 Fix recursive directory scanning in @ mention "Add Folder" functionality
  src/services/glob/list-files.ts
Labels: bug, size:M, lgtm, PR - Needs Review

#4796 Fixes #4794: Fix marketplace blanking after populating
  webview-ui/src/components/marketplace/MarketplaceView.tsx
  webview-ui/src/components/marketplace/MarketplaceViewStateManager.ts
  webview-ui/src/components/marketplace/__tests__/MarketplaceViewStateManager.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#4786 feat: add LaTeX math equation rendering in chat window (#4258)
  pnpm-lock.yaml
  src/.vscodeignore
  src/core/webview/ClineProvider.ts
  webview-ui/package.json
  webview-ui/src/components/common/MarkdownBlock.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.spec.tsx
  webview-ui/src/index.css
  webview-ui/vite.config.ts
Labels: enhancement, size:M, lgtm, PR - Needs Review

#4954 fix: update MarketplaceViewStateManager test to match default isFetching state
  webview-ui/src/components/marketplace/__tests__/MarketplaceViewStateManager.spec.ts
Labels: bug, size:XS, lgtm, PR - Needs Review

#4841 Update MarkdownBlock.tsx
  webview-ui/src/components/common/MarkdownBlock.tsx
  webview-ui/src/components/common/__tests__/MarkdownBlock.spec.tsx
Labels: bug, size:L, lgtm, PR - Needs Review

#4884 Fixes #4882: Remove experimental setting for command execution in attempt_completion
  packages/types/src/experiment.ts
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/architect-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/ask-mode-prompt.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-disabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/mcp-server-creation-enabled.snap
  src/core/prompts/__tests__/__snapshots__/add-custom-instructions/partial-reads-enabled.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/consistent-system-prompt.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-computer-use-support.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-false.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-true.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-diff-enabled-undefined.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-different-viewport-size.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-mcp-hub-provided.snap
  src/core/prompts/__tests__/__snapshots__/system-prompt/with-undefined-mcp-hub.snap
  src/core/prompts/sections/objective.ts
  src/core/prompts/tools/__tests__/attempt-completion.spec.ts
  src/core/prompts/tools/attempt-completion.ts
  src/core/tools/__tests__/attemptCompletionTool.experiment.spec.ts
  src/core/tools/attemptCompletionTool.ts
  src/shared/__tests__/experiments.spec.ts
  src/shared/experiments.ts
  src/shared/tools.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: size:XL, lgtm, PR - Needs Review

#4964 v3.21.2
  .changeset/v3.21.2.md
Labels: changelog-ready, size:S

#4314 fix context length for lmstudio and ollama (#2462)
  packages/types/src/providers/index.ts
  packages/types/src/providers/lm-studio.ts
  packages/types/src/providers/ollama.ts
  pnpm-lock.yaml
  src/api/providers/fetchers/__tests__/fixtures/lmstudio-model-details.json
  src/api/providers/fetchers/__tests__/fixtures/ollama-model-details.json
  src/api/providers/fetchers/__tests__/lmstudio.test.ts
  src/api/providers/fetchers/__tests__/ollama.test.ts
  src/api/providers/fetchers/lmstudio.ts
  src/api/providers/fetchers/modelCache.ts
  src/api/providers/fetchers/ollama.ts
  src/api/providers/ollama.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/__tests__/webviewMessageHandler.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/package.json
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/providers/LMStudio.tsx
  webview-ui/src/components/settings/providers/Ollama.tsx
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/utils/__tests__/validate.test.ts
  webview-ui/src/utils/validate.ts
Labels: bug, documentation, size:XL, lgtm, PR - Needs Review

#4456 feat: add profile-specific context condensing thresholds
  packages/types/src/global-settings.ts
  src/core/condense/index.ts
  src/core/sliding-window/__tests__/sliding-window.spec.ts
  src/core/sliding-window/index.ts
  src/core/task/Task.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.spec.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/settings/ContextManagementSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/__tests__/ContextManagementSettings.spec.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.spec.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/id/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm, UI/UX, PR - Needs Review

#4972 Fix flakey ModelPicker test
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/__tests__/ModelPicker.spec.tsx
Labels: bug, size:M

#4985 Simplify PR template checklist for code quality and testing
  .github/pull_request_template.md
Labels: documentation, size:S, lgtm

#4987 Remove type of change from PR template
  .github/pull_request_template.md
Labels: size:S

#4994 fix: resolve MCP tool eye icon state and hide in chat context (#4993)
  webview-ui/src/components/chat/McpExecution.tsx
  webview-ui/src/components/mcp/McpToolRow.tsx
  webview-ui/src/components/mcp/__tests__/McpToolRow.spec.tsx
Labels: bug, size:M, lgtm, UI/UX

#4997 v3.21.3
  .changeset/v3.21.3.md
Labels: changelog-ready, size:XS

#4990 The goal of this change is to give the mode writer access to a list o…
  .roomodes
Labels: size:XS, lgtm, PR - Needs Review

#4980 fix: resolve diff editor issues with markdown preview associations (#4946)
  src/integrations/editor/DiffViewProvider.ts
  src/integrations/editor/__tests__/DiffViewProvider.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5022 Refine PR Reviewer mode: focus on issues, minimize markdown
  .roo/rules-pr-reviewer/1_workflow.xml
  .roo/rules-pr-reviewer/2_best_practices.xml
  .roo/rules-pr-reviewer/3_common_mistakes_to_avoid.xml
Labels: enhancement, size:S, lgtm, PR - Needs Review

#4823 Close the local browser when used as fallback for remote
  .changeset/curly-states-see.md
  src/services/browser/BrowserSession.ts
  src/services/browser/__tests__/BrowserSession.spec.ts
Labels: bug, size:L, lgtm, PR - Needs Review

#5019 fix: start line not working in multiple apply diff
  src/core/diff/strategies/multi-file-search-replace.ts
Labels: bug, size:XS, lgtm, PR - Needs Preliminary Review

#5002 Store the organization id in credentials
  packages/cloud/src/AuthService.ts
  packages/cloud/src/CloudService.ts
  packages/cloud/src/__tests__/AuthService.spec.ts
  packages/cloud/src/__tests__/CloudService.test.ts
  packages/types/src/cloud.ts
  src/activate/handleUri.ts
  src/services/mdm/MdmService.ts
  src/services/mdm/__tests__/MdmService.spec.ts
Labels: size:L, lgtm, PR - Draft / In Progress
