Repository RooCodeInc/Roo-Code, pull requests merged in 2025-03, with the labels that each got.

#1279 Move integration tests into its own module
  .github/workflows/changeset-release.yml
  .github/workflows/code-qa.yml
  .vscodeignore
  e2e/.env.integration.example
  e2e/.vscode-test.mjs
  e2e/VSCODE_INTEGRATION_TESTS.md
  e2e/package-lock.json
  e2e/package.json
  e2e/src/runTest.ts
  e2e/src/suite/extension.test.ts
  e2e/src/suite/index.ts
  e2e/src/suite/modes.test.ts
  e2e/src/suite/task.test.ts
  e2e/tsconfig.json
  knip.json
  package-lock.json
  package.json
  src/exports/cline.d.ts
  src/shared/modes.ts
Labels: enhancement, size:L

#1275 Estimate the number of tokens in the last message for sliding window math
  e2e/.vscode-test.mjs
  e2e/package.json
  e2e/src/runTest.ts
  e2e/tsconfig.json
  package-lock.json
  package.json
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
Labels: enhancement, size:L, lgtm

#1277 Update ChatView.tsx
  webview-ui/src/components/chat/ChatView.tsx
Labels: size:XS

#1289 Add a 5k token buffer before the end of the context window
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
Labels: enhancement, size:M

#1264 Changeset version bump
  .changeset/chilly-bugs-pay.md
  .changeset/swift-lamps-decide.md
  .changeset/tasty-grapes-suffer.md
  .changeset/young-hornets-taste.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:M

#1291 Fix "install dependencies" section of marketplace-publish
  .github/workflows/marketplace-publish.yml
  package.json
Labels: size:XS, lgtm

#1282 feat: Add support for Gemini models on Vertex AI
  .changeset/dry-suits-shake.md
  package-lock.json
  package.json
  src/api/providers/__tests__/vertex.test.ts
  src/api/providers/vertex.ts
  src/api/transform/__tests__/vertex-gemini-format.test.ts
  src/api/transform/vertex-gemini-format.ts
  src/shared/api.ts
Labels: enhancement, size:XL, lgtm

#1296 Mermaids
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/shared/modes.ts
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/components/common/MarkdownBlock.tsx
  webview-ui/src/components/common/MermaidBlock.tsx
  webview-ui/src/utils/useDebounceEffect.ts
Labels: enhancement, size:L, lgtm

#1270 feat: add shortcut to switch modes
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/__tests__/ChatTextArea.test.tsx
Labels: enhancement, size:M, lgtm

#1297 Add type='module' to webview script
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:XS, lgtm

#1299 v3.7.10
  .changeset/young-pigs-refuse.md
Labels: size:XS

#1298 Changeset version bump
  .changeset/dry-suits-shake.md
  .changeset/young-pigs-refuse.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:S

#1303 Include custom modes in mode switching keyboard shortcut
  .changeset/honest-queens-pump.md
  webview-ui/src/components/chat/ChatView.tsx
Labels: enhancement, size:S, lgtm

#1305 Custom max tokens fix for non-thinking models
  .changeset/fuzzy-donkeys-whisper.md
  src/api/providers/__tests__/anthropic.test.ts
  src/api/providers/__tests__/openrouter.test.ts
  src/api/providers/__tests__/vertex.test.ts
  src/api/providers/anthropic.ts
  src/api/providers/openrouter.ts
  src/api/providers/vertex.ts
Labels: size:L, lgtm

#1304 Clearer instructions for read-only modes that can run commands
  .changeset/proud-melons-appear.md
  src/core/Cline.ts
Labels: size:XS, lgtm

#1306 Changeset version bump
  .changeset/fuzzy-donkeys-whisper.md
  .changeset/honest-queens-pump.md
  .changeset/proud-melons-appear.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:S

#1307 DRY up getModel
  src/api/__tests__/index.test.ts
  src/api/index.ts
  src/api/providers/anthropic.ts
  src/api/providers/constants.ts
  src/api/providers/ollama.ts
  src/api/providers/openai.ts
  src/api/providers/openrouter.ts
  src/api/providers/vertex.ts
Labels: size:L, lgtm

#1312 Infrastructure to support calling token count APIs, starting with Anthropic
  src/api/index.ts
  src/api/providers/anthropic.ts
  src/api/providers/base-provider.ts
  src/api/providers/bedrock.ts
  src/api/providers/gemini.ts
  src/api/providers/glama.ts
  src/api/providers/lmstudio.ts
  src/api/providers/mistral.ts
  src/api/providers/ollama.ts
  src/api/providers/openai-native.ts
  src/api/providers/openai.ts
  src/api/providers/openrouter.ts
  src/api/providers/unbound.ts
  src/api/providers/vertex.ts
  src/api/providers/vscode-lm.ts
  src/core/Cline.ts
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
Labels: enhancement, size:XL, lgtm

#1325 docs: add fallback npm install:ci instructions to README
  README.md
Labels: documentation, size:XS, lgtm

#1323 Default middle-out compression to on
  .changeset/weak-cameras-hope.md
  src/api/providers/openrouter.ts
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:S, lgtm

#1331 Add a checkbox to enable/disable the browser tool
  .changeset/nervous-candles-refuse.md
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: enhancement, size:L, lgtm

#1332 fix: switch mode state
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:XS, lgtm

#1327 feat: update virtual id for extended output 128k claude
  src/api/providers/anthropic.ts
  src/shared/api.ts
Labels: enhancement, size:S, lgtm

#1338 Support 128k max tokens for openrouter and vertex thinking
  src/api/providers/__tests__/openrouter.test.ts
  src/api/providers/openrouter.ts
  src/shared/api.ts
Labels: enhancement, size:XS

#1340 Exclude MCP from system prompt if mode does not support it
  .changeset/fluffy-pumpkins-sip.md
  src/core/prompts/system.ts
Labels: enhancement, size:S, lgtm

#1341 Update the warning text for the VS LM API
  .changeset/tidy-donuts-rhyme.md
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:XS, lgtm

#1326 Changeset version bump
  .changeset/fluffy-pumpkins-sip.md
  .changeset/healthy-buckets-attack.md
  .changeset/nervous-candles-refuse.md
  .changeset/stale-toys-think.md
  .changeset/tidy-donuts-rhyme.md
  .changeset/weak-cameras-hope.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M

#1343 Update CHANGELOG.md
  CHANGELOG.md
Labels: size:S

#1319 feat(mentions): improve path handling for Windows and escaped spaces
  src/shared/__tests__/context-mentions.test.ts
  src/shared/context-mentions.ts
Labels: enhancement, size:L, lgtm

#1346 Async checkpoints
  src/core/Cline.ts
  src/services/checkpoints/CheckpointServiceFactory.ts
  src/services/checkpoints/LocalCheckpointService.ts
  src/services/checkpoints/ShadowCheckpointService.ts
  src/services/checkpoints/__tests__/LocalCheckpointService.test.ts
  src/services/checkpoints/__tests__/ShadowCheckpointService.test.ts
  src/services/checkpoints/index.ts
  src/services/checkpoints/types.ts
  webview-ui/src/components/chat/checkpoints/CheckpointSaved.tsx
  webview-ui/src/components/chat/checkpoints/schema.ts
Labels: enhancement, size:XXL, lgtm

#1348 Set Vertex maxTokens to 64000
  src/shared/api.ts
Labels: size:XS, lgtm

#1329 Custom dropdowns for mode/api profile
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/common/CaretIcon.tsx
  webview-ui/src/components/ui/__tests__/select-dropdown.test.tsx
  webview-ui/src/components/ui/index.ts
  webview-ui/src/components/ui/select-dropdown.tsx
Labels: enhancement, size:XL, lgtm

#1357 Add a repo-per-workspace checkpoint service in addition to repo-per-task
  src/core/Cline.ts
  src/services/checkpoints/RepoPerTaskCheckpointService.ts
  src/services/checkpoints/RepoPerWorkspaceCheckpointService.ts
  src/services/checkpoints/ShadowCheckpointService.ts
  src/services/checkpoints/__tests__/ShadowCheckpointService.test.ts
  src/services/checkpoints/index.ts
  src/services/checkpoints/types.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/checkpoints/CheckpointMenu.tsx
  webview-ui/src/components/history/HistoryView.tsx
Labels: enhancement, size:XL, lgtm

#1368 Adding support for Speculative Decoding for LMStudio Local Models
  src/api/providers/lmstudio.ts
  src/core/webview/ClineProvider.ts
  src/shared/api.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:L, lgtm

#1378 Fix issues with select dropdown
  webview-ui/src/components/ui/__tests__/select-dropdown.test.tsx
  webview-ui/src/components/ui/select-dropdown.tsx
Labels: bug, size:M, lgtm

#1380 Disable terminal actions for now
  package.json
  src/activate/index.ts
  src/activate/registerTerminalActions.ts
  src/extension.ts
Labels: size:L, lgtm

#1379 Checkpoint storage setting + settings view redesign
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/checkpoints.ts
  src/shared/globalState.ts
  webview-ui/src/components/common/MermaidBlock.tsx
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/history/useTaskSearch.ts
  webview-ui/src/components/mcp/McpView.tsx
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/settings/AdvancedSettings.tsx
  webview-ui/src/components/settings/ApiConfigManager.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/BrowserSettings.tsx
  webview-ui/src/components/settings/CheckpointSettings.tsx
  webview-ui/src/components/settings/ExperimentalFeature.tsx
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/components/settings/NotificationSettings.tsx
  webview-ui/src/components/settings/Section.tsx
  webview-ui/src/components/settings/SectionHeader.tsx
  webview-ui/src/components/settings/SettingsFooter.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/TemperatureControl.tsx
  webview-ui/src/components/settings/__tests__/SettingsView.test.tsx
  webview-ui/src/components/settings/styles.ts
  webview-ui/src/components/settings/types.ts
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/index.css
Labels: enhancement, size:XXL, lgtm

#1235 Feat ContextProxy to improve state management
  src/core/__tests__/contextProxy.test.ts
  src/core/contextProxy.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/shared/api.ts
  src/shared/checkExistApiConfig.ts
  src/shared/globalState.ts
Labels: enhancement, size:XXL, lgtm

#1300 feat: add x-title and http-referer header to all openai providers
  .changeset/wise-pears-join.md
  src/api/providers/__tests__/openai.test.ts
  src/api/providers/openai.ts
  src/api/providers/openrouter.ts
  src/api/providers/requesty.ts
Labels: enhancement, size:M, lgtm

#1394 Revert "Better encapsulation for API config"
  src/core/__tests__/contextProxy.test.ts
  src/core/contextProxy.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
Labels: size:L

#1267 Human relay
  src/activate/registerCommands.ts
  src/api/index.ts
  src/api/providers/human-relay.ts
  src/core/webview/ClineProvider.ts
  src/extension.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/api.ts
  webview-ui/src/App.tsx
  webview-ui/src/components/human-relay/HumanRelayDialog.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:XL, lgtm

#1315 style(task-header): add padding to align task header values
  webview-ui/src/components/chat/TaskHeader.tsx
Labels: size:XS, lgtm

#1396 feat(contextProxy): add setValue and setValues methods to simplify
  src/core/__tests__/contextProxy.test.ts
  src/core/contextProxy.ts
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:L, lgtm

#1397 fix test
  src/core/webview/__tests__/ClineProvider.test.ts
Labels: size:S

#1123 subtasks alpha version (still in development)
  src/activate/registerCommands.ts
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/exports/index.ts
  src/shared/HistoryItem.ts
  webview-ui/src/components/chat/TaskHeader.tsx
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/__tests__/HistoryView.test.tsx
Labels: enhancement, in progress, size:XL, lgtm

#1234 Supports updating multiple locations of a file in one call of the apply_diff tool
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
  src/core/diff/DiffStrategy.ts
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/core/diff/types.ts
  src/core/webview/ClineProvider.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/experiments.ts
Labels: enhancement, size:XXL, lgtm

#1401 Better UX for choosing between diff strategies
  webview-ui/src/components/settings/AdvancedSettings.tsx
  webview-ui/src/components/settings/ExperimentalSettings.tsx
Labels: enhancement, size:M

#1404 Missed a spot in ClineProvider
  src/core/webview/ClineProvider.ts
Labels: bug, size:XS

#1399 Fix settings colors for themes that use color transparency
  webview-ui/src/components/common/VSCodeButtonLink.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelDescriptionMarkdown.tsx
  webview-ui/src/components/settings/ModelInfoView.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/SectionHeader.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/TemperatureControl.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/index.css
Labels: size:XXL, lgtm

#1390 Terminal "middle-out": smart truncation for terminal output
  src/core/Cline.ts
  src/core/mentions/index.ts
  src/core/webview/ClineProvider.ts
  src/integrations/misc/__tests__/extract-text.test.ts
  src/integrations/misc/extract-text.ts
  src/integrations/terminal/OutputBuilder.ts
  src/integrations/terminal/TerminalManager.ts
  src/integrations/terminal/TerminalProcess.ts
  src/integrations/terminal/__tests__/OutputBuilder.test.ts
  src/integrations/terminal/__tests__/TerminalProcess.test.ts
  src/integrations/terminal/__tests__/mergePromise.test.ts
  src/integrations/terminal/getLatestTerminalOutput.ts
  src/integrations/terminal/mergePromise.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  src/shared/terminal.ts
  src/utils/git.ts
  webview-ui/src/components/settings/AdvancedSettings.tsx
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: enhancement, size:XXL, lgtm

#1414 Adds Unbound metadata for non-streaming requests
  src/api/providers/__tests__/unbound.test.ts
  src/api/providers/unbound.ts
Labels: enhancement, size:S, lgtm

#1415 fix reset all state
  src/core/__tests__/contextProxy.test.ts
  src/core/contextProxy.ts
  src/core/webview/ClineProvider.ts
Labels: bug, size:L, lgtm

#1416 Handle outputless commands
  .changeset/wise-bats-perform.md
  src/core/Cline.ts
  src/integrations/terminal/TerminalProcess.ts
  src/integrations/terminal/__tests__/TerminalProcess.test.ts
Labels: bug, size:L, lgtm

#1417 Remove item number from history preview cards
  .changeset/shiny-mugs-care.md
  webview-ui/src/components/history/HistoryPreview.tsx
Labels: enhancement, size:S, lgtm

#1421 Remove (Main) from task header
  webview-ui/src/components/chat/TaskHeader.tsx
Labels: size:XS, lgtm

#1425 Update README.md
  README.md
Labels: size:XS

#1420 Improve file excludes for checkpoints service
  src/services/checkpoints/ShadowCheckpointService.ts
  src/services/checkpoints/__tests__/ShadowCheckpointService.test.ts
  src/services/checkpoints/__tests__/excludes.test.ts
  src/services/checkpoints/constants.ts
  src/services/checkpoints/excludes.ts
Labels: enhancement, size:XL, lgtm

#1392 Add credentials auth for Google vertex
  .changeset/tame-carpets-bake.md
  src/api/providers/vertex.ts
  src/shared/api.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:M, lgtm

#1429 Choose the correct checkpoint storage strategy when resuming tasks
  src/core/webview/ClineProvider.ts
  src/services/checkpoints/RepoPerWorkspaceCheckpointService.ts
  src/services/checkpoints/ShadowCheckpointService.ts
  src/services/checkpoints/__tests__/ShadowCheckpointService.test.ts
Labels: enhancement, size:L, lgtm

#1436 Turn off ellipsis quiet mode
  ellipsis.yaml
Labels: size:XS

#1439 Revert "Turn off ellipsis quiet mode"
  ellipsis.yaml
Labels: size:XS

#1435 Theoretical handling of stream non-availability or delayed availability
  src/integrations/terminal/TerminalManager.ts
  src/integrations/terminal/TerminalProcess.ts
Labels: bug, size:L, lgtm

#1438 Opt-in telemetry
  .env.sample
  .github/workflows/marketplace-publish.yml
  .gitignore
  .rooignore
  .vscodeignore
  PRIVACY.md
  package-lock.json
  package.json
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/extension.ts
  src/services/telemetry/TelemetryService.ts
  src/shared/ExtensionMessage.ts
  src/shared/TelemetrySetting.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/App.tsx
  webview-ui/src/__mocks__/posthog-js.ts
  webview-ui/src/__tests__/TelemetryClient.test.ts
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/common/TelemetryBanner.tsx
  webview-ui/src/components/settings/SettingsFooter.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/utils/TelemetryClient.ts
  webview-ui/src/utils/__tests__/TelemetryClient.test.ts
Labels: enhancement, size:XL, lgtm

#1448 fix: adjust font size of code elements within headings to ensure cons…
  webview-ui/src/components/common/MarkdownBlock.tsx
Labels: bug, size:XS, lgtm

#1452 UI tweaks to task header
  webview-ui/src/components/chat/TaskHeader.tsx
Labels: enhancement, size:S

#1454 Disable repo per workspace checkpoints
  .changeset/nine-cameras-applaud.md
  src/core/Cline.ts
  webview-ui/src/components/settings/CheckpointSettings.tsx
Labels: size:M, lgtm

#1459 v3.8
  .changeset/young-wolves-add.md
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/chat/Announcement.tsx
Labels: size:M

#1395 Changeset version bump
  .changeset/nine-cameras-applaud.md
  .changeset/shiny-mugs-care.md
  .changeset/tame-carpets-bake.md
  .changeset/wise-bats-perform.md
  .changeset/wise-pears-join.md
  .changeset/young-wolves-add.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:M

#1458 Show the reserved output tokens in the context window bar
  webview-ui/src/__mocks__/components/chat/TaskHeader.tsx
  webview-ui/src/__tests__/ContextWindowProgress.test.tsx
  webview-ui/src/__tests__/ContextWindowProgressLogic.test.ts
  webview-ui/src/__tests__/getMaxTokensForModel.test.tsx
  webview-ui/src/components/chat/TaskHeader.tsx
  webview-ui/src/utils/model-utils.ts
Labels: enhancement, size:XL, lgtm

#1457 Use full width for Configuration Profile dropdown
  webview-ui/src/components/settings/ApiConfigManager.tsx
Labels: enhancement, size:XS, lgtm

#1466 Update .clinerules
  .clinerules
Labels: size:S

#1467 Add app version to telemetry
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:S, lgtm

#1468 Fix: Custom temperature cannot be unchecked
  src/shared/api.ts
  webview-ui/src/components/settings/TemperatureControl.tsx
  webview-ui/src/components/settings/__tests__/TemperatureControl.test.tsx
Labels: bug, size:S, lgtm

#1464 Fix: Input/output prices are parsed too early
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: bug, size:XS, lgtm

#1444 fix claude 3.7 think enhance prompt problem.
  src/api/providers/anthropic.ts
Labels: bug, size:XS, lgtm

#1476 Fix logic for default modelMaxTokens for thinking models
  src/core/Cline.ts
  webview-ui/package-lock.json
  webview-ui/src/__tests__/getMaxTokensForModel.test.tsx
  webview-ui/src/utils/__tests__/model-utils.test.ts
  webview-ui/src/utils/model-utils.ts
Labels: bug, size:L, lgtm

#1479 Turn checkpoints on by default
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:XS, lgtm

#1480 v3.8.1
  .changeset/red-meals-report.md
Labels: size:XS

#1481 Changeset version bump
  .changeset/red-meals-report.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1484 Fix settings dropdown issues
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/components/ui/index.ts
  webview-ui/src/components/ui/select.tsx
Labels: bug, size:L, lgtm

#1486 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, size:M

#1489 Add o3-mini support to openai compatible
  .changeset/wild-dragons-leave.md
  src/api/providers/openai.ts
Labels: bug, size:M, lgtm

#1500 Strip BOM twice when applying diffs
  jest.config.js
  package-lock.json
  package.json
  src/__mocks__/strip-bom.js
  src/integrations/editor/DiffViewProvider.ts
Labels: bug, size:S, lgtm

#1501 Strip all BOMs
  src/integrations/editor/DiffViewProvider.ts
Labels: size:S

#1491 Sbc subtasks approve button
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: enhancement, size:L, lgtm

#1494 support tool progress status
  src/core/Cline.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/core/diff/types.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/common/CodeAccordian.tsx
Labels: enhancement, size:M, lgtm

#1505 V3.8.2
  .changeset/modern-pillows-visit.md
  src/core/Cline.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/core/webview/ClineProvider.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/common/CodeAccordian.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: enhancement, size:L, lgtm

#1502 Changeset version bump
  .changeset/modern-pillows-visit.md
  .changeset/wild-dragons-leave.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:S

#1511 Fix the VSCode LM model picker
  .changeset/eleven-birds-doubt.md
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: size:M

#1512 Changeset version bump
  .changeset/eleven-birds-doubt.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1518 Revert tool progress for now
  .changeset/empty-bees-suffer.md
  src/core/Cline.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/core/diff/types.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/common/CodeAccordian.tsx
Labels: bug, size:M, lgtm

#1507 feat: Add toggle for custom mode creation
  src/core/prompts/sections/modes.ts
  src/core/webview/ClineProvider.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: enhancement, in progress, size:M, lgtm

#1522 v3.8.4
  .changeset/sixty-ants-begin.md
Labels: size:XS

#1519 Changeset version bump
  .changeset/empty-bees-suffer.md
  .changeset/sixty-ants-begin.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#996 Reduce the probability of errors when the model tries to fix the problems
  src/core/mentions/index.ts
  src/integrations/diagnostics/index.ts
  src/integrations/editor/DiffViewProvider.ts
Labels: lgtm

#721 feat: Add Kotlin support in list_code_definition_names
  esbuild.js
  src/services/tree-sitter/__tests__/index.test.ts
  src/services/tree-sitter/__tests__/languageParser.test.ts
  src/services/tree-sitter/index.ts
  src/services/tree-sitter/languageParser.ts
  src/services/tree-sitter/queries/index.ts
  src/services/tree-sitter/queries/kotlin.ts
Labels: lgtm

#573 Do not exclude whole project dir when listing in case where project i…
  src/services/glob/list-files.ts
Labels: lgtm

#1516 App tab layout fixes
  .changeset/lemon-bulldogs-unite.md
  .env.sample
  webview-ui/src/App.tsx
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/checkpoints/CheckpointMenu.tsx
  webview-ui/src/components/common/Alert.tsx
  webview-ui/src/components/common/Tab.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/mcp/McpView.tsx
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/ui/dropdown-menu.tsx
  webview-ui/src/components/ui/hooks/index.ts
  webview-ui/src/components/ui/hooks/useRooPortal.ts
  webview-ui/src/components/ui/popover.tsx
  webview-ui/src/components/ui/select-dropdown.tsx
  webview-ui/src/components/ui/select.tsx
  webview-ui/src/components/welcome/WelcomeView.tsx
  webview-ui/src/index.css
Labels: enhancement, size:L, lgtm

#1524 Add telemetry for checkpoint save/restore/diff
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/services/telemetry/TelemetryService.ts
Labels: enhancement, size:M, lgtm

#1451 Add openai style cost calculation
  src/api/providers/__tests__/requesty.test.ts
  src/api/providers/openai.ts
  src/api/providers/requesty.ts
  src/api/providers/vscode-lm.ts
  src/core/Cline.ts
  src/utils/__tests__/cost.test.ts
  src/utils/cost.ts
Labels: enhancement, size:L, lgtm

#1556 fix browser system prompt inclusion rules
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
Labels: bug, size:L, lgtm

#1545 Follow the established pattern for command registration
  README.md
  src/activate/humanRelay.ts
  src/activate/registerCommands.ts
  src/extension.ts
Labels: enhancement, size:L, lgtm

#1552 fix: update MCP servers directory path for platform compatibility
  src/core/webview/ClineProvider.ts
Labels: size:S, lgtm

#1550 Users need the ability to use custom ARNs (Amazon Resource Names) with AWS Bedrock for intelligent prompt routing.
  src/api/providers/__tests__/bedrock-custom-arn.test.ts
  src/api/providers/__tests__/bedrock.test.ts
  src/api/providers/bedrock.ts
  src/shared/api.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/utils/validate.ts
Labels: enhancement, size:XL, lgtm

#1560 refactor alert dialog styles, use vscode theme
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/ui/alert-dialog.tsx
Labels: enhancement, size:M, lgtm

#1558 Fix usage tracking for SiliconFlow etc
  .changeset/tidy-queens-pay.md
  src/api/providers/__tests__/openai-usage-tracking.test.ts
  src/api/providers/openai.ts
Labels: bug, size:L, lgtm

#1546 Rename ClineAPI to RooCodeAPI and improve types
  .eslintrc.json
  e2e/VSCODE_INTEGRATION_TESTS.md
  e2e/src/suite/index.ts
  e2e/tsconfig.json
  src/activate/createRooCodeAPI.ts
  src/activate/index.ts
  src/exports/README.md
  src/exports/roo-code.d.ts
  src/extension.ts
  src/shared/ExtensionMessage.ts
Labels: enhancement, size:L, lgtm

#1526 Fix progress status
  src/core/Cline.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/core/diff/types.ts
  src/exports/roo-code.d.ts
  src/shared/ExtensionMessage.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/common/CodeAccordian.tsx
Labels: bug, size:M, lgtm

#1543 add gemini-2.0-pro-exp-02-05 model to vertex
  src/shared/api.ts
Labels: enhancement, size:XS, lgtm

#1572 Use baseURL in OpenRouter generation check
  src/api/providers/openrouter.ts
Labels: size:XS, lgtm

#1564 fix: Preserve parent-child relationship when cancelling subtasks
  e2e/src/suite/task.test.ts
  src/core/webview/ClineProvider.ts
Labels: bug, size:L, lgtm

#1365 refactor terminal architecture to address critical issues with the current design
  package.json
  src/activate/index.ts
  src/activate/registerTerminalActions.ts
  src/core/Cline.ts
  src/core/assistant-message/index.ts
  src/core/mentions/index.ts
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/tools/execute-command.ts
  src/core/webview/ClineProvider.ts
  src/extension.ts
  src/integrations/misc/__tests__/extract-text.test.ts
  src/integrations/misc/extract-text.ts
  src/integrations/terminal/OutputBuilder.ts
  src/integrations/terminal/Terminal.ts
  src/integrations/terminal/TerminalManager.ts
  src/integrations/terminal/TerminalProcess.ts
  src/integrations/terminal/TerminalRegistry.ts
  src/integrations/terminal/__tests__/OutputBuilder.test.ts
  src/integrations/terminal/__tests__/TerminalProcess.test.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.test.ts
  src/integrations/terminal/__tests__/TerminalProcessInterpretExitCode.test.ts
  src/integrations/terminal/__tests__/mergePromise.test.ts
  src/integrations/terminal/get-latest-output.ts
  src/integrations/terminal/mergePromise.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  src/shared/terminal.ts
  src/utils/git.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/settings/AdvancedSettings.tsx
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
Labels: bug, size:XXL, lgtm

#1583 Fix MarkdownBlock text color for Dark High Contrast theme
  webview-ui/src/components/common/MarkdownBlock.tsx
Labels: bug, size:S, lgtm

#1586 Fix terminal process unit tests on MacOS
  src/integrations/terminal/__tests__/TerminalProcessExec.test.ts
Labels: bug, size:M

#1579 ContextProxy fix - constructor should not be async
  .changeset/seven-apricots-watch.md
  .github/workflows/code-qa.yml
  .gitignore
  e2e/.env.local.sample
  e2e/VSCODE_INTEGRATION_TESTS.md
  e2e/package.json
  e2e/src/suite/index.ts
  e2e/src/suite/modes.test.ts
  e2e/src/suite/subtasks.test.ts
  e2e/src/suite/task.test.ts
  e2e/src/suite/utils.ts
  knip.json
  src/activate/createRooCodeAPI.ts
  src/api/providers/openrouter.ts
  src/core/__tests__/contextProxy.test.ts
  src/core/contextProxy.ts
  src/core/prompts/sections/modes.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/exports/README.md
  src/exports/roo-code.d.ts
  src/shared/ExtensionMessage.ts
  src/shared/globalState.ts
Labels: bug, size:XXL, lgtm

#1590 Add Deepseek R1 On-Demand to Bedrock
  src/shared/api.ts
Labels: enhancement, size:XS, lgtm

#1584 I18n
  .roomodes
  src/__mocks__/vscode.js
  src/core/Cline.ts
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/__tests__/custom-system-prompt.test.ts
  src/core/prompts/__tests__/sections.test.ts
  src/core/prompts/__tests__/system.test.ts
  src/core/prompts/sections/__tests__/custom-instructions.test.ts
  src/core/prompts/sections/custom-instructions.ts
  src/core/prompts/system.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/exports/roo-code.d.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/__tests__/language.test.ts
  src/shared/__tests__/modes.test.ts
  src/shared/globalState.ts
  src/shared/language.ts
  src/shared/modes.ts
  webview-ui/.gitignore
  webview-ui/jest.config.cjs
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/App.tsx
  webview-ui/src/__mocks__/i18n/TranslationContext.tsx
  webview-ui/src/__mocks__/i18n/setup.ts
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/ui/combobox-primitive.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/i18n/TranslationContext.tsx
  webview-ui/src/i18n/__tests__/TranslationContext.test.tsx
  webview-ui/src/i18n/locales/ar/.gitkeep
  webview-ui/src/i18n/locales/ca/.gitkeep
  webview-ui/src/i18n/locales/cs/.gitkeep
  webview-ui/src/i18n/locales/de/.gitkeep
  webview-ui/src/i18n/locales/en/.gitkeep
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/.gitkeep
  webview-ui/src/i18n/locales/fr/.gitkeep
  webview-ui/src/i18n/locales/hi/.gitkeep
  webview-ui/src/i18n/locales/hu/.gitkeep
  webview-ui/src/i18n/locales/it/.gitkeep
  webview-ui/src/i18n/locales/ja/.gitkeep
  webview-ui/src/i18n/locales/ko/.gitkeep
  webview-ui/src/i18n/locales/pl/.gitkeep
  webview-ui/src/i18n/locales/pt-BR/.gitkeep
  webview-ui/src/i18n/locales/pt/.gitkeep
  webview-ui/src/i18n/locales/ru/.gitkeep
  webview-ui/src/i18n/locales/tr/.gitkeep
  webview-ui/src/i18n/locales/zh-CN/.gitkeep
  webview-ui/src/i18n/locales/zh-TW/.gitkeep
  webview-ui/src/i18n/setup.ts
  webview-ui/src/i18n/test-utils.ts
Labels: enhancement, size:XL, lgtm

#1585 fix: add PowerShell-specific command handling
  src/integrations/terminal/Terminal.ts
  src/integrations/terminal/TerminalProcess.ts
  src/integrations/terminal/__tests__/TerminalProcess.test.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.test.ts
Labels: bug, size:S, lgtm

#1495 feat: add sse mcp support
  esbuild.js
  package-lock.json
  package.json
  src/__mocks__/@modelcontextprotocol/sdk/client/sse.js
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/__tests__/system.test.ts
  src/core/prompts/sections/mcp-servers.ts
  src/services/mcp/McpHub.ts
  src/services/mcp/__tests__/McpHub.test.ts
Labels: enhancement, size:L, lgtm

#1534 support custom base url for gemini in google AI studio
  src/api/providers/__tests__/gemini.test.ts
  src/api/providers/gemini.ts
  src/exports/roo-code.d.ts
  src/shared/api.ts
  src/shared/globalState.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:M, lgtm

#1599 Add diffStrategy name to telemetry
  src/core/diff/strategies/multi-search-replace.ts
  src/core/diff/strategies/new-unified/index.ts
  src/core/diff/strategies/search-replace.ts
  src/core/diff/strategies/unified.ts
  src/core/diff/types.ts
  src/core/prompts/__tests__/sections.test.ts
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:S, lgtm

#1603 Fix more hard-coded openrouter urls
  src/api/providers/openrouter.ts
  src/core/webview/ClineProvider.ts
Labels: size:S, lgtm

#1611 v3.8.5
  .changeset/strange-guests-divide.md
Labels: size:XS

#1527 Changeset version bump
  .changeset/automatic-tags-publish.md
  .changeset/lemon-bulldogs-unite.md
  .changeset/seven-apricots-watch.md
  .changeset/strange-guests-divide.md
  .changeset/thin-fans-deliver.md
  .changeset/tidy-queens-pay.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M

#1617 Fix e2e tests
  e2e/src/suite/modes.test.ts
  e2e/src/suite/subtasks.test.ts
  e2e/src/suite/utils.ts
  package-lock.json
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/exports/api.ts
  src/exports/roo-code.d.ts
Labels: size:L

#1619 Update git config for marketplace publish
  .github/workflows/marketplace-publish.yml
Labels: enhancement, size:XS

#1620 Revert "feat: add sse mcp support"
  .changeset/loud-bugs-hope.md
  esbuild.js
  package-lock.json
  package.json
  src/__mocks__/@modelcontextprotocol/sdk/client/sse.js
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/__tests__/system.test.ts
  src/core/prompts/sections/mcp-servers.ts
  src/services/mcp/McpHub.ts
  src/services/mcp/__tests__/McpHub.test.ts
Labels: size:L, lgtm

#1621 Changeset version bump
  .changeset/loud-bugs-hope.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#1622 Fix 'See less' style
  webview-ui/src/components/chat/TaskHeader.tsx
Labels: size:XS, lgtm

#1604 Cost display updating for Bedrock custom ARNs that are prompt routers
  src/api/providers/__tests__/bedrock-invokedModelId.test.ts
  src/api/providers/__tests__/bedrock.test.ts
  src/api/providers/bedrock.ts
  src/shared/api.ts
Labels: bug, size:XL, lgtm

#1630 Contributors
  .github/workflows/update-contributors.yml
  README.md
  package.json
  scripts/update-contributors.js
Labels: documentation, size:L

#1632 Open a PR to update contributors
  .github/workflows/update-contributors.yml
Labels: size:S

#1633 Better git logic for updating contributors in readme
  .github/workflows/update-contributors.yml
Labels: documentation, size:S

#1634 Use create pull request action more
  .github/workflows/update-contributors.yml
Labels: enhancement, size:S

#1635 Run prettier before checking for contributor changes
  .github/workflows/update-contributors.yml
Labels: enhancement, size:XS

#1636 Only set width on contributor images
  README.md
  scripts/update-contributors.js
Labels: documentation, size:M

#1637 Update update-contributors.js
  scripts/update-contributors.js
Labels: size:XS

#1638 Disable husky when updating contributors
  .github/workflows/update-contributors.yml
Labels: size:XS, lgtm

#1639 Update update-contributors.yml
  .github/workflows/update-contributors.yml
Labels: size:XS

#1647 refactor(i18n): enhance welcome page text for internationalization
  webview-ui/src/components/welcome/WelcomeView.tsx
  webview-ui/src/i18n/locales/ar/welcome.json
  webview-ui/src/i18n/locales/ca/welcome.json
  webview-ui/src/i18n/locales/cs/welcome.json
  webview-ui/src/i18n/locales/de/welcome.json
  webview-ui/src/i18n/locales/en/welcome.json
  webview-ui/src/i18n/locales/es/welcome.json
  webview-ui/src/i18n/locales/fr/welcome.json
  webview-ui/src/i18n/locales/hi/welcome.json
  webview-ui/src/i18n/locales/hu/welcome.json
  webview-ui/src/i18n/locales/it/welcome.json
  webview-ui/src/i18n/locales/ja/welcome.json
  webview-ui/src/i18n/locales/ko/welcome.json
  webview-ui/src/i18n/locales/pl/welcome.json
  webview-ui/src/i18n/locales/pt-BR/welcome.json
  webview-ui/src/i18n/locales/pt/welcome.json
  webview-ui/src/i18n/locales/ru/welcome.json
  webview-ui/src/i18n/locales/tr/welcome.json
  webview-ui/src/i18n/locales/zh-CN/welcome.json
  webview-ui/src/i18n/locales/zh-TW/welcome.json
Labels: enhancement, size:L, lgtm

#1650 Context management
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/exports/roo-code.d.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/globalState.ts
  webview-ui/src/__mocks__/lucide-react.ts
  webview-ui/src/components/settings/AdvancedSettings.tsx
  webview-ui/src/components/settings/ContextManagementSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/__tests__/ContextManagementSettings.test.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
Labels: enhancement, size:L, lgtm

#1652 Contributor guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation, size:L

#1677 update the readme discord link was broken on the bottom fixed
  README.md
Labels: documentation, size:XS, lgtm

#1676 refactor(i18n): Internationalization of Button and tooltip in ChatView
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/common/TelemetryBanner.tsx
  webview-ui/src/i18n/locales/ar/chat.json
  webview-ui/src/i18n/locales/ar/common.json
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/ca/common.json
  webview-ui/src/i18n/locales/cs/chat.json
  webview-ui/src/i18n/locales/cs/common.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/de/common.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/common.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/es/common.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/fr/common.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hi/common.json
  webview-ui/src/i18n/locales/hu/chat.json
  webview-ui/src/i18n/locales/hu/common.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/it/common.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ja/common.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/ko/common.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pl/common.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt-BR/common.json
  webview-ui/src/i18n/locales/pt/chat.json
  webview-ui/src/i18n/locales/pt/common.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/ru/common.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/tr/common.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-CN/common.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/common.json
Labels: enhancement, size:XXL

#1684 Fix paren in i18n
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/i18n/locales/ar/chat.json
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/cs/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hu/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:M

#1686 Fix getWorkspaceProblems to use an await
  src/core/mentions/index.ts
Labels: bug, size:XS

#1688 i18n for chattextarea
  .roomodes
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/i18n/locales/ar/chat.json
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/cs/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hu/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:L

#1689 Translate history preview and view
  .roomodes
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/history/CopyButton.tsx
  webview-ui/src/components/history/DeleteTaskDialog.tsx
  webview-ui/src/components/history/ExportButton.tsx
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/history/__tests__/HistoryView.test.tsx
  webview-ui/src/i18n/__mocks__/TranslationContext.tsx
  webview-ui/src/i18n/locales/ar/history.json
  webview-ui/src/i18n/locales/ca/history.json
  webview-ui/src/i18n/locales/cs/history.json
  webview-ui/src/i18n/locales/de/history.json
  webview-ui/src/i18n/locales/en/history.json
  webview-ui/src/i18n/locales/es/history.json
  webview-ui/src/i18n/locales/fr/history.json
  webview-ui/src/i18n/locales/hi/history.json
  webview-ui/src/i18n/locales/hu/history.json
  webview-ui/src/i18n/locales/it/history.json
  webview-ui/src/i18n/locales/ja/history.json
  webview-ui/src/i18n/locales/ko/history.json
  webview-ui/src/i18n/locales/pl/history.json
  webview-ui/src/i18n/locales/pt-BR/history.json
  webview-ui/src/i18n/locales/pt/history.json
  webview-ui/src/i18n/locales/ru/history.json
  webview-ui/src/i18n/locales/tr/history.json
  webview-ui/src/i18n/locales/zh-CN/history.json
  webview-ui/src/i18n/locales/zh-TW/history.json
Labels: enhancement, size:XL, lgtm

#1690 Localize the auto-approve menu
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/i18n/locales/ar/chat.json
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/cs/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hu/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:XL, lgtm

#1691 Localize the prompts tab
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/i18n/locales/ar/prompts.json
  webview-ui/src/i18n/locales/ca/prompts.json
  webview-ui/src/i18n/locales/cs/prompts.json
  webview-ui/src/i18n/locales/de/prompts.json
  webview-ui/src/i18n/locales/en/prompts.json
  webview-ui/src/i18n/locales/es/prompts.json
  webview-ui/src/i18n/locales/fr/prompts.json
  webview-ui/src/i18n/locales/hi/prompts.json
  webview-ui/src/i18n/locales/hu/prompts.json
  webview-ui/src/i18n/locales/it/prompts.json
  webview-ui/src/i18n/locales/ja/prompts.json
  webview-ui/src/i18n/locales/ko/prompts.json
  webview-ui/src/i18n/locales/pl/prompts.json
  webview-ui/src/i18n/locales/pt-BR/prompts.json
  webview-ui/src/i18n/locales/pt/prompts.json
  webview-ui/src/i18n/locales/ru/prompts.json
  webview-ui/src/i18n/locales/tr/prompts.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
Labels: enhancement, size:XXL
