Repository RooCodeInc/Roo-Code, pull requests merged in 2025-05, with the labels that each got.

#3081 fix the built boomerang orchestrator mode to bring in line with origi…
  src/shared/modes.ts
Labels: bug, size:XS, lgtm

#3066 feat(openai): Add Config Option to Overwrite OpenAI's API Base
  evals/packages/types/src/roo-code.ts
  src/api/providers/openai-native.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:M, lgtm

#3084 Fix padding problem in #2965
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:XS, lgtm

#3095 Show 'None' when a mode has no tool groups
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/i18n/locales/ca/prompts.json
  webview-ui/src/i18n/locales/de/prompts.json
  webview-ui/src/i18n/locales/en/prompts.json
  webview-ui/src/i18n/locales/es/prompts.json
  webview-ui/src/i18n/locales/fr/prompts.json
  webview-ui/src/i18n/locales/hi/prompts.json
  webview-ui/src/i18n/locales/it/prompts.json
  webview-ui/src/i18n/locales/ja/prompts.json
  webview-ui/src/i18n/locales/ko/prompts.json
  webview-ui/src/i18n/locales/pl/prompts.json
  webview-ui/src/i18n/locales/pt-BR/prompts.json
  webview-ui/src/i18n/locales/ru/prompts.json
  webview-ui/src/i18n/locales/tr/prompts.json
  webview-ui/src/i18n/locales/vi/prompts.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
Labels: enhancement, size:M

#2747 refactor(chat): show inline code more subtle
  webview-ui/src/components/common/MarkdownBlock.tsx
Labels: enhancement, size:XS, lgtm

#3069 Sync evals types
  evals/package.json
  evals/packages/types/src/roo-code-defaults.ts
  evals/packages/types/src/roo-code.ts
  evals/pnpm-lock.yaml
  src/schemas/index.ts
Labels: size:L

#3076 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, size:XS

#3108 Telemetry for title button clicks
  src/activate/registerCommands.ts
  src/services/telemetry/TelemetryService.ts
Labels: enhancement, size:S, lgtm

#3056 Customizable headers for the OpenAI-compatible provider
  src/api/providers/openai.ts
  src/core/config/ContextProxy.ts
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm

#2969 Fix: ChatTextArea's height moving unexcepted when Roo Code width change
  webview-ui/src/components/chat/ChatTextArea.tsx
Labels: bug, size:XS, lgtm

#3113 Remove flaky tiktoken test
  src/utils/__tests__/tiktoken.test.ts
Labels: size:S, lgtm

#3112 Handle Mermaid validation errors
  webview-ui/src/components/common/MermaidBlock.tsx
  webview-ui/src/i18n/locales/ca/common.json
  webview-ui/src/i18n/locales/de/common.json
  webview-ui/src/i18n/locales/en/common.json
  webview-ui/src/i18n/locales/es/common.json
  webview-ui/src/i18n/locales/fr/common.json
  webview-ui/src/i18n/locales/hi/common.json
  webview-ui/src/i18n/locales/it/common.json
  webview-ui/src/i18n/locales/ja/common.json
  webview-ui/src/i18n/locales/ko/common.json
  webview-ui/src/i18n/locales/pl/common.json
  webview-ui/src/i18n/locales/pt-BR/common.json
  webview-ui/src/i18n/locales/ru/common.json
  webview-ui/src/i18n/locales/tr/common.json
  webview-ui/src/i18n/locales/vi/common.json
  webview-ui/src/i18n/locales/zh-CN/common.json
  webview-ui/src/i18n/locales/zh-TW/common.json
Labels: size:L, lgtm

#3120 Copy both error message and content on mermaid error
  webview-ui/src/components/common/MermaidBlock.tsx
Labels: size:XS

#3098 Changeset version bump
  .changeset/spicy-tips-fail.md
  .changeset/v3.15.2.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3125 Updates `terminal.zshOhMy` description
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: documentation, size:M, lgtm

#3130 Update default settings for evals
  evals/packages/types/src/roo-code-defaults.ts
  evals/packages/types/src/roo-code.ts
Labels: size:M

#3124 More command execution improvements
  src/core/tools/executeCommandTool.ts
  webview-ui/src/components/chat/CommandExecution.tsx
  webview-ui/src/components/chat/CommandExecutionError.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L

#3123 Improve performance of CustomModesManager
  src/core/config/CustomModesManager.ts
  src/core/config/__tests__/CustomModesManager.test.ts
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:L

#3096 Gemini caching fixes
  src/api/providers/anthropic-vertex.ts
  src/api/providers/glama.ts
  src/api/providers/openrouter.ts
  src/api/providers/unbound.ts
  src/api/transform/caching.ts
  src/api/transform/caching/__tests__/anthropic.test.ts
  src/api/transform/caching/__tests__/gemini.test.ts
  src/api/transform/caching/__tests__/vertex.test.ts
  src/api/transform/caching/anthropic.ts
  src/api/transform/caching/gemini.ts
  src/api/transform/caching/vertex.ts
  src/api/transform/vertex-caching.ts
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
Labels: size:XL, lgtm

#3133 v3.15.3
  .changeset/famous-jars-dance.md
Labels: size:XS

#3136 More robust process killing
  .changeset/great-sheep-speak.md
  package-lock.json
  package.json
  src/core/tools/executeCommandTool.ts
  src/integrations/terminal/ExecaTerminalProcess.ts
Labels: enhancement, size:M

#3139 Fix empty command bug
  .changeset/chilled-books-relate.md
  webview-ui/src/components/chat/CommandExecution.tsx
Labels: bug, size:S

#3134 Changeset version bump
  .changeset/chilled-books-relate.md
  .changeset/famous-jars-dance.md
  .changeset/great-sheep-speak.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3141 Add isSubtask to telemetry
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:XS, lgtm

#3142 Gemini caching tweaks
  .changeset/tiny-mugs-give.md
  src/api/providers/__tests__/gemini.test.ts
  src/api/providers/gemini.ts
Labels: enhancement, size:XL, lgtm

#3150 Remove help button from title bar
  package.json
  src/activate/registerCommands.ts
Labels: size:S

#3156 Fix issues with subtasks attempting completion along with commands
  .changeset/dull-flowers-trade.md
  src/core/Cline.ts
  src/core/tools/attemptCompletionTool.ts
  src/core/tools/executeCommandTool.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/CommandExecution.tsx
Labels: bug, size:M, lgtm

#3149 Changeset version bump
  .changeset/dull-flowers-trade.md
  .changeset/tiny-mugs-give.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S, lgtm

#3166 Update @google/genai package
  .changeset/lovely-nails-fly.md
  package-lock.json
  package.json
Labels: size:XS

#3135 perf: optimize code block rendering performance
  webview-ui/src/components/common/CodeBlock.tsx
Labels: enhancement, size:M, lgtm

#3167 Changeset version bump
  .changeset/lovely-nails-fly.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3172 Add support for tests that use ESM libraries
  .github/workflows/code-qa.yml
  package-lock.json
  package.json
  scripts/run-tests.js
  src/integrations/terminal/__tests__/ExecaTerminal.spec.ts
  vitest.config.ts
Labels: enhancement, size:M

#3071 fix: migrate and persist modeApiConfigs for per-mode API profiles
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.test.ts
Labels: bug, size:S, lgtm

#3087 feat: clickable code references in model responses navigate to source lines
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/sections/index.ts
  src/core/prompts/sections/markdown-formatting.ts
  src/core/prompts/system.ts
  src/core/webview/webviewMessageHandler.ts
  src/integrations/misc/open-file.ts
  webview-ui/src/components/common/MarkdownBlock.tsx
Labels: enhancement, size:M, lgtm, UI/UX

#3078 Move environment details to a separate module, add tests
  .changeset/pretty-peaches-bake.md
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
  src/core/environment/__tests__/getEnvironmentDetails.test.ts
  src/core/environment/getEnvironmentDetails.ts
  src/services/glob/list-files.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:XL

#3145 Improve Accessibility of Auto-Approve Toggles
  webview-ui/src/components/settings/AutoApproveToggle.tsx
  webview-ui/src/components/settings/__tests__/AutoApproveToggle.test.tsx
Labels: enhancement, size:M, lgtm

#2862 feat: add VSCode terminal environment inheritance setting
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/settings/TerminalSettings.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: bug, enhancement, size:XL, lgtm

#3034 feat: Add Groq and Chutes API providers
  src/api/index.ts
  src/api/providers/__tests__/chutes.test.ts
  src/api/providers/__tests__/groq.test.ts
  src/api/providers/base-openai-compatible-provider.ts
  src/api/providers/chutes.ts
  src/api/providers/groq.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
  src/schemas/index.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: bug, enhancement, size:XL

#3196 Organize provider settings into separate components
  .changeset/five-pigs-talk.md
  src/api/providers/__tests__/chutes.test.ts
  src/api/providers/__tests__/groq.test.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/providers/Anthropic.tsx
  webview-ui/src/components/settings/providers/Bedrock.tsx
  webview-ui/src/components/settings/providers/Gemini.tsx
  webview-ui/src/components/settings/providers/LMStudio.tsx
  webview-ui/src/components/settings/providers/Ollama.tsx
  webview-ui/src/components/settings/providers/OpenAI.tsx
  webview-ui/src/components/settings/providers/OpenAICompatible.tsx
  webview-ui/src/components/settings/providers/OpenRouter.tsx
  webview-ui/src/components/settings/providers/OpenRouterBalanceDisplay.tsx
  webview-ui/src/components/settings/providers/VSCodeLM.tsx
  webview-ui/src/components/settings/providers/Vertex.tsx
  webview-ui/src/components/settings/transforms.ts
Labels: enhancement, size:XXL

#3203 Use Lucide icons and translations in the code block
  webview-ui/src/components/common/CodeBlock.tsx
  webview-ui/src/components/common/__tests__/CodeBlock.test.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L, lgtm

#3193 Requesty provider fixes
  src/api/providers/__tests__/requesty.test.ts
  src/api/providers/fetchers/cache.ts
  src/api/providers/requesty.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/WebviewMessage.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/oauth/urls.ts
Labels: bug, size:XL, lgtm

#1441 #1287 - ignore stderr of MCP servers unless it really fails to connect
  renovate.json
  webview-ui/src/components/mcp/McpView.tsx
Labels: bug, size:M, lgtm

#3201 Fix language select width calculation
  webview-ui/src/components/common/CodeBlock.tsx
Labels: bug, size:XS, lgtm

#2529 Fix/remove path lib webview
  webview-ui/src/utils/context-mentions.ts
Labels: size:XS, lgtm

#3214 chore: prepare for v3.16.0 release
  .changeset/v3.16.0.md
  README.md
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/ru/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/README.md
  package-lock.json
  package.json
  src/core/webview/ClineProvider.ts
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: documentation, size:XXL

#2987 refactor: general UI improvements
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/prompts/__tests__/PromptsView.test.tsx
  webview-ui/src/components/settings/AutoApproveSettings.tsx
  webview-ui/src/components/settings/ContextManagementSettings.tsx
  webview-ui/src/components/ui/alert-dialog.tsx
  webview-ui/src/components/ui/button.tsx
  webview-ui/src/components/ui/slider.tsx
  webview-ui/src/components/ui/textarea.tsx
  webview-ui/src/i18n/locales/ca/prompts.json
  webview-ui/src/i18n/locales/de/prompts.json
  webview-ui/src/i18n/locales/en/prompts.json
  webview-ui/src/i18n/locales/es/prompts.json
  webview-ui/src/i18n/locales/fr/prompts.json
  webview-ui/src/i18n/locales/hi/prompts.json
  webview-ui/src/i18n/locales/it/prompts.json
  webview-ui/src/i18n/locales/ja/prompts.json
  webview-ui/src/i18n/locales/ko/prompts.json
  webview-ui/src/i18n/locales/pl/prompts.json
  webview-ui/src/i18n/locales/pt-BR/prompts.json
  webview-ui/src/i18n/locales/ru/prompts.json
  webview-ui/src/i18n/locales/tr/prompts.json
  webview-ui/src/i18n/locales/vi/prompts.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
Labels: enhancement, size:XL, lgtm

#3222 Add gemini-2.5-pro-preview-05-06 model
  src/shared/api.ts
  webview-ui/src/components/settings/ModelInfoView.tsx
Labels: enhancement, size:M, lgtm

#3200 Update setup script to pull latest evals repo
  evals/scripts/setup.sh
Labels: enhancement, size:XS, lgtm

#3225 Enable Gemini prompt caching by default
  .changeset/three-rings-approve.md
  evals/packages/types/src/roo-code.ts
  src/api/providers/__tests__/gemini.test.ts
  src/api/providers/gemini.ts
  src/api/providers/openrouter.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/settings/PromptCachingControl.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:M

#3188 Changeset version bump
  .changeset/five-pigs-talk.md
  .changeset/pretty-peaches-bake.md
  .changeset/three-rings-approve.md
  .changeset/v3.16.0.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M, lgtm

#3229 Add editor name to telemetry
  .changeset/brave-pigs-judge.md
  src/core/webview/ClineProvider.ts
Labels: enhancement, size:XS

#3231 Add Dutch localization files
  .roo/rules-translate/001-general-rules.md
  README.md
  evals/packages/types/src/roo-code.ts
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/nl/CODE_OF_CONDUCT.md
  locales/nl/CONTRIBUTING.md
  locales/nl/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/ru/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/README.md
  package.nls.nl.json
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/i18n/locales/nl/common.json
  src/i18n/locales/nl/tools.json
  src/schemas/index.ts
  src/shared/language.ts
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/nl/common.json
  webview-ui/src/i18n/locales/nl/history.json
  webview-ui/src/i18n/locales/nl/humanRelay.json
  webview-ui/src/i18n/locales/nl/mcp.json
  webview-ui/src/i18n/locales/nl/prompts.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/nl/welcome.json
Labels: documentation, size:XL

#3234 fix: wrap footer buttons in About section on narrow screens
  webview-ui/src/components/settings/About.tsx
Labels: size:S, lgtm

#3246 feat: Revamp contribution process and templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  CONTRIBUTING.md
  locales/ca/CODE_OF_CONDUCT.md
  locales/ca/CONTRIBUTING.md
  locales/de/CODE_OF_CONDUCT.md
  locales/de/CONTRIBUTING.md
  locales/es/CODE_OF_CONDUCT.md
  locales/es/CONTRIBUTING.md
  locales/fr/CODE_OF_CONDUCT.md
  locales/fr/CONTRIBUTING.md
  locales/hi/CODE_OF_CONDUCT.md
  locales/hi/CONTRIBUTING.md
  locales/it/CODE_OF_CONDUCT.md
  locales/it/CONTRIBUTING.md
  locales/ja/CODE_OF_CONDUCT.md
  locales/ja/CONTRIBUTING.md
  locales/ko/CODE_OF_CONDUCT.md
  locales/ko/CONTRIBUTING.md
  locales/nl/CODE_OF_CONDUCT.md
  locales/nl/CONTRIBUTING.md
  locales/pl/CODE_OF_CONDUCT.md
  locales/pl/CONTRIBUTING.md
  locales/pt-BR/CODE_OF_CONDUCT.md
  locales/pt-BR/CONTRIBUTING.md
  locales/ru/CODE_OF_CONDUCT.md
  locales/ru/CONTRIBUTING.md
  locales/tr/CODE_OF_CONDUCT.md
  locales/tr/CONTRIBUTING.md
  locales/vi/CODE_OF_CONDUCT.md
  locales/vi/CONTRIBUTING.md
  locales/zh-CN/CODE_OF_CONDUCT.md
  locales/zh-CN/CONTRIBUTING.md
  locales/zh-TW/CODE_OF_CONDUCT.md
  locales/zh-TW/CONTRIBUTING.md
Labels: documentation, enhancement, size:XXL, lgtm

#3251 fix: update links in issue and pull request templates to relative paths
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: size:S, lgtm

#3254 Update CODE_OF_CONDUCT and CONTRIBUTING documents across multiple lan…
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  locales/ca/CODE_OF_CONDUCT.md
  locales/ca/CONTRIBUTING.md
  locales/de/CODE_OF_CONDUCT.md
  locales/de/CONTRIBUTING.md
  locales/es/CODE_OF_CONDUCT.md
  locales/es/CONTRIBUTING.md
  locales/fr/CODE_OF_CONDUCT.md
  locales/fr/CONTRIBUTING.md
  locales/hi/CODE_OF_CONDUCT.md
  locales/hi/CONTRIBUTING.md
  locales/it/CODE_OF_CONDUCT.md
  locales/it/CONTRIBUTING.md
  locales/ja/CODE_OF_CONDUCT.md
  locales/ja/CONTRIBUTING.md
  locales/ko/CODE_OF_CONDUCT.md
  locales/ko/CONTRIBUTING.md
  locales/nl/CODE_OF_CONDUCT.md
  locales/nl/CONTRIBUTING.md
  locales/pl/CODE_OF_CONDUCT.md
  locales/pl/CONTRIBUTING.md
  locales/pt-BR/CODE_OF_CONDUCT.md
  locales/pt-BR/CONTRIBUTING.md
  locales/ru/CODE_OF_CONDUCT.md
  locales/ru/CONTRIBUTING.md
  locales/tr/CODE_OF_CONDUCT.md
  locales/tr/CONTRIBUTING.md
  locales/vi/CODE_OF_CONDUCT.md
  locales/vi/CONTRIBUTING.md
  locales/zh-CN/CODE_OF_CONDUCT.md
  locales/zh-CN/CONTRIBUTING.md
  locales/zh-TW/CODE_OF_CONDUCT.md
  locales/zh-TW/CONTRIBUTING.md
Labels: documentation, size:L, lgtm

#3235 Tailwind migration
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/chat/BrowserSessionRow.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/CommandExecutionError.tsx
  webview-ui/src/components/chat/ContextMenu.tsx
  webview-ui/src/components/chat/IconButton.tsx
  webview-ui/src/components/chat/Markdown.tsx
  webview-ui/src/components/chat/ProgressIndicator.tsx
  webview-ui/src/components/common/CodeAccordian.tsx
  webview-ui/src/components/common/CodeBlock.tsx
  webview-ui/src/components/common/MarkdownBlock.tsx
  webview-ui/src/components/common/MermaidBlock.tsx
  webview-ui/src/components/common/TelemetryBanner.tsx
  webview-ui/src/components/common/Thumbnails.tsx
  webview-ui/src/components/common/VSCodeButtonLink.tsx
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/mcp/McpEnabledToggle.tsx
  webview-ui/src/components/mcp/McpResourceRow.tsx
  webview-ui/src/components/mcp/McpToolRow.tsx
  webview-ui/src/components/mcp/McpView.tsx
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/settings/ApiConfigManager.tsx
  webview-ui/src/components/settings/BrowserSettings.tsx
  webview-ui/src/components/settings/ModelDescriptionMarkdown.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/providers/Bedrock.tsx
  webview-ui/src/components/settings/providers/Glama.tsx
  webview-ui/src/components/settings/providers/LMStudio.tsx
  webview-ui/src/components/settings/providers/OpenAICompatible.tsx
  webview-ui/src/components/settings/providers/OpenRouter.tsx
  webview-ui/src/components/settings/providers/Requesty.tsx
  webview-ui/src/components/settings/styles.ts
  webview-ui/src/components/ui/dialog.tsx
  webview-ui/src/components/ui/markdown/Blockquote.tsx
  webview-ui/src/components/ui/markdown/CodeBlock.tsx
  webview-ui/src/index.css
Labels: enhancement, size:XXL, lgtm

#3240 Detect tool loops
  src/core/Cline.ts
  src/core/ToolRepetitionDetector.ts
  src/core/__tests__/ToolRepetitionDetector.test.ts
  src/i18n/locales/ca/tools.json
  src/i18n/locales/de/tools.json
  src/i18n/locales/en/tools.json
  src/i18n/locales/es/tools.json
  src/i18n/locales/fr/tools.json
  src/i18n/locales/hi/tools.json
  src/i18n/locales/it/tools.json
  src/i18n/locales/ja/tools.json
  src/i18n/locales/ko/tools.json
  src/i18n/locales/nl/tools.json
  src/i18n/locales/pl/tools.json
  src/i18n/locales/pt-BR/tools.json
  src/i18n/locales/ru/tools.json
  src/i18n/locales/tr/tools.json
  src/i18n/locales/vi/tools.json
  src/i18n/locales/zh-CN/tools.json
  src/i18n/locales/zh-TW/tools.json
Labels: enhancement, size:XL, lgtm

#3242 Add LiteLLM provider
  src/api/index.ts
  src/api/providers/fetchers/cache.ts
  src/api/providers/fetchers/litellm.ts
  src/api/providers/litellm.ts
  src/api/providers/router-provider.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/ModelPicker.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/components/settings/providers/LiteLLM.tsx
  webview-ui/src/components/settings/providers/index.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/utils/validate.ts
Labels: enhancement, size:L, lgtm

#3283 Update evals defaults, stop forking cte/evals
  evals/packages/types/src/roo-code-defaults.ts
  evals/scripts/setup.sh
Labels: size:M

#3292 v3.16.1
  .changeset/v3.16.1.md
Labels: size:S

#3262 fix: reset the variable `isWaitingForFirstChunk` when catch exception
  src/core/Cline.ts
Labels: bug, size:XS, lgtm

#3230 Changeset version bump
  .changeset/brave-pigs-judge.md
  .changeset/v3.16.1.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M

#3295 Clarify XML tool use formatting instructions
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/responses.ts
  src/core/prompts/sections/tool-use.ts
Labels: documentation, size:S, lgtm

#3300 Changeset version bump
  .changeset/v3.16.2.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3306 fix: add Elixir (.ex, .exs) file extension support in language parser
  src/services/tree-sitter/languageParser.ts
Labels: bug, size:XS, lgtm

#3324 Changeset version bump
  .changeset/wicked-ways-cry.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3326 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, size:XS

#3328 fix: properly handle mode name overflow
  webview-ui/src/components/prompts/PromptsView.tsx
Labels: bug, size:S, lgtm

#3336 fix: enhance focus styles in select-dropdown and docs url
  webview-ui/src/components/ui/select-dropdown.tsx
  webview-ui/src/index.css
Labels: bug, size:S, lgtm

#3338 Fix: Enforce provider selection in OpenRouter by using 'only' parameter and disabling fallbacks
  src/api/providers/openrouter.ts
Labels: bug, size:S, lgtm

#3345 Move presentAssistantMessage into its own module
  jest.config.js
  src/activate/CodeActionProvider.ts
  src/activate/__tests__/CodeActionProvider.test.ts
  src/activate/handleTask.ts
  src/activate/index.ts
  src/activate/registerCodeActions.ts
  src/core/Cline.ts
  src/core/__tests__/read-file-maxReadFileLine.test.ts
  src/core/assistant-message/index.ts
  src/core/assistant-message/parseAssistantMessage.ts
  src/core/assistant-message/presentAssistantMessage.ts
  src/core/tools/ToolRepetitionDetector.ts
  src/core/tools/__tests__/ToolRepetitionDetector.test.ts
  src/core/tools/__tests__/readFileTool.test.ts
  src/core/tools/__tests__/validateToolUse.test.ts
  src/core/tools/validateToolUse.ts
  src/core/webview/ClineProvider.ts
  src/extension.ts
  src/integrations/editor/EditorUtils.ts
  src/integrations/editor/__tests__/EditorUtils.test.ts
  src/integrations/misc/__tests__/read-file-tool.test.ts
Labels: enhancement, size:XXL

#1711 build: prevent $esbuild-watch error
  .vscode/tasks.json
Labels: size:S, lgtm

#3303 Disable Posthog autocapture in the code in addition to in the web console
  webview-ui/src/utils/TelemetryClient.ts
Labels: size:XS, lgtm

#3352 Rename `Cline` to `Task`
  src/core/assistant-message/presentAssistantMessage.ts
  src/core/checkpoints/index.ts
  src/core/environment/__tests__/getEnvironmentDetails.test.ts
  src/core/environment/getEnvironmentDetails.ts
  src/core/task/Task.ts
  src/core/task/__tests__/Task.test.ts
  src/core/tools/__tests__/executeCommandTool.test.ts
  src/core/tools/accessMcpResourceTool.ts
  src/core/tools/applyDiffTool.ts
  src/core/tools/askFollowupQuestionTool.ts
  src/core/tools/attemptCompletionTool.ts
  src/core/tools/browserActionTool.ts
  src/core/tools/executeCommandTool.ts
  src/core/tools/fetchInstructionsTool.ts
  src/core/tools/insertContentTool.ts
  src/core/tools/listCodeDefinitionNamesTool.ts
  src/core/tools/listFilesTool.ts
  src/core/tools/newTaskTool.ts
  src/core/tools/readFileTool.ts
  src/core/tools/searchAndReplaceTool.ts
  src/core/tools/searchFilesTool.ts
  src/core/tools/switchModeTool.ts
  src/core/tools/useMcpToolTool.ts
  src/core/tools/writeToFileTool.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
Labels: size:XL

#3357 Stop leaking other provider settings
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.test.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
Labels: size:L, lgtm

#3371 fix display issues with too long profile names in ChatTextArea.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
Labels: bug, size:S, lgtm

#3356 fix: Prevent terminal focus theft on paste after command execution
  src/core/tools/executeCommandTool.ts
Labels: bug, size:XS, lgtm

#3368 fix: show properly formatted multi-line commands in preview
  webview-ui/src/components/chat/CommandExecution.tsx
Labels: bug, actionable, size:XS, lgtm

#3354 Fix not being able to use specific providers on Openrouter
  src/api/providers/fetchers/openrouter.ts
  src/api/providers/openrouter.ts
Labels: bug, size:XS, lgtm

#3359 fix: handle unsupported language errors gracefully in read_file tool
  src/core/tools/readFileTool.ts
Labels: bug, size:S, lgtm

#3343 fix(prompts): revert to vscodetextarea to prevent race condition
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/prompts/__tests__/PromptsView.test.tsx
Labels: bug, size:S, lgtm

#3366 Simplify the process of setting the "active" provider profile
  .gitignore
  git
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.test.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/api.ts
Labels: enhancement, size:L, lgtm

#3380 Get rid of `ApiConfiguration` type alias, rename `ApiConfigMeta` to `ProviderSettingsEntry`
  e2e/package-lock.json
  e2e/package.json
  evals/config/eslint/package.json
  evals/package.json
  evals/packages/types/src/roo-code.ts
  evals/pnpm-lock.yaml
  package-lock.json
  package.json
  src/api/index.ts
  src/core/config/ProviderSettingsManager.ts
  src/core/task/Task.ts
  src/core/task/__tests__/Task.test.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/schemas/index.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  src/shared/__tests__/checkExistApiConfig.test.ts
  src/shared/api.ts
  src/utils/__tests__/enhance-prompt.test.ts
  src/utils/single-completion-handler.ts
  webview-ui/src/components/chat/__tests__/TaskHeader.test.tsx
  webview-ui/src/components/settings/ApiConfigManager.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/PromptCachingControl.tsx
  webview-ui/src/components/settings/ReasoningEffort.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/ThinkingBudget.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/components/settings/providers/Anthropic.tsx
  webview-ui/src/components/settings/providers/Bedrock.tsx
  webview-ui/src/components/settings/providers/BedrockCustomArn.tsx
  webview-ui/src/components/settings/providers/Chutes.tsx
  webview-ui/src/components/settings/providers/DeepSeek.tsx
  webview-ui/src/components/settings/providers/Gemini.tsx
  webview-ui/src/components/settings/providers/Glama.tsx
  webview-ui/src/components/settings/providers/Groq.tsx
  webview-ui/src/components/settings/providers/LMStudio.tsx
  webview-ui/src/components/settings/providers/LiteLLM.tsx
  webview-ui/src/components/settings/providers/Mistral.tsx
  webview-ui/src/components/settings/providers/Ollama.tsx
  webview-ui/src/components/settings/providers/OpenAI.tsx
  webview-ui/src/components/settings/providers/OpenAICompatible.tsx
  webview-ui/src/components/settings/providers/OpenRouter.tsx
  webview-ui/src/components/settings/providers/Requesty.tsx
  webview-ui/src/components/settings/providers/Unbound.tsx
  webview-ui/src/components/settings/providers/VSCodeLM.tsx
  webview-ui/src/components/settings/providers/Vertex.tsx
  webview-ui/src/components/settings/providers/XAI.tsx
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/utils/validate.ts
Labels: size:XL

#3383 Export more types to the external API
  src/core/config/ProviderSettingsManager.ts
  src/exports/api.ts
  src/exports/interface.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
Labels: enhancement, size:XL

#3399 Don't return api keys through the api
  src/exports/api.ts
  src/exports/interface.ts
  src/exports/roo-code.d.ts
Labels: size:M, lgtm

#3386 Improve provider profile management in the external API
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/api.ts
  src/exports/interface.ts
  src/exports/roo-code.d.ts
  src/shared/WebviewMessage.ts
Labels: enhancement, size:L, lgtm

#3415 Fix saving of OpenAI compatible headers
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/providers/OpenAICompatible.tsx
  webview-ui/src/components/settings/utils/__tests__/headers.test.ts
  webview-ui/src/components/settings/utils/headers.ts
Labels: bug, size:L, lgtm

#3424 Fix: forced-color-adjust in highlight theme
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/welcome/RooHero.tsx
  webview-ui/src/components/welcome/RooTips.tsx
Labels: bug, size:XS, lgtm

#3426 v3.16.4
  .changeset/v3.16.4.md
Labels: size:S

#3427 Changeset version bump
  .changeset/v3.16.4.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M

#3441 Changeset version bump
  .changeset/lazy-bottles-travel.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3448 Pr template fix
  .github/pull_request_template.md
Labels: size:XS, lgtm

#3452 Tweaks to the issue/bug intended to make it more intuitive.
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: bug, size:M, lgtm

#3454 Refactor bug report template to enforce required fields for reproduct…
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, size:XS

#3463 fix(textarea): empty string as fallback
  webview-ui/src/components/prompts/PromptsView.tsx
Labels: bug, size:XS, lgtm

#3469 Updated roadmap
  CONTRIBUTING.md
  locales/ca/CONTRIBUTING.md
  locales/de/CONTRIBUTING.md
  locales/es/CONTRIBUTING.md
  locales/fr/CONTRIBUTING.md
  locales/hi/CONTRIBUTING.md
  locales/it/CONTRIBUTING.md
  locales/ja/CONTRIBUTING.md
  locales/ko/CONTRIBUTING.md
  locales/nl/CONTRIBUTING.md
  locales/pl/CONTRIBUTING.md
  locales/pt-BR/CONTRIBUTING.md
  locales/ru/CONTRIBUTING.md
  locales/tr/CONTRIBUTING.md
  locales/vi/CONTRIBUTING.md
  locales/zh-CN/CONTRIBUTING.md
  locales/zh-TW/CONTRIBUTING.md
Labels: documentation, size:XXL

#3028 fix: webview terminal output processing error
  src/core/tools/executeCommandTool.ts
  webview-ui/src/components/chat/CommandExecution.tsx
Labels: bug, size:M, lgtm

#1870 ClineProvider.finishSubTask should wait for unpausing the parent task
  src/core/webview/ClineProvider.ts
Labels: bug, size:XS, lgtm

#3507 Changeset version bump
  .changeset/thin-penguins-search.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3509 Improve command execution UI
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/CommandExecution.tsx
  webview-ui/src/components/common/CodeBlock.tsx
Labels: enhancement, size:L

#3512 fix: get model id from ApiHandler
  src/core/environment/__tests__/getEnvironmentDetails.test.ts
  src/core/environment/getEnvironmentDetails.ts
Labels: bug, size:XS, lgtm

#3515 Gemini implicit caching
  evals/packages/types/src/roo-code.ts
  src/api/index.ts
  src/api/providers/__tests__/gemini.test.ts
  src/api/providers/__tests__/openrouter.test.ts
  src/api/providers/__tests__/vertex.test.ts
  src/api/providers/fetchers/__tests__/fixtures/openrouter-models.json
  src/api/providers/fetchers/__tests__/openrouter.test.ts
  src/api/providers/fetchers/openrouter.ts
  src/api/providers/gemini.ts
  src/api/providers/openrouter.ts
  src/api/transform/gemini-format.ts
  src/core/task/Task.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/api.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/PromptCachingControl.tsx
Labels: enhancement, size:XL

#3518 Update CHANGELOG.md
  CHANGELOG.md
Labels: size:XS

#3457 Handle directory URI on diagnostics
  src/integrations/diagnostics/__tests__/diagnostics.test.ts
  src/integrations/diagnostics/index.ts
Labels: bug, size:L, lgtm

#3430 Use the provider-specific model info for the OpenRouter provider
  package-lock.json
  package.json
  src/api/providers/__tests__/glama.test.ts
  src/api/providers/__tests__/openrouter.test.ts
  src/api/providers/__tests__/requesty.test.ts
  src/api/providers/__tests__/unbound.test.ts
  src/api/providers/fetchers/__tests__/fixtures/openrouter-model-endpoints.json
  src/api/providers/fetchers/__tests__/fixtures/openrouter-models.json
  src/api/providers/fetchers/__tests__/openrouter.test.ts
  src/api/providers/fetchers/modelCache.ts
  src/api/providers/fetchers/modelEndpointCache.ts
  src/api/providers/fetchers/openrouter.ts
  src/api/providers/openrouter.ts
  src/api/providers/requesty.ts
  src/api/providers/router-provider.ts
  src/core/webview/webviewMessageHandler.ts
  webview-ui/src/components/ui/hooks/useSelectedModel.ts
Labels: bug, size:L, lgtm

#3474 Greyscreen fix
  src/core/task/__tests__/Task.test.ts
  src/integrations/editor/DiffViewProvider.ts
Labels: bug, size:XS, lgtm

#3329 make apply_diff can deduce when line number in search part fix #2990
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
Labels: bug, size:M, lgtm

#3530 fix: command validation failing on shell array indexing
  webview-ui/.eslintrc.json
  webview-ui/src/__tests__/utils/command-validation.test.ts
  webview-ui/src/utils/command-validation.ts
Labels: bug, size:L, lgtm

#3471 fix(task): temporary fix for the ask error
  src/core/checkpoints/index.ts
  src/core/task/Task.ts
  src/core/tools/__tests__/readFileTool.test.ts
  src/core/tools/applyDiffTool.ts
  src/core/tools/attemptCompletionTool.ts
  src/core/tools/insertContentTool.ts
  src/core/tools/listCodeDefinitionNamesTool.ts
  src/core/tools/readFileTool.ts
  src/core/tools/searchAndReplaceTool.ts
  src/core/tools/writeToFileTool.ts
Labels: bug, size:L, lgtm

#3542 Requesty: Only report final usage
  .changeset/twelve-ants-scream.md
  src/api/providers/requesty.ts
Labels: bug, size:S, lgtm

#3538 Add tests + benchmark for parseAssistantMessage V1 + 2
  src/core/assistant-message/__tests__/parseAssistantMessage.test.ts
  src/core/assistant-message/__tests__/parseAssistantMessageBenchmark.ts
  src/core/assistant-message/parseAssistantMessage.ts
  src/core/assistant-message/parseAssistantMessageV2.ts
  src/integrations/editor/DiffViewProvider.ts
Labels: size:XL, lgtm

#3456 Accidental execution of tool syntax fix
  src/core/assistant-message/__tests__/parseAssistantMessage.test.ts
  src/core/assistant-message/__tests__/parseAssistantMessageBenchmark.ts
  src/core/assistant-message/index.ts
  src/core/assistant-message/parseAssistantMessage.ts
  src/core/assistant-message/parseAssistantMessageV2.ts
  src/core/task/Task.ts
  webview-ui/src/__tests__/utils/command-validation.test.ts
  webview-ui/src/utils/__tests__/command-validation.test.ts
Labels: bug, size:XL, lgtm

#3560 Revert "Accidental execution of tool syntax fix"
  src/core/assistant-message/__tests__/parseAssistantMessage.test.ts
  src/core/assistant-message/__tests__/parseAssistantMessageBenchmark.ts
  src/core/assistant-message/index.ts
  src/core/assistant-message/parseAssistantMessage.ts
  src/core/assistant-message/parseAssistantMessageV2.ts
  src/core/task/Task.ts
  webview-ui/src/__tests__/utils/command-validation.test.ts
  webview-ui/src/utils/__tests__/command-validation.test.ts
Labels: size:XL

#3539 Focus improvements
  src/integrations/editor/DiffViewProvider.ts
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/__tests__/ChatTextArea.test.tsx
  webview-ui/src/components/chat/__tests__/ChatView.test.tsx
Labels: enhancement, size:L, lgtm

#3241 Show LLM streaming file write content
  src/core/tools/applyDiffTool.ts
  src/core/tools/insertContentTool.ts
  src/core/tools/searchAndReplaceTool.ts
  src/core/tools/writeToFileTool.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ContextMenu.tsx
  webview-ui/src/components/common/CodeAccordian.tsx
  webview-ui/src/components/common/ToolUseBlock.tsx
  webview-ui/src/utils/removeLeadingNonAlphanumeric.ts
Labels: enhancement, size:L, lgtm

#3563 Publish Roo Code types to NPM
  roo-code-types/.gitignore
  roo-code-types/.releaserc
  roo-code-types/LICENSE
  roo-code-types/README.md
  roo-code-types/index.d.ts
  roo-code-types/package-lock.json
  roo-code-types/package.json
  scripts/generate-types.mts
Labels: enhancement, size:XL

#3472 Make CONTRIBUTING.md more concise
  CONTRIBUTING.md
  locales/ca/CONTRIBUTING.md
  locales/de/CONTRIBUTING.md
  locales/es/CONTRIBUTING.md
  locales/fr/CONTRIBUTING.md
  locales/hi/CONTRIBUTING.md
  locales/it/CONTRIBUTING.md
  locales/ja/CONTRIBUTING.md
  locales/ko/CONTRIBUTING.md
  locales/nl/CONTRIBUTING.md
  locales/pl/CONTRIBUTING.md
  locales/pt-BR/CONTRIBUTING.md
  locales/ru/CONTRIBUTING.md
  locales/tr/CONTRIBUTING.md
  locales/vi/CONTRIBUTING.md
  locales/zh-CN/CONTRIBUTING.md
  locales/zh-TW/CONTRIBUTING.md
Labels: documentation, size:XXL

#3568 Add IPC types to roo-code.d.ts
  scripts/generate-types.mts
  src/exports/api.ts
  src/exports/interface.ts
  src/exports/ipc.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/schemas/ipc.ts
Labels: enhancement, size:XXL

#3578 Revert "fix(deps): update nextjs monorepo to v15.3.2"
  evals/apps/web/package.json
  evals/pnpm-lock.yaml
Labels: size:XS

#3581 Fix linter warning + run prettier on everything
  e2e/.vscode-test.mjs
  e2e/package.json
  evals/.tool-versions
  package.nls.nl.json
  scripts/generate-types.mts
  src/i18n/locales/nl/common.json
  webview-ui/index.html
  webview-ui/jest.config.cjs
  webview-ui/package.json
  webview-ui/src/__tests__/utils/command-validation.test.ts
  webview-ui/src/components/settings/ModelInfoView.tsx
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/nl/common.json
  webview-ui/src/i18n/locales/nl/history.json
  webview-ui/src/i18n/locales/nl/humanRelay.json
  webview-ui/src/i18n/locales/nl/mcp.json
  webview-ui/src/i18n/locales/nl/prompts.json
  webview-ui/src/i18n/locales/nl/welcome.json
  webview-ui/src/stories/Welcome.mdx
  webview-ui/src/utils/__tests__/command-validation.test.ts
Labels: size:XXL

#3571 Add a 'when to use' section to mode definitions
  .changeset/dark-swans-marry.md
  src/core/prompts/instructions/create-mode.ts
  src/core/prompts/sections/modes.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/modes.ts
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/i18n/locales/ca/prompts.json
  webview-ui/src/i18n/locales/de/prompts.json
  webview-ui/src/i18n/locales/en/prompts.json
  webview-ui/src/i18n/locales/es/prompts.json
  webview-ui/src/i18n/locales/fr/prompts.json
  webview-ui/src/i18n/locales/hi/prompts.json
  webview-ui/src/i18n/locales/it/prompts.json
  webview-ui/src/i18n/locales/ja/prompts.json
  webview-ui/src/i18n/locales/ko/prompts.json
  webview-ui/src/i18n/locales/nl/prompts.json
  webview-ui/src/i18n/locales/pl/prompts.json
  webview-ui/src/i18n/locales/pt-BR/prompts.json
  webview-ui/src/i18n/locales/ru/prompts.json
  webview-ui/src/i18n/locales/tr/prompts.json
  webview-ui/src/i18n/locales/vi/prompts.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
  webview-ui/src/utils/context-mentions.ts
Labels: enhancement, size:L, lgtm

#3583 Refactor: Update custom instructions for 'ask' mode
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/shared/modes.ts
Labels: size:XS, lgtm

#3586 Refactor: Update new_task tool description and mode examples
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/prompts/tools/new-task.ts
Labels: size:XS, lgtm

#3587 Rename cline_docs -> docs
  .roo/rules/rules.md
  .vscodeignore
  docs/bedrock/bedrock-cache-strategy-documentation.md
  docs/bedrock/model-identification.md
  docs/settings.md
Labels: documentation, size:XS

#3604 Use a shadcn dialog for the announcement
  .changeset/nasty-keys-smile.md
  scripts/generate-types.mts
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/components/ui/dialog.tsx
Labels: size:L, lgtm

#3600 Add build vsix Workflow
  .github/workflows/build-vsix.yml
Labels: enhancement, size:M, lgtm

#3596 build: enable source maps for improved debugging
  webview-ui/package.json
  webview-ui/tsconfig.json
  webview-ui/vite.config.ts
Labels: enhancement, size:XS, lgtm

#3614 v3.16.7
  .changeset/v3.16.7.md
Labels: size:S

#3582 [Condense] Condense messages with an LLM rather than truncating
  .changeset/large-bags-send.md
  evals/packages/types/src/roo-code.ts
  src/api/transform/__tests__/image-cleaning.test.ts
  src/api/transform/image-cleaning.ts
  src/core/condense/__tests__/index.test.ts
  src/core/condense/index.ts
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
  src/core/task-persistence/apiMessages.ts
  src/core/task/Task.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/experiments.ts
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm

#3619 Fix type generation
  scripts/generate-types.mts
Labels: bug, size:XS

#3622 v3.17.0
  .changeset/v3.17.0.md
  README.md
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/nl/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/ru/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/README.md
  src/core/webview/ClineProvider.ts
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:XXL

#3556 Changeset version bump
  .changeset/dark-swans-marry.md
  .changeset/large-bags-send.md
  .changeset/lovely-moles-end.md
  .changeset/nasty-keys-smile.md
  .changeset/twelve-ants-scream.md
  .changeset/v3.16.7.md
  .changeset/v3.17.0.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M

#3626 Fix incorrect reserved tokens calculation on OpenRouter
  webview-ui/src/utils/model-utils.ts
Labels: bug, size:XS, lgtm

#3636 Fix command display in the approval required case
  .changeset/seven-ghosts-tan.md
  webview-ui/package-lock.json
  webview-ui/src/components/chat/CommandExecution.tsx
Labels: bug, size:M

#3637 Changeset version bump
  .changeset/seven-ghosts-tan.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3638 Fix how custom instructions are loaded into the API request
  src/core/task/Task.ts
  src/core/task/__tests__/Task.test.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
Labels: bug, size:M, lgtm

#3649 Revert "Switch to the new Roo message parser"
  .changeset/eighty-rules-slide.md
  src/core/assistant-message/index.ts
  src/core/task/Task.ts
Labels: size:S, lgtm

#3645 Changeset version bump
  .changeset/eighty-rules-slide.md
  .changeset/ten-stars-occur.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#3657 Import settings bug fix / improvements
  .changeset/young-dancers-join.md
  src/core/config/__tests__/importExport.test.ts
  src/core/config/importExport.ts
  src/core/webview/webviewMessageHandler.ts
  src/i18n/locales/ca/common.json
  src/i18n/locales/de/common.json
  src/i18n/locales/en/common.json
  src/i18n/locales/es/common.json
  src/i18n/locales/fr/common.json
  src/i18n/locales/hi/common.json
  src/i18n/locales/it/common.json
  src/i18n/locales/ja/common.json
  src/i18n/locales/ko/common.json
  src/i18n/locales/nl/common.json
  src/i18n/locales/pl/common.json
  src/i18n/locales/pt-BR/common.json
  src/i18n/locales/ru/common.json
  src/i18n/locales/tr/common.json
  src/i18n/locales/vi/common.json
  src/i18n/locales/zh-CN/common.json
  src/i18n/locales/zh-TW/common.json
Labels: bug, size:L

#3675 Export ProviderName type to Roo-Code-Types
  src/exports/interface.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
Labels: size:M

#3704 Log Cleanup to Remove Cline
  src/core/task/Task.ts
Labels: size:S, lgtm

#3697 #3679 - Fixes packaging to include correct tiktoken.wasm (lite)
  .gitignore
  .vscodeignore
  esbuild.js
  tsconfig.json
Labels: bug, size:S, lgtm

#3663 Adds refresh models button for Unbound provider
  .changeset/seven-kids-return.md
  src/api/providers/fetchers/modelCache.ts
  src/api/providers/fetchers/unbound.ts
  webview-ui/src/components/settings/providers/Unbound.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/nl/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/ru/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm

#3710 Add Qwen3 model series to the Chutes provider
  .changeset/curly-plants-pull.md
  src/shared/api.ts
Labels: enhancement, size:M, lgtm

#3727 fix(webview): Fix links to filename:0
  .changeset/slimy-paths-design.md
  src/integrations/misc/open-file.ts
Labels: bug, size:XS, lgtm

#3606 feat(evals): add UI and backend support for importing and injecting f…
  evals/apps/cli/src/index.ts
  evals/apps/web/src/app/runs/new/new-run.tsx
  evals/apps/web/src/lib/schemas.ts
  evals/apps/web/src/lib/server/runs.ts
Labels: enhancement, size:M, lgtm

#3736 [Condense Context] Track metrics around context condensing and show in UI
  .changeset/fair-houses-deny.md
  evals/packages/types/src/roo-code.ts
  src/core/condense/__tests__/index.test.ts
  src/core/condense/index.ts
  src/core/sliding-window/__tests__/sliding-window.test.ts
  src/core/sliding-window/index.ts
  src/core/task/Task.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/__tests__/getApiMetrics.test.ts
  src/shared/getApiMetrics.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/chat/ContextCondenseRow.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/nl/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/ru/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:XXL, lgtm

#3739 Make prompt input textareas resizable (#3691)
  webview-ui/src/components/prompts/PromptsView.tsx
Labels: bug, size:S, lgtm

#3659 feat: move play audio to webview to ensure cross-platform
  package-lock.json
  package.json
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/utils/sound.ts
  webview-ui/audio/celebration.wav
  webview-ui/audio/notification.wav
  webview-ui/audio/progress_loop.wav
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/__tests__/ChatView.test.tsx
  webview-ui/vite.config.ts
Labels: enhancement, size:L, lgtm
