Repository RooCodeInc/Roo-Code, pull requests merged in 2025-04, with the labels that each got.

#2157 Dockerize evals
  .dockerignore
  benchmark/Dockerfile
  benchmark/README.md
  benchmark/apps/cli/src/index.ts
  benchmark/apps/web/src/lib/server/runs.ts
  benchmark/entrypoint.sh
  benchmark/package.json
  benchmark/packages/types/src/roo-code-defaults.ts
  src/exports/api.ts
  src/integrations/terminal/Terminal.ts
Labels: enhancement, size:L, lgtm

#2166 Update app icon
  assets/icons/icon.png
Labels: enhancement, size:XS

#1874 We should post state to webview at the end of `RooCodeAPI.clearCurrentTask()`
  src/exports/api.ts
Labels: bug, size:XS, lgtm

#1963 Fix Tests to run properly on Windows
  .changeset/curvy-cows-cry.md
  .github/workflows/code-qa.yml
  jest.config.js
  package.json
  scripts/run-tests.js
  src/api/providers/__tests__/bedrock.test.ts
  src/api/providers/bedrock.ts
  src/core/diff/strategies/new-unified/edit-strategies.ts
  src/extension.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.bash.test.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.cmd.test.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.common.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.pwsh.test.ts
  src/integrations/terminal/__tests__/setupTerminalTests.ts
  src/integrations/terminal/__tests__/streamUtils/bashStream.ts
  src/integrations/terminal/__tests__/streamUtils/cmdStream.ts
  src/integrations/terminal/__tests__/streamUtils/index.ts
  src/integrations/terminal/__tests__/streamUtils/mockStream.ts
  src/integrations/terminal/__tests__/streamUtils/pwshStream.ts
  src/integrations/workspace/__tests__/WorkspaceTracker.test.ts
  src/services/mcp/McpHub.ts
  src/services/mcp/__tests__/McpHub.test.ts
Labels: bug, size:XXL, lgtm

#2169 Tree-sitter Enhancements: TSX, TypeScript, JSON, and Markdown Support
  .github/workflows/code-qa.yml
  src/services/tree-sitter/__tests__/helpers.ts
  src/services/tree-sitter/__tests__/index.test.ts
  src/services/tree-sitter/__tests__/markdownIntegration.test.ts
  src/services/tree-sitter/__tests__/markdownParser.test.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.json.test.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.tsx.test.ts
  src/services/tree-sitter/index.ts
  src/services/tree-sitter/languageParser.ts
  src/services/tree-sitter/markdownParser.ts
  src/services/tree-sitter/queries/index.ts
  src/services/tree-sitter/queries/javascript.ts
  src/services/tree-sitter/queries/tsx.ts
  src/services/tree-sitter/queries/typescript.ts
Labels: enhancement, size:XXL, lgtm

#2193 fix(diff): Handle line number stripping for deletions in apply_diff
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
Labels: bug, size:S, lgtm

#2196 Update History Selection Mode button spacing
  webview-ui/src/components/history/HistoryView.tsx
Labels: enhancement, size:XS, lgtm

#2181 Limit DropdownMenu height to 80% of viewport
  webview-ui/src/components/ui/select-dropdown.tsx
Labels: enhancement, size:XS, lgtm

#2192 Update dependencies via `npm audit fix`
  package-lock.json
Labels: size:XS, lgtm

#2215 Make the SelectDropdown use modal=false
  webview-ui/src/components/ui/select-dropdown.tsx
Labels: size:XS

#2225 fixes: 2224 - Update AWS region drop down to be current.
  webview-ui/src/components/settings/constants.ts
Labels: enhancement, size:S, lgtm

#2230 fixes: 2229 - completePrompt doesn't work for bedrock.
  src/api/providers/__tests__/bedrock-custom-arn.test.ts
  src/api/providers/__tests__/bedrock.test.ts
  src/api/providers/bedrock.ts
Labels: bug, size:L, lgtm

#2232 Allow processes to access the Roo Code API via a unix socket
  .tool-versions
  e2e/VSCODE_INTEGRATION_TESTS.md
  e2e/package.json
  e2e/src/suite/extension.test.ts
  e2e/src/suite/index.ts
  e2e/src/suite/modes.test.ts
  e2e/src/suite/subtasks.test.ts
  e2e/src/suite/task.test.ts
  e2e/src/suite/utils.ts
  knip.json
  package-lock.json
  package.json
  src/activate/registerCommands.ts
  src/exports/api.ts
  src/exports/interface.ts
  src/exports/ipc.ts
  src/exports/log.ts
  src/exports/message-history.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/extension.ts
  src/integrations/terminal/Terminal.ts
  src/schemas/index.ts
  src/schemas/ipc.ts
Labels: enhancement, size:XXL, lgtm

#2233 Improve zh-TW Traditional Chinese locale
  locales/zh-TW/CODE_OF_CONDUCT.md
  locales/zh-TW/CONTRIBUTING.md
  locales/zh-TW/README.md
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/history.json
  webview-ui/src/i18n/locales/zh-TW/humanRelay.json
  webview-ui/src/i18n/locales/zh-TW/mcp.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/i18n/locales/zh-TW/welcome.json
Labels: documentation, size:XL, lgtm

#2237 Add a mode switched event, better mode switch e2e test
  e2e/src/suite/modes.test.ts
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/exports/api.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/schemas/ipc.ts
Labels: enhancement, size:M

#2236 Fix tree sitter to output 1-based line numbers
  src/services/tree-sitter/__tests__/index.test.ts
  src/services/tree-sitter/__tests__/markdownIntegration.test.ts
  src/services/tree-sitter/index.ts
Labels: bug, size:S, lgtm

#2243 Typos + promisify exec calls
  e2e/src/suite/task.test.ts
  evals/apps/web/src/app/runs/new/settings-diff.tsx
  evals/apps/web/src/lib/server/processes.ts
  evals/packages/db/README.md
Labels: documentation, size:M, lgtm

#2246 Remove the experimental unified diff
  .changeset/popular-teachers-brush.md
  evals/packages/types/src/roo-code-defaults.ts
  evals/packages/types/src/roo-code.ts
  src/core/diff/DiffStrategy.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/__tests__/experiments.test.ts
  src/shared/experiments.ts
  webview-ui/src/components/settings/AdvancedSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
Labels: enhancement, size:M

#2241 feat: Add support for Azure AI Inference Service with DeepSeek-V3 model
  src/api/providers/__tests__/openai.test.ts
  src/api/providers/__tests__/requesty.test.ts
  src/api/providers/openai.ts
Labels: enhancement, size:L, lgtm

#2250 v3.11.4
  .changeset/fifty-glasses-fold.md
Labels: size:XS, lgtm

#2204 Changeset version bump
  .changeset/curvy-cows-cry.md
  .changeset/fifty-glasses-fold.md
  .changeset/popular-teachers-brush.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:M

#2251 Add profile management functions to API
  src/core/config/ProviderSettingsManager.ts
  src/exports/api.ts
  src/exports/interface.ts
  src/exports/roo-code.d.ts
Labels: enhancement, size:L, lgtm

#2261 chore: Add more multi-block tests for apply_diff tool
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
Labels: size:M, lgtm

#2262 Remove code for old diff strategies
  src/core/diff/DiffStrategy.ts
  src/core/diff/strategies/__tests__/new-unified.test.ts
  src/core/diff/strategies/__tests__/unified.test.ts
  src/core/diff/strategies/new-unified/__tests__/edit-strategies.test.ts
  src/core/diff/strategies/new-unified/__tests__/search-strategies.test.ts
  src/core/diff/strategies/new-unified/edit-strategies.ts
  src/core/diff/strategies/new-unified/index.ts
  src/core/diff/strategies/new-unified/search-strategies.ts
  src/core/diff/strategies/new-unified/types.ts
  src/core/diff/strategies/unified.ts
Labels: size:XXL, lgtm

#2263 Fix for focus grabbing when follow-up returns + Unit Test
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/chat/__tests__/ChatView.test.tsx
Labels: bug, size:L, lgtm

#2071 Jbbrown/bedrock caching
  cline_docs/bedrock/bedrock-cache-strategy-documentation.md
  cline_docs/bedrock/model-identification.md
  locales/ca/README.md
  locales/de/README.md
  locales/es/README.md
  locales/fr/README.md
  locales/hi/README.md
  locales/it/README.md
  locales/ja/README.md
  locales/ko/README.md
  locales/pl/README.md
  locales/pt-BR/README.md
  locales/tr/README.md
  locales/vi/README.md
  locales/zh-CN/README.md
  locales/zh-TW/CONTRIBUTING.md
  locales/zh-TW/README.md
  package-lock.json
  package.json
  src/api/providers/__tests__/bedrock-custom-arn.test.ts
  src/api/providers/__tests__/bedrock-invokedModelId.test.ts
  src/api/providers/__tests__/bedrock.test.ts
  src/api/providers/bedrock.ts
  src/api/transform/cache-strategy/__tests__/cache-strategy.test.ts
  src/api/transform/cache-strategy/base-strategy.ts
  src/api/transform/cache-strategy/multi-point-strategy.ts
  src/api/transform/cache-strategy/types.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/api.ts
  src/shared/aws_regions.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: documentation, enhancement, size:XXL

#2171 mcp supports cwd config and defaults to workspace cwd
  src/services/mcp/McpHub.ts
Labels: enhancement, size:XS, lgtm

#2260 fix: Improve error message when apply_diff structure is invalid
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
Labels: bug, size:M, lgtm

#2281 Show menu buttons in tab view
  package.json
  src/activate/__tests__/registerCommands.test.ts
  src/activate/registerCommands.ts
Labels: enhancement, size:L, lgtm

#2275 Update LICENSE
  LICENSE
Labels: size:XS

#2282 Better logic for choosing the view column when opening Roo in a tab
  src/activate/registerCommands.ts
Labels: enhancement, size:S, lgtm

#2274 fix: Improve handling of escaped markers in apply_diff
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
Labels: bug, size:S, lgtm

#2283 v3.11.5
  .changeset/friendly-cooks-dress.md
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/chat/Announcement.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: size:L

#2285 Revert "Better logic for choosing the view column when opening Roo in a tab"
  .changeset/hip-pumpkins-mate.md
  src/activate/registerCommands.ts
Labels: size:S

#2284 Changeset version bump
  .changeset/friendly-cooks-dress.md
  .changeset/hip-pumpkins-mate.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2280 Ironing out some kinks when running evals with high parallelism
  evals/apps/cli/src/index.ts
  evals/apps/web/src/app/home.tsx
  evals/apps/web/src/app/layout.tsx
  evals/apps/web/src/app/runs/[id]/run.tsx
  evals/apps/web/src/app/runs/new/new-run.tsx
  evals/apps/web/src/hooks/use-open-router-models.ts
  evals/apps/web/src/lib/format-tokens.ts
  evals/apps/web/src/lib/schemas.ts
  evals/packages/db/package.json
  evals/packages/db/scripts/enable-wal.mts
  evals/packages/db/src/db.ts
  evals/packages/db/src/schema.ts
  evals/packages/types/src/roo-code-defaults.ts
  evals/packages/types/src/roo-code.ts
  evals/scripts/setup.sh
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  src/exports/api.ts
Labels: size:XL

#2298 Improve evals settings import
  evals/apps/web/src/app/runs/new/new-run.tsx
  evals/apps/web/src/app/runs/new/settings-diff.tsx
  evals/packages/types/src/roo-code.ts
Labels: enhancement, size:M

#2300 Add the gemini 2.5 pro preview model with upper bound pricing
  .changeset/quiet-turkeys-wash.md
  src/shared/api.ts
  webview-ui/src/components/settings/ModelInfoView.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:M, lgtm

#2278 Refactor: Improve file tool context formatting and diff error guidance
  src/core/__tests__/read-file-maxReadFileLine.test.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/core/tools/readFileTool.ts
Labels: enhancement, size:S, lgtm

#2305 Improve zh-TW Traditional Chinese locale
  locales/zh-TW/README.md
  src/i18n/locales/zh-TW/common.json
  src/i18n/locales/zh-TW/tools.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:L, lgtm

#2306 Improve Simplified Chinese translations
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-CN/history.json
  webview-ui/src/i18n/locales/zh-CN/humanRelay.json
  webview-ui/src/i18n/locales/zh-CN/mcp.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-CN/welcome.json
Labels: documentation, size:L, lgtm

#2312 Updated buttons to @/components/ui/button
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/mcp/McpView.tsx
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/settings/SettingsView.tsx
Labels: enhancement, size:L, lgtm

#2310 refactor(mcp): Implement reference counting for McpHub lifecycle
  src/core/webview/ClineProvider.ts
  src/services/mcp/McpHub.ts
Labels: enhancement, size:M, lgtm

#2314 v3.11.7
  .changeset/swift-trees-double.md
Labels: size:XS

#2316 Changeset version bump
  .changeset/swift-trees-double.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2221 feat(settings): add searchable dropdown to API config profiles setting page
  webview-ui/src/components/settings/ApiConfigManager.tsx
  webview-ui/src/components/settings/__tests__/ApiConfigManager.test.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm

#2054 feat: add workspace tracking to history items
  src/core/Cline.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
Labels: enhancement, size:XS, lgtm

#2176 fix: history search highlight
  webview-ui/src/index.css
Labels: bug, size:XS, lgtm

#2318 Improve combineApiRequests performance
  src/integrations/terminal/__tests__/TerminalProcessExec.pwsh.test.ts
  src/integrations/terminal/__tests__/setupTerminalTests.ts
  src/shared/__tests__/combineApiRequests.test.ts
  src/shared/combineApiRequests.ts
Labels: enhancement, size:XL, lgtm

#2309 feat: Add support for .roorules configuration files
  src/core/prompts/sections/__tests__/custom-instructions.test.ts
  src/core/prompts/sections/custom-instructions.ts
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/components/settings/__tests__/ApiConfigManager.test.tsx
  webview-ui/src/i18n/locales/ca/prompts.json
  webview-ui/src/i18n/locales/de/prompts.json
  webview-ui/src/i18n/locales/en/prompts.json
  webview-ui/src/i18n/locales/es/prompts.json
  webview-ui/src/i18n/locales/fr/prompts.json
  webview-ui/src/i18n/locales/hi/prompts.json
  webview-ui/src/i18n/locales/it/prompts.json
  webview-ui/src/i18n/locales/ja/prompts.json
  webview-ui/src/i18n/locales/ko/prompts.json
  webview-ui/src/i18n/locales/pl/prompts.json
  webview-ui/src/i18n/locales/pt-BR/prompts.json
  webview-ui/src/i18n/locales/tr/prompts.json
  webview-ui/src/i18n/locales/vi/prompts.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
Labels: enhancement, size:L, lgtm

#2307 fix: correct nodejs version format in .tool-versions file
  .tool-versions
Labels: bug, size:XS, lgtm

#2331 v3.11.8
  .changeset/plenty-bags-yawn.md
Labels: size:XS

#2332 Changeset version bump
  .changeset/plenty-bags-yawn.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2182 Tidy up following ClineProvider refactor
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
Labels: size:L, lgtm

#2337 fix: clamp negative line numbers when reading files
  src/integrations/misc/__tests__/read-lines.test.ts
  src/integrations/misc/read-lines.ts
Labels: bug, size:M, lgtm

#2335 feat: enhance Rust tree-sitter parser with advanced language structures
  src/services/tree-sitter/__tests__/helpers.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.rust.test.ts
  src/services/tree-sitter/queries/rust.ts
Labels: enhancement, size:XL, lgtm

#2341 fix: persist settings on api.setConfiguration
  src/exports/api.ts
Labels: bug, size:XS, lgtm

#2355 Add deep links to settings sections
  webview-ui/src/App.tsx
  webview-ui/src/components/chat/AutoApproveMenu.tsx
  webview-ui/src/components/chat/ChatTextArea.tsx
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/common/TelemetryBanner.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:M

#2357 Move .clinerules to .roorules
  .roorules
Labels: size:XS

#2334 fix: Prevent unnecessary autoscroll when buttons appear (#1280)
  webview-ui/src/components/chat/ChatView.tsx
Labels: bug, size:XS, lgtm

#1672 feat(RooCodeAPI): implement resumeTask and isTaskInHistory
  src/exports/api.ts
  src/exports/roo-code.d.ts
Labels: enhancement, size:S, lgtm

#2380 Fixes to resumeTask and isTaskInHistory
  src/exports/api.ts
  src/exports/interface.ts
  src/exports/roo-code.d.ts
Labels: size:S

#2354 feat: enhance rule file loading with .roo/rules directory support
  src/core/prompts/sections/__tests__/custom-instructions.test.ts
  src/core/prompts/sections/custom-instructions.ts
  webview-ui/src/components/prompts/PromptsView.tsx
  webview-ui/src/i18n/locales/ca/prompts.json
  webview-ui/src/i18n/locales/de/prompts.json
  webview-ui/src/i18n/locales/en/prompts.json
  webview-ui/src/i18n/locales/es/prompts.json
  webview-ui/src/i18n/locales/fr/prompts.json
  webview-ui/src/i18n/locales/hi/prompts.json
  webview-ui/src/i18n/locales/it/prompts.json
  webview-ui/src/i18n/locales/ja/prompts.json
  webview-ui/src/i18n/locales/ko/prompts.json
  webview-ui/src/i18n/locales/pl/prompts.json
  webview-ui/src/i18n/locales/pt-BR/prompts.json
  webview-ui/src/i18n/locales/tr/prompts.json
  webview-ui/src/i18n/locales/vi/prompts.json
  webview-ui/src/i18n/locales/zh-CN/prompts.json
  webview-ui/src/i18n/locales/zh-TW/prompts.json
Labels: enhancement, size:XL, lgtm

#2385 Move .roorules to .roo/rules/
  .roo/rules/rules.md
  .roorules
Labels: size:M

#2384 Added to Vertex AI Provider gemini 2.5 Pro Preview
  src/shared/api.ts
Labels: enhancement, size:XS, lgtm

#2382 Add custom instructions for zh-TW
  .roo/rules-translate/001-general-rules.md
  .roo/rules-translate/instructions-zh-tw.md
  .roomodes
Labels: documentation, size:L

#2389 Don't automatically convert types when parsing XML
  src/utils/__tests__/xml.test.ts
  src/utils/xml.ts
Labels: enhancement, size:L

#2376 feat(settings): Rate-limit setting updated to be per-profile
  .changeset/curvy-masks-scream.md
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.test.ts
  src/core/config/__tests__/importExport.test.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/settings/AdvancedSettings.tsx
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/components/settings/RateLimitSecondsControl.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/__tests__/ApiOptions.test.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm

#2393 v3.11.9
  .changeset/cuddly-bats-look.md
Labels: size:XS

#2394 Changeset version bump
  .changeset/cuddly-bats-look.md
  .changeset/curvy-masks-scream.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, changelog-ready, size:S

#2396 Update CHANGELOG.md
  CHANGELOG.md
Labels: size:XS

#2381 Add custom instructions for zh-CN
  .roo/rules-translate/instructions-zh-cn.md
Labels: documentation, size:L

#2401 Fix cache usage tracking for openai-compatible
  src/api/providers/openai.ts
Labels: bug, size:XS

#2406 Update CHANGELOG.md
  CHANGELOG.md
Labels: size:XS

#2405 Fix a bug not to read rule files properly, under nested `.roo/rules` directories
  .changeset/poor-dolphins-brush.md
  src/core/prompts/sections/__tests__/custom-instructions.test.ts
  src/core/prompts/sections/custom-instructions.ts
Labels: bug, size:M, lgtm

#2408 Clean up global `rateLimitSeconds` & fully shift to provider version
  evals/packages/types/src/roo-code-defaults.ts
  evals/packages/types/src/roo-code.ts
  src/core/Cline.ts
  src/core/config/ProviderSettingsManager.ts
  src/core/webview/ClineProvider.ts
  src/core/webview/__tests__/ClineProvider.test.ts
  src/core/webview/webviewMessageHandler.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/settings/ExperimentalSettings.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/context/__tests__/ExtensionStateContext.test.tsx
Labels: size:M, lgtm

#2326 feat: Add CommandOutputViewer component and integrate it into ChatRow
  webview-ui/src/__tests__/components/common/CommandOutputViewer.test.tsx
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/common/CommandOutputViewer.tsx
Labels: enhancement, size:L, lgtm

#2410 Fix typo in diff prompt
  src/core/diff/strategies/multi-search-replace.ts
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
Labels: documentation, size:XS

#2409 Remove extra colon from rules content
  src/core/prompts/sections/custom-instructions.ts
Labels: size:XS

#2413 v3.11.10
  .changeset/tame-squids-teach.md
Labels: size:XS

#2412 Changeset version bump
  .changeset/poor-dolphins-brush.md
  .changeset/tame-squids-teach.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2399 Add the option to use a custom Host header for openai-compatible
  .vscodeignore
  src/api/providers/openai.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L

#2421 Follow symlinks for rules files
  src/core/prompts/sections/__tests__/custom-instructions.test.ts
  src/core/prompts/sections/custom-instructions.ts
Labels: enhancement, size:L

#2420 feat: enhance tree-sitter parsers for multiple languages
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.cpp.test.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.go.test.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.java.test.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.python.test.ts
  src/services/tree-sitter/__tests__/parseSourceCodeDefinitions.tsx.test.ts
  src/services/tree-sitter/queries/cpp.ts
  src/services/tree-sitter/queries/go.ts
  src/services/tree-sitter/queries/java.ts
  src/services/tree-sitter/queries/python.ts
  src/services/tree-sitter/queries/tsx.ts
  src/services/tree-sitter/queries/typescript.ts
Labels: enhancement, size:XXL, lgtm

#2340 refactor: improve readFileTool XML output format
  src/core/__tests__/read-file-maxReadFileLine.test.ts
  src/core/__tests__/read-file-xml.test.ts
  src/core/tools/readFileTool.ts
  src/integrations/misc/__tests__/extract-text.test.ts
  src/integrations/misc/__tests__/read-lines.test.ts
  src/integrations/misc/extract-text.ts
  src/integrations/misc/read-lines.ts
Labels: enhancement, size:XXL, lgtm

#2426 Improve subtasks UI
  src/core/Cline.ts
  src/core/tools/attemptCompletionTool.ts
  src/core/webview/ClineProvider.ts
  src/exports/api.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:L

#2433 Add o1-pro to api.ts
  src/shared/api.ts
Labels: enhancement, size:XS, lgtm

#2383 Add custom instructions for de
  .roo/rules-translate/instructions-de.md
Labels: documentation, size:S

#2435 v3.11.11
  .changeset/khaki-laws-fold.md
Labels: size:XS

#2438 API fixes
  .tool-versions
  src/exports/api.ts
Labels: size:S

#2441 More sane evals default concurrency + staggered startup
  evals/apps/cli/src/index.ts
Labels: size:S

#2442 Fix gh fork command
  evals/scripts/setup.sh
Labels: size:XS

#2452 Add a script to copy eval run results to Turso
  evals/packages/db/package.json
  evals/packages/db/scripts/copy-run.mts
  evals/turbo.json
Labels: size:L

#2453 Fall back on aggressive line number stripping in diffs
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/integrations/misc/__tests__/extract-text.test.ts
  src/integrations/misc/extract-text.ts
Labels: bug, size:L, lgtm

#2449 Make Grok3 streaming work with OpenAI Compatible
  src/api/providers/__tests__/openai.test.ts
  src/api/providers/openai.ts
Labels: enhancement, size:M, lgtm

#2454 v3.11.12
  .changeset/gold-jokes-lie.md
Labels: size:XS

#2455 Changeset version bump
  .changeset/gold-jokes-lie.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2464 `.direnv` directory should not be packaged
  .vscodeignore
Labels: enhancement, size:XS, lgtm

#2440 feat: Add file context tracking system
  src/core/Cline.ts
  src/core/__tests__/Cline.test.ts
  src/core/__tests__/read-file-maxReadFileLine.test.ts
  src/core/__tests__/read-file-xml.test.ts
  src/core/context-tracking/FileContextTracker.ts
  src/core/context-tracking/FileContextTrackerTypes.ts
  src/core/mentions/index.ts
  src/core/tools/applyDiffTool.ts
  src/core/tools/insertContentTool.ts
  src/core/tools/listCodeDefinitionNamesTool.ts
  src/core/tools/readFileTool.ts
  src/core/tools/searchAndReplaceTool.ts
  src/core/tools/writeToFileTool.ts
  src/shared/globalFileNames.ts
Labels: enhancement, size:L, lgtm

#2470 Bug Fixed: Chinese i18n css error
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/i18n/locales/zh-CN/settings.json
Labels: bug, size:XS, lgtm

#2473 Modification of AWS Bedrock to Amazon Bedrock
  .github/ISSUE_TEMPLATE/bug_report.yml
  cline_docs/bedrock/bedrock-cache-strategy-documentation.md
  cline_docs/bedrock/model-identification.md
  evals/packages/types/src/roo-code.ts
  src/api/providers/bedrock.ts
  src/schemas/index.ts
  src/shared/api.ts
  src/shared/aws_regions.ts
  webview-ui/src/components/settings/constants.ts
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
  webview-ui/src/utils/validate.ts
Labels: documentation, size:L

#2476 Move "Previously Roo Cline" to description from title
  package.json
Labels: documentation, size:XS, lgtm

#2479 Update README.md to reflect new branding and add demo GIF;
  README.md
  assets/docs/demo.gif
Labels: documentation, size:XS, lgtm

#2478 Better display of diff errors
  src/core/tools/applyDiffTool.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
Labels: enhancement, size:L

#2451 docs: update settings.md with comprehensive steps
  cline_docs/settings.md
Labels: documentation, size:L, lgtm

#2485 Fix discard changes in settings
  webview-ui/src/App.tsx
Labels: bug, size:XS

#2481 Exclude demo gif from extension build
  .vscodeignore
Labels: size:XS

#2494 ♻️ refactor(webview): move webview HTML generation to WebviewHTMLManager
  src/core/webview/ClineProvider.ts
  src/core/webview/WebviewHTMLManager.ts
Labels: enhancement, size:L, lgtm

#2456 Terminal improvements: command delay, PowerShell counter, and ZSH EOL mark
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/integrations/terminal/Terminal.ts
  src/integrations/terminal/TerminalProcess.ts
  src/integrations/terminal/TerminalRegistry.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.bash.test.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.cmd.test.ts
  src/integrations/terminal/__tests__/TerminalProcessExec.pwsh.test.ts
  src/integrations/terminal/__tests__/TerminalRegistry.test.ts
  src/schemas/index.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/ChatRow.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/components/settings/TerminalSettings.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/i18n/locales/ca/chat.json
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/chat.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/chat.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/chat.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/chat.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/chat.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/chat.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/chat.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/chat.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/chat.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/chat.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/chat.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/chat.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/chat.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/chat.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:XL, lgtm

#2427 fix: preserve content integrity in VS Code LM provider
  src/api/providers/vscode-lm.ts
Labels: bug, size:M, lgtm

#2502 Revert "♻️ refactor(webview): move webview HTML generation to WebviewHTMLManager"
  src/core/webview/ClineProvider.ts
  src/core/webview/WebviewHTMLManager.ts
Labels: size:L

#2504 Changeset version bump
  .changeset/loud-meals-teach.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2505 Evals fixes
  evals/apps/cli/src/index.ts
  evals/apps/web/src/app/runs/new/new-run.tsx
  evals/packages/db/drizzle.config.ts
  evals/packages/db/src/db.ts
  evals/packages/db/src/queries/taskMetrics.ts
Labels: size:L

#2513 Fix bug not to respect symbolic linked rules, if target is a directory or another symbolic link
  .changeset/metal-papayas-think.md
  src/core/prompts/sections/__tests__/custom-instructions.test.ts
  src/core/prompts/sections/custom-instructions.ts
Labels: bug, size:L, lgtm

#2517 Changeset version bump
  .changeset/metal-papayas-think.md
  .changeset/tough-coats-hear.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2265 Control evals concurrency in web app
  evals/apps/cli/src/index.ts
  evals/apps/web/package.json
  evals/apps/web/src/app/runs/new/new-run.tsx
  evals/apps/web/src/components/ui/index.ts
  evals/apps/web/src/components/ui/slider.tsx
  evals/apps/web/src/lib/schemas.ts
  evals/package.json
  evals/packages/db/drizzle/0002_white_flatman.sql
  evals/packages/db/drizzle/meta/0002_snapshot.json
  evals/packages/db/drizzle/meta/_journal.json
  evals/packages/db/src/schema.ts
  evals/pnpm-lock.yaml
  evals/scripts/setup.sh
  src/core/context-tracking/FileContextTracker.ts
Labels: size:L

#2518 Add reasoningEffort to provider settings schema
  evals/packages/types/src/roo-code-defaults.ts
  evals/packages/types/src/roo-code.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
Labels: enhancement, size:M

#2515 Fix: Remove 'v' prefix from Node.js version in .tool-versions file
  .tool-versions
Labels: size:XS, lgtm

#2520 Evals enhancements: delete runs, show all run instead of just completed runs
  evals/.tool-versions
  evals/apps/web/package.json
  evals/apps/web/src/app/home.tsx
  evals/apps/web/src/components/ui/alert-dialog.tsx
  evals/apps/web/src/components/ui/dropdown-menu.tsx
  evals/apps/web/src/components/ui/index.ts
  evals/apps/web/src/lib/server/runs.ts
  evals/packages/db/src/queries/runs.ts
  evals/pnpm-lock.yaml
Labels: size:L

#2524 Fix node version string when running asdf install nodejs
  evals/scripts/setup.sh
Labels: size:XS

#2528 Fix duplicate mention suggestion
  webview-ui/src/utils/context-mentions.ts
Labels: bug, size:S, lgtm

#2538 Fix to Bedrock ARN validation
  src/api/providers/bedrock.ts
  webview-ui/src/utils/validate.ts
Labels: size:XS, lgtm

#2531 Add Anthropic option to pass API Token as Authorization header instead of X-Api-Key for the custom base URL
  evals/packages/types/src/roo-code.ts
  src/api/providers/__tests__/anthropic.test.ts
  src/api/providers/anthropic.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  webview-ui/src/components/settings/ApiOptions.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:M, lgtm

#2530 Fix AWS token expiry issue when cached token expires when using AWS Profile for Bedrock (#2469)
  src/api/providers/bedrock.ts
Labels: bug, size:XS, lgtm

#2526 Filter & Search Workspace Task History
  webview-ui/package-lock.json
  webview-ui/package.json
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/HistoryView.tsx
  webview-ui/src/components/history/useTaskSearch.ts
  webview-ui/src/components/ui/checkbox.tsx
  webview-ui/src/components/ui/index.ts
  webview-ui/src/i18n/locales/ca/history.json
  webview-ui/src/i18n/locales/de/history.json
  webview-ui/src/i18n/locales/en/history.json
  webview-ui/src/i18n/locales/es/history.json
  webview-ui/src/i18n/locales/fr/history.json
  webview-ui/src/i18n/locales/hi/history.json
  webview-ui/src/i18n/locales/it/history.json
  webview-ui/src/i18n/locales/ja/history.json
  webview-ui/src/i18n/locales/ko/history.json
  webview-ui/src/i18n/locales/pl/history.json
  webview-ui/src/i18n/locales/pt-BR/history.json
  webview-ui/src/i18n/locales/tr/history.json
  webview-ui/src/i18n/locales/vi/history.json
  webview-ui/src/i18n/locales/zh-CN/history.json
  webview-ui/src/i18n/locales/zh-TW/history.json
Labels: enhancement, size:L, lgtm

#2552 docs: document process for adding new settings
  cline_docs/settings.md
Labels: documentation, size:L, lgtm

#2523 Add localization support for Roo Code extension in multiple languages
  package.json
  package.nls.ca.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.hi.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko.json
  package.nls.pl.json
  package.nls.pt-BR.json
  package.nls.tr.json
  package.nls.vi.json
  package.nls.zh-CN.json
  package.nls.zh-TW.json
Labels: enhancement, size:XL, lgtm

#2541 feature: Closable welcome message
  src/core/webview/ClineProvider.ts
  src/core/webview/webviewMessageHandler.ts
  src/exports/roo-code.d.ts
  src/exports/types.ts
  src/schemas/index.ts
  src/shared/ExtensionMessage.ts
  src/shared/WebviewMessage.ts
  webview-ui/src/components/chat/ChatView.tsx
  webview-ui/src/components/settings/InterfaceSettings.tsx
  webview-ui/src/components/settings/SettingsView.tsx
  webview-ui/src/context/ExtensionStateContext.tsx
  webview-ui/src/i18n/locales/ca/settings.json
  webview-ui/src/i18n/locales/de/settings.json
  webview-ui/src/i18n/locales/en/settings.json
  webview-ui/src/i18n/locales/es/settings.json
  webview-ui/src/i18n/locales/fr/settings.json
  webview-ui/src/i18n/locales/hi/settings.json
  webview-ui/src/i18n/locales/it/settings.json
  webview-ui/src/i18n/locales/ja/settings.json
  webview-ui/src/i18n/locales/ko/settings.json
  webview-ui/src/i18n/locales/pl/settings.json
  webview-ui/src/i18n/locales/pt-BR/settings.json
  webview-ui/src/i18n/locales/tr/settings.json
  webview-ui/src/i18n/locales/vi/settings.json
  webview-ui/src/i18n/locales/zh-CN/settings.json
  webview-ui/src/i18n/locales/zh-TW/settings.json
Labels: enhancement, size:L, lgtm

#2555 Evals improvements
  evals/apps/cli/package.json
  evals/apps/cli/src/index.ts
  evals/apps/web/src/app/runs/[id]/run.tsx
  evals/apps/web/src/app/runs/[id]/task-status.tsx
  evals/apps/web/src/app/runs/new/new-run.tsx
  evals/apps/web/src/hooks/use-process-tree.ts
  evals/apps/web/src/hooks/use-run-status.ts
  evals/packages/db/src/schema.ts
  evals/packages/ipc/src/client.ts
  evals/packages/ipc/src/server.ts
  evals/packages/types/src/roo-code-defaults.ts
  evals/packages/types/src/roo-code.ts
  evals/pnpm-lock.yaml
  evals/scripts/setup.sh
Labels: enhancement, size:L

#2554 fix build vsix package
  package-lock.json
  package.json
Labels: bug, size:XS, lgtm

#2560 fix: background color for new profile dialog
  webview-ui/src/components/settings/ApiConfigManager.tsx
Labels: size:XS, lgtm

#2570 More unit test kill -9 fixes
  evals/apps/cli/src/index.ts
  evals/packages/db/src/schema.ts
Labels: size:M

#2573 Support all providers in evals settings
  evals/apps/web/src/app/runs/new/new-run.tsx
Labels: size:M

#2572 fix: Restore focus ring for VSCodeButton component
  webview-ui/src/index.css
Labels: size:XS, lgtm

#2574 Revert "Add o1-pro to api.ts"
  src/shared/api.ts
Labels: size:XS

#2582 Add workspace filter to historypreview as well
  webview-ui/src/components/history/HistoryPreview.tsx
  webview-ui/src/components/history/HistoryView.tsx
Labels: enhancement, size:S

#2584 Update NLS translations
  package.nls.ca.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.hi.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko.json
  package.nls.pl.json
  package.nls.pt-BR.json
  package.nls.tr.json
  package.nls.vi.json
  package.nls.zh-CN.json
  package.nls.zh-TW.json
Labels: documentation, size:M

#2586 v3.11.15
  .changeset/good-lemons-hunt.md
Labels: size:XS

#2587 Changeset version bump
  .changeset/good-lemons-hunt.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2142 feat: Add modelId support when exporting tasks
  src/core/Cline.ts
  src/core/webview/ClineProvider.ts
  webview-ui/src/components/settings/ApiOptions.tsx
Labels: enhancement, size:S, lgtm

#2604 Update log messages for Cline instances to Roo Code instances in regi…
  src/activate/__tests__/registerCommands.test.ts
  src/activate/registerCommands.ts
Labels: enhancement, size:XS, lgtm

#2605 Add GPT 4.1
  .changeset/selfish-dancers-heal.md
  src/shared/api.ts
Labels: enhancement, size:M, lgtm

#2607 Fix test
  .changeset/purple-oranges-eat.md
  src/api/providers/__tests__/openai-native.test.ts
Labels: size:S

#2606 Changeset version bump
  .changeset/purple-oranges-eat.md
  .changeset/selfish-dancers-heal.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: changelog-ready, size:S

#2567 Fix overdependence on start/end lines in diff strategy
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
Labels: size:L, lgtm

#2611 Parse providers individually
  src/core/config/ProviderSettingsManager.ts
  src/core/config/__tests__/ProviderSettingsManager.test.ts
Labels: enhancement, size:M, lgtm

#2543 Fix eslint error about --ext option by remove it
  e2e/package.json
  evals/apps/cli/package.json
  evals/packages/db/package.json
  evals/packages/ipc/package.json
  evals/packages/lib/package.json
  evals/packages/types/package.json
  package.json
  webview-ui/package.json
Labels: size:S, lgtm

#2615 Remove the end_line from the multi_diff instructions and logic
  src/core/diff/strategies/__tests__/multi-search-replace.test.ts
  src/core/diff/strategies/multi-search-replace.ts
  src/core/prompts/__tests__/__snapshots__/system.test.ts.snap
  src/core/tools/applyDiffTool.ts
Labels: size:L, lgtm

#2616 Fix openai cache tracking and cost estimates
  src/api/providers/__tests__/openai-native.test.ts
  src/api/providers/openai-native.ts
  src/shared/api.ts
Labels: size:L, lgtm

#2431 feat: implement fuzzy search and dropdown grouping in SelectDropdown component
  webview-ui/src/components/ui/__tests__/select-dropdown.test.tsx
  webview-ui/src/components/ui/select-dropdown.tsx
  webview-ui/src/i18n/locales/ca/common.json
  webview-ui/src/i18n/locales/de/common.json
  webview-ui/src/i18n/locales/en/common.json
  webview-ui/src/i18n/locales/es/common.json
  webview-ui/src/i18n/locales/fr/common.json
  webview-ui/src/i18n/locales/hi/common.json
  webview-ui/src/i18n/locales/it/common.json
  webview-ui/src/i18n/locales/ja/common.json
  webview-ui/src/i18n/locales/ko/common.json
  webview-ui/src/i18n/locales/pl/common.json
  webview-ui/src/i18n/locales/pt-BR/common.json
  webview-ui/src/i18n/locales/tr/common.json
  webview-ui/src/i18n/locales/vi/common.json
  webview-ui/src/i18n/locales/zh-CN/common.json
  webview-ui/src/i18n/locales/zh-TW/common.json
Labels: enhancement, size:XL, lgtm
